function cameraX(){return clamp(player.x-Math.min(350,VW*.27),0,Math.max(0,END_X-VW+300))}
function round(x,y,w,h,r){ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x,y,w,h,r);else ctx.rect(x,y,w,h)}
function draw(){ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#05070d';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.setTransform(scale,0,0,scale,0,0);ctx.save();if(shake>.2)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);const cam=cameraX();ctx.translate(-cam,0);drawWorld(cam);ctx.restore();if(flash>.01){ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle=`rgba(140,248,255,${flash*.24})`;ctx.fillRect(0,0,canvas.width,canvas.height)}}
function drawWorld(cam){
 const bg=ctx.createLinearGradient(0,0,0,H);bg.addColorStop(0,'#11182a');bg.addColorStop(.52,'#090d18');bg.addColorStop(1,'#04060b');ctx.fillStyle=bg;ctx.fillRect(cam,0,VW,H);
 const p1=cam*.16,p2=cam*.34;ctx.fillStyle='rgba(92,109,153,.045)';for(let x=Math.floor((cam-p1)/230)*230-230;x<cam+VW+250;x+=230){const sx=x+p1,h=130+((x/230)%5)*26;ctx.fillRect(sx,610-h,150,h)}
 ctx.fillStyle='rgba(116,143,196,.055)';for(let x=Math.floor((cam-p2)/170)*170-170;x<cam+VW+200;x+=170){const sx=x+p2,h=95+((x/170)%4)*32;ctx.fillRect(sx,610-h,110,h);ctx.fillStyle='rgba(140,248,255,.038)';for(let y=545-h;y<585;y+=31){ctx.fillRect(sx+16,y,14,7);ctx.fillRect(sx+48,y,14,7);ctx.fillRect(sx+78,y,10,7)}ctx.fillStyle='rgba(116,143,196,.055)'}
 ctx.fillStyle='#0e141e';ctx.fillRect(cam,FLOOR,VW,110);ctx.fillStyle='rgba(255,255,255,.027)';for(let x=Math.floor(cam/82)*82;x<cam+VW+100;x+=82)ctx.fillRect(x,FLOOR,2,110);ctx.fillStyle='rgba(109,124,255,.12)';ctx.fillRect(cam,FLOOR-3,VW,3);
 for(const s of SECTORS.slice(1)){ctx.fillStyle='rgba(140,248,255,.07)';ctx.fillRect(s.x,90,2,520)}
 if(player.x<900){label(720,420,'HALTEN','#ffd45c','HEAVY zerbricht Glas')}
 if(player.x<1460){label(1260,555,'LOSLASSEN','#8cf8ff','LIGHT schwebt über Lücken')}
 for(const o of objects){
  if(o.type==='pit'){ctx.fillStyle='#010207';ctx.fillRect(o.x,o.y,o.w,o.h);const g=ctx.createLinearGradient(o.x,o.y,o.x,o.y+o.h);g.addColorStop(0,'rgba(109,124,255,.10)');g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(o.x,o.y,o.w,o.h);ctx.fillStyle='rgba(140,248,255,.09)';ctx.fillRect(o.x,o.y,3,o.h);ctx.fillRect(o.x+o.w-3,o.y,3,o.h)}
  else if(o.type==='glass'&&!o.done){drawGlass(o)}
  else if(o.type==='ceiling'){ctx.save();ctx.fillStyle='#171e2a';round(o.x,o.y,o.w,o.h,22);ctx.fill();ctx.fillStyle='rgba(255,255,255,.035)';ctx.fillRect(o.x+22,o.y+18,o.w-44,5);ctx.fillStyle='rgba(255,212,92,.12)';ctx.fillRect(o.x,o.y+o.h-5,o.w,5);ctx.restore()}
  else if(o.type==='pad'){ctx.save();ctx.shadowColor='#ffd45c';ctx.shadowBlur=o.done?20:12;ctx.fillStyle=o.done?'#ffe899':'#ffd45c';round(o.x,o.y,o.w,o.h,8);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#5d4700';for(let x=o.x+14;x<o.x+o.w-8;x+=24){ctx.beginPath();ctx.moveTo(x,o.y+11);ctx.lineTo(x+8,o.y+4);ctx.lineTo(x+16,o.y+11);ctx.fill()}ctx.restore()}
  else if(o.type==='fragile'&&!o.done){ctx.fillStyle='#25232c';ctx.fillRect(o.x,o.y,o.w,o.h);ctx.strokeStyle='#ffd45c';ctx.lineWidth=2;for(let x=o.x+24;x<o.x+o.w;x+=42){ctx.beginPath();ctx.moveTo(x,o.y+3);ctx.lineTo(x+12,o.y+17);ctx.lineTo(x+2,o.y+o.h-2);ctx.stroke()}}
  else if(o.type==='fan'){ctx.save();ctx.fillStyle='rgba(140,248,255,.025)';ctx.fillRect(o.x,o.y,o.w,o.h);ctx.strokeStyle='rgba(140,248,255,.15)';ctx.strokeRect(o.x,o.y,o.w,o.h);ctx.globalAlpha=.36;for(let i=0;i<6;i++){const yy=o.y+o.h-(worldTime*155+i*68)%(o.h+80);ctx.strokeStyle='#8cf8ff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(o.x+30,yy);ctx.quadraticCurveTo(o.x+o.w*.5,yy-42,o.x+o.w-28,yy-10);ctx.stroke()}ctx.restore()}
  else if(o.type==='checkpoint'){ctx.save();ctx.strokeStyle=o.done?'#72efad':'rgba(114,239,173,.38)';ctx.lineWidth=4;ctx.shadowColor='#72efad';ctx.shadowBlur=o.done?18:7;ctx.beginPath();ctx.moveTo(o.x,o.y);ctx.lineTo(o.x,o.y+o.h);ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle=o.done?'#72efad':'rgba(114,239,173,.7)';ctx.font='900 10px sans-serif';ctx.textAlign='center';ctx.fillText('CHECK',o.x,o.y-12);ctx.restore()}
  else if(o.type==='crusher'){drawCrusher(o)}
  else if(o.type==='finish'){ctx.save();ctx.shadowColor='#72efad';ctx.shadowBlur=24;ctx.fillStyle='#72efad';ctx.fillRect(o.x,o.y,o.w,o.h);ctx.shadowBlur=0;ctx.fillStyle='#10251a';ctx.save();ctx.translate(o.x+o.w/2,o.y+o.h/2);ctx.rotate(-Math.PI/2);ctx.font='950 14px sans-serif';ctx.textAlign='center';ctx.fillText('FINISH',0,5);ctx.restore();ctx.restore()}
 }
 for(const f of flux){if(f.taken)continue;const bob=Math.sin(worldTime*4+f.x*.01)*6;ctx.save();ctx.translate(f.x,f.y+bob);ctx.rotate(worldTime*.8);ctx.shadowColor='#bba7ff';ctx.shadowBlur=22;ctx.fillStyle='#bba7ff';ctx.beginPath();for(let i=0;i<8;i++){const a=i*Math.PI/4,r=i%2?9:18;const x=Math.cos(a)*r,y=Math.sin(a)*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='rgba(255,255,255,.65)';ctx.beginPath();ctx.arc(-4,-5,4,0,Math.PI*2);ctx.fill();ctx.restore()}
 for(const t of trails){ctx.globalAlpha=clamp(t.life/.34,0,1)*.22;ctx.fillStyle=t.heavy?'#ffd45c':'#8cf8ff';ctx.beginPath();ctx.arc(t.x,t.y,t.r,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;
 for(const r of rings){ctx.globalAlpha=clamp(r.life/r.max,0,1);ctx.strokeStyle=r.color;ctx.lineWidth=4;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,Math.PI*2);ctx.stroke()}ctx.globalAlpha=1;
 for(const s of shockwaves){ctx.globalAlpha=clamp(s.life/s.max,0,1)*.7;ctx.strokeStyle=s.color;ctx.lineWidth=6;ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.stroke()}ctx.globalAlpha=1;
 for(const p of particles){ctx.globalAlpha=clamp(p.life/.55,0,1);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size)}ctx.globalAlpha=1;
 for(const s of sparks){ctx.globalAlpha=clamp(s.life/.35,0,1);ctx.strokeStyle='#ffd45c';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.x-s.vx*.026,s.y-s.vy*.026);ctx.stroke()}ctx.globalAlpha=1;
 drawBall();
 if(toastT>0){ctx.save();ctx.globalAlpha=clamp(toastT/.25,0,1);ctx.font='950 15px sans-serif';ctx.textAlign='center';const tx=player.x,ty=Math.max(125,player.y-84),w=Math.max(170,ctx.measureText(toastText).width+34);ctx.fillStyle='rgba(5,8,14,.86)';round(tx-w/2,ty-21,w,38,19);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.09)';ctx.stroke();ctx.fillStyle=toastText.includes('PERFECT')?'#ffe68e':'#f7fbff';ctx.fillText(toastText,tx,ty+4);ctx.restore()}
}
function label(x,y,title,color,sub){ctx.save();ctx.textAlign='center';ctx.font='950 16px sans-serif';ctx.fillStyle=color;ctx.fillText(title,x,y);ctx.font='800 10px sans-serif';ctx.fillStyle='rgba(220,232,246,.58)';ctx.fillText(sub,x,y+20);ctx.restore()}
function drawGlass(o){ctx.save();ctx.fillStyle='rgba(255,212,92,.065)';ctx.fillRect(o.x,o.y,o.w,o.h);ctx.strokeStyle='rgba(255,222,121,.74)';ctx.lineWidth=2;ctx.strokeRect(o.x,o.y,o.w,o.h);ctx.shadowColor='#ffd45c';ctx.shadowBlur=13;ctx.beginPath();for(let y=o.y+18;y<o.y+o.h-15;y+=42){ctx.moveTo(o.x+4,y);ctx.lineTo(o.x+o.w-4,y+24)}ctx.stroke();ctx.restore()}
function drawCrusher(o){const cyc=(Math.sin(worldTime*2.4+o.phase)+1)/2,bottom=125+cyc*255;ctx.save();ctx.fillStyle='#202632';round(o.x,88,o.w,bottom-88,12);ctx.fill();ctx.fillStyle='#ff5e78';ctx.shadowColor='#ff5e78';ctx.shadowBlur=10;ctx.fillRect(o.x,bottom-7,o.w,7);ctx.shadowBlur=0;for(let x=o.x+8;x<o.x+o.w;x+=18){ctx.fillStyle='rgba(255,255,255,.05)';ctx.fillRect(x,105,8,Math.max(0,bottom-125))}ctx.restore()}
function drawBall(){ctx.save();ctx.translate(player.x,player.y);ctx.rotate(player.rot);if(player.heavy){ctx.shadowColor='rgba(255,212,92,.22)';ctx.shadowBlur=18;const g=ctx.createRadialGradient(-8,-10,4,0,0,player.r);g.addColorStop(0,'#f7f2e7');g.addColorStop(.12,'#bcc4d0');g.addColorStop(.48,'#5d6573');g.addColorStop(1,'#1b2029');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,player.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='rgba(255,212,92,.58)';ctx.lineWidth=3;ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.18)';ctx.lineWidth=2;for(let a=0;a<Math.PI*2;a+=Math.PI/3){ctx.beginPath();ctx.moveTo(Math.cos(a)*8,Math.sin(a)*8);ctx.lineTo(Math.cos(a)*(player.r-6),Math.sin(a)*(player.r-6));ctx.stroke()}}else{ctx.shadowColor='#78efff';ctx.shadowBlur=34;const g=ctx.createRadialGradient(-10,-12,3,0,0,player.r);g.addColorStop(0,'#fff');g.addColorStop(.18,'#c9fbff');g.addColorStop(.55,'#79eefa');g.addColorStop(1,'#596cff');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,player.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=11;ctx.strokeStyle='rgba(255,255,255,.62)';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='rgba(255,255,255,.35)';ctx.beginPath();ctx.arc(-10,-12,6,0,Math.PI*2);ctx.fill()}ctx.restore()}
function frame(now){const dt=Math.min(.03,(now-last)/1000||.016);last=now;update(dt);draw();requestAnimationFrame(frame)}
ui.play.onclick=()=>{audio()?.resume?.();ui.intro.classList.add('hidden');reset();running=true};ui.again.onclick=()=>{ui.result.classList.add('hidden');reset();running=true};ui.restart.onclick=()=>{reset();running=true};
reset();requestAnimationFrame(frame);window.__HL2__={player,objects,flux,reset,setMode,state:()=>({x:player.x,y:player.y,heavy:player.heavy,points,combo,bestCombo,fluxCount,finished,worldTime,checkpointX})};
