const APP_VERSION='5.0';
const STORAGE_KEY='mk-v5';
const DAYS=['Montag','Dienstag','Mittwoch','Donnerstag','Freitag'];
const DAY_KEYS=['mon','tue','wed','thu','fri'];
const ICON_RULES=[
  [/rucksack/i,'🎒'],[/trinkflasche|flasche/i,'🥤'],[/znüni|znueni|proviant|snack/i,'🍎'],[/turn|sport|schuhe|hallenschuhe/i,'👟'],[/helm/i,'🪖'],[/regen|regenschutz/i,'🌧️'],[/geld|chf|franken/i,'💰'],[/unterschrift|unterschrieben/i,'✍️'],[/leuchtweste|weste/i,'🦺'],[/buch|bibliothek/i,'📚'],[/schulreise|ausflug/i,'🚌'],[/wald/i,'🌲'],[/schwimm/i,'🏊'],[/musik|instrument/i,'🎵']
];
function iconFor(text=''){for(const [r,i] of ICON_RULES)if(r.test(text))return i;return '📌'}
const $=id=>document.getElementById(id);
const deep=x=>JSON.parse(JSON.stringify(x));
const uid=()=>crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
const fmtDate=d=>new Intl.DateTimeFormat('de-CH',{weekday:'long',day:'2-digit',month:'2-digit'}).format(d);
const isoDate=d=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)};
const CHILD_COLORS=['blue','green','orange','purple'];
const seed={children:[{id:'jayden',name:'Jayden'},{id:'fynn',name:'Fynn'},{id:'elia',name:'Elia'}],tasks:{jayden:[['Rucksack',0],['Helm',0],['Turnsachen',0]],fynn:[['Rucksack',0],['Trinkflasche',0]],elia:[['Rucksack',0],['Trinkflasche',0],['Znünibox',0],['Leuchtweste',0]]},timetable:{jayden:{mon:['07:45–11:50','13:30–15:10'],tue:['07:45–11:50','13:30–15:10'],wed:['07:45–11:50',''],thu:['07:45–11:50','13:30–15:10'],fri:['07:45–11:50','13:30–15:10']},fynn:{mon:['08:20–11:50','13:30–15:10'],tue:['08:20–11:50','13:30–15:10'],wed:['08:20–11:50',''],thu:['08:20–11:50','13:30–15:10'],fri:['08:20–11:50','13:30–15:10']},elia:{mon:['08:20–11:45','13:30–15:00'],tue:['08:20–11:45','13:30–15:00'],wed:['08:20–11:45',''],thu:['08:20–11:45','13:30–15:00'],fri:['08:20–11:45','13:30–15:00']}},events:[{id:'demo-trip',child:'jayden',title:'Schulreise',date:'2026-08-20',start:'07:00',end:'17:00',location:'Schulhaus',items:['CHF 5 mitgeben','Gute Schuhe','Rucksack','Trinkflasche']}],documents:[]};
let state=load();let homeFilter='all',weekFilter='all',docFilter='all',weekOffset=0,dayMode='tomorrow',currentFile=null,pendingReview=null;
function load(){try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY));if(v)return v;const older=JSON.parse(localStorage.getItem('mk-v4')||'null');if(older){const n=deep(seed);n.children=older.children||n.children;n.tasks=older.tasks||n.tasks;n.timetable=older.tt||older.timetable||n.timetable;n.events=older.events||[];n.documents=older.docs||[];return n}}catch{}return deep(seed)}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderAll()}
function child(id){return state.children.find(c=>c.id===id)}
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('on');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('on'),1800)}
function chips(el,value,cb){el.innerHTML=`<button class="chip ${value==='all'?'on':''}" data-v="all">Alle</button>`+state.children.map(c=>`<button class="chip ${value===c.id?'on':''}" data-v="${c.id}">${esc(c.name)}</button>`).join('');el.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>cb(b.dataset.v))}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function taskMarkup(t,i,cid){const [name,done]=t;return `<div class="task ${done?'done':''}" data-c="${cid}" data-i="${i}"><button class="check">${done?'✓':''}</button><div class="symbol">${iconFor(name)}</div><div class="task-main"><b>${esc(name)}</b><small>für ${dayMode==='today'?'heute':'morgen'}</small></div></div>`}
function renderHome(){chips($('homeFilter'),homeFilter,v=>{homeFilter=v;renderHome()});const target=new Date();if(dayMode==='tomorrow')target.setDate(target.getDate()+1);$('heroDate').textContent=fmtDate(target);$('todayToggle').classList.toggle('on',dayMode==='today');$('tomorrowToggle').classList.toggle('on',dayMode==='tomorrow');let total=0,done=0;const cs=state.children.filter(c=>homeFilter==='all'||homeFilter===c.id);$('taskCards').innerHTML=cs.map((c,ci)=>{const arr=state.tasks[c.id]||[];total+=arr.length;done+=arr.filter(x=>x[1]).length;return `<div class="child-card"><div class="child-head"><div class="child-title"><div class="kid-avatar ${CHILD_COLORS[ci%CHILD_COLORS.length]}">👦</div><div><b>${esc(c.name)}</b><div class="muted">${arr.filter(x=>x[1]).length} von ${arr.length} bereit</div></div></div><span class="badge">${arr.length?Math.round(arr.filter(x=>x[1]).length/arr.length*100):100}%</span></div>${arr.map((t,i)=>taskMarkup(t,i,c.id)).join('')}</div>`}).join('')||'<div class="empty">Keine Einträge.</div>';$('taskCards').querySelectorAll('.task').forEach(r=>r.querySelector('.check').onclick=()=>{const a=state.tasks[r.dataset.c][+r.dataset.i];a[1]=a[1]?0:1;save()});const pct=total?Math.round(done/total*100):100;$('meterBar').style.width=pct+'%';$('progressText').textContent=`${done} von ${total} erledigt`;$('progressPct').textContent=pct+'%';$('heroTitle').textContent=pct===100?'Alles bereit. ✓':'Alles bereit für morgen?';$('heroCopy').textContent=pct===100?'Sehr gut – für die ausgewählten Kinder ist alles vorbereitet.':'Ein kurzer Blick – dann ist klar, was jedes Kind braucht.';renderQuick()}
function renderQuick(){const items=['Rucksack','Trinkflasche','Znünibox','Turnsachen','Helm','Regenjacke','CHF 5 mitgeben','Unterschrift'];$('quickAdd').innerHTML=items.map(x=>`<button data-x="${esc(x)}"><span>${iconFor(x)}</span>${esc(x.replace('CHF 5 mitgeben','Geld'))}</button>`).join('');$('quickAdd').querySelectorAll('button').forEach(b=>b.onclick=()=>{const cid=homeFilter==='all'?state.children[0]?.id:homeFilter;if(!cid)return;state.tasks[cid]??=[];if(!state.tasks[cid].some(x=>x[0]===b.dataset.x))state.tasks[cid].push([b.dataset.x,0]);save();toast(`${iconFor(b.dataset.x)} zu ${child(cid)?.name} hinzugefügt`)})}
function mondayForOffset(){const n=new Date();n.setHours(12,0,0,0);const w=(n.getDay()+6)%7;n.setDate(n.getDate()-w+weekOffset*7);return n}
function weekDates(){const m=mondayForOffset();return DAY_KEYS.map((key,i)=>{const d=new Date(m);d.setDate(m.getDate()+i);return{key,date:d,iso:isoDate(d),label:DAYS[i]}})}
function renderWeek(){chips($('weekFilter'),weekFilter,v=>{weekFilter=v;renderWeek()});const ds=weekDates();$('weekRange').textContent=`${ds[0].date.toLocaleDateString('de-CH',{day:'2-digit',month:'2-digit'})} – ${ds[4].date.toLocaleDateString('de-CH',{day:'2-digit',month:'2-digit'})}`;const cs=state.children.filter(c=>weekFilter==='all'||weekFilter===c.id);$('weekList').innerHTML=ds.map(d=>{let inner='';cs.forEach((c,ci)=>{const z=state.timetable[c.id]?.[d.key]||['',''];if(z[0]||z[1])inner+=`<div class="schedule"><div class="schedule-time">${z[0]&&z[1]?'Schule':z[0]?'Morgen':'Nachm.'}</div><div><div class="kidline"><span class="kid-tag">👦 ${esc(c.name)}</span><b>${esc(z[0]||'')}</b>${z[1]?`<b> · ${esc(z[1])}</b>`:''}</div><small>${z[1]?'Vormittag & Nachmittag':'Nachmittag frei'}</small></div></div>`});state.events.filter(e=>e.date===d.iso&&(weekFilter==='all'||e.child===weekFilter)).forEach(e=>{const c=child(e.child);inner+=`<div class="event"><div class="event-top"><div class="event-icon">${iconFor(e.title)}</div><div class="event-main"><div class="event-title"><b>${esc(e.title)}</b><span class="kid-tag">👦 ${esc(c?.name||'')}</span></div><div class="event-meta">${e.start?`🕒 ${esc(e.start)}${e.end?'–'+esc(e.end):''}`:''}${e.location?`<br>📍 ${esc(e.location)}`:''}</div>${(e.items||[]).length?`<div class="pills">${e.items.map(x=>`<span class="pill">${iconFor(x)} ${esc(x)}</span>`).join('')}</div>`:''}</div></div></div>`});return `<div class="day"><div class="day-title"><span>${d.label}</span><span>${d.date.toLocaleDateString('de-CH',{day:'2-digit',month:'2-digit'})}</span></div>${inner||'<div class="empty">Keine Einträge.</div>'}</div>`}).join('')}
function renderFamily(){const html=state.children.map((c,ci)=>{state.timetable[c.id]??={};return `<div class="family-card"><div class="family-top"><div class="child-title"><div class="kid-avatar ${CHILD_COLORS[ci%CHILD_COLORS.length]}">👦</div><div><b>${esc(c.name)}</b><div class="muted">Stundenplan & Dokumente</div></div></div></div><div class="timetable"><div class="tt-row"><span></span><span class="tt-head">Vormittag</span><span class="tt-head">Nachmittag</span></div>${DAY_KEYS.map((k,i)=>{const z=state.timetable[c.id][k]||['',''];return `<div class="tt-row"><b>${DAYS[i].slice(0,2)}</b><input class="input tt-input" data-c="${c.id}" data-k="${k}" data-p="0" value="${esc(z[0])}" placeholder="frei"><input class="input tt-input" data-c="${c.id}" data-k="${k}" data-p="1" value="${esc(z[1])}" placeholder="frei"></div>`}).join('')}</div><button class="btn soft save-tt" data-c="${c.id}" style="width:100%;margin-top:10px">Stundenplan speichern</button></div>`}).join('');$('familyList').innerHTML=html;$('familyList').querySelectorAll('.save-tt').forEach(b=>b.onclick=()=>{const cid=b.dataset.c;state.timetable[cid]??={};$('familyList').querySelectorAll(`.tt-input[data-c="${cid}"]`).forEach(inp=>{state.timetable[cid][inp.dataset.k]??=['',''];state.timetable[cid][inp.dataset.k][+inp.dataset.p]=inp.value.trim()});save();toast('Stundenplan gespeichert')})}
function renderDocSelect(){const opts=state.children.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$('docChild').innerHTML=`<option value="auto">Kind automatisch erkennen</option>${opts}`}
function renderDocs(){chips($('docFilter'),docFilter,v=>{docFilter=v;renderDocs()});const docs=state.documents.filter(d=>docFilter==='all'||d.child===docFilter);$('docList').innerHTML=docs.length?docs.map(d=>`<div class="doc"><div class="doc-icon">${d.type==='timetable'?'🗓️':'📄'}</div><div class="doc-meta"><b>${esc(d.name)}</b><small>👦 ${esc(child(d.child)?.name||'Nicht zugeordnet')} · ${d.type==='timetable'?'Stundenplan':'Schuldokument'}${d.summary?`<br>${esc(d.summary)}`:''}</small></div><div class="doc-actions"><button class="mini-btn" data-open="${d.id}">Öffnen</button></div></div>`).join(''):'<div class="empty">Noch keine Dokumente gespeichert.</div>';$('docList').querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openStored(b.dataset.open))}
async function db(){return new Promise((res,rej)=>{const r=indexedDB.open('morgenklar-files',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('files'))r.result.createObjectStore('files')};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function putFile(id,f){const d=await db();return new Promise((res,rej)=>{const tx=d.transaction('files','readwrite');tx.objectStore('files').put(f,id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function getFile(id){const d=await db();return new Promise((res,rej)=>{const r=d.transaction('files').objectStore('files').get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function openStored(id){try{const f=await getFile(id);if(!f)return toast('Originaldatei nicht mehr verfügbar');window.open(URL.createObjectURL(f),'_blank')}catch{toast('Datei konnte nicht geöffnet werden')}}
function detectChild(text,chosen){if(chosen&&chosen!=='auto')return chosen;const low=text.toLowerCase();const matches=state.children.filter(c=>low.includes(c.name.toLowerCase()));return matches.length===1?matches[0].id:null}
function parseDateToken(text){let m=text.match(/\b(\d{1,2})[.\/-](\d{1,2})(?:[.\/-](\d{2,4}))?\b/);if(m){let y=m[3]?+m[3]:new Date().getFullYear();if(y<100)y+=2000;return `${y}-${String(+m[2]).padStart(2,'0')}-${String(+m[1]).padStart(2,'0')}`};const months={januar:1,februar:2,'märz':3,maerz:3,april:4,mai:5,juni:6,juli:7,august:8,september:9,oktober:10,november:11,dezember:12};m=text.match(/\b(\d{1,2})\.?\s*(Januar|Februar|März|Maerz|April|Mai|Juni|Juli|August|September|Oktober|November|Dezember)(?:\s+(\d{4}))?/i);if(m){const y=m[3]?+m[3]:new Date().getFullYear();return `${y}-${String(months[m[2].toLowerCase()]).padStart(2,'0')}-${String(+m[1]).padStart(2,'0')}`};return''}
function parseTimeRange(text){const m=text.match(/(?:von\s*)?(\d{1,2})(?:[:.]([0-5]\d))?\s*(?:uhr)?\s*(?:bis|[-–])\s*(\d{1,2})(?:[:.]([0-5]\d))?\s*(?:uhr)?/i);if(!m)return['',''];let a=+m[1],b=+m[3];if(/abend/i.test(text)&&b<12)b+=12;return[`${String(a).padStart(2,'0')}:${m[2]||'00'}`,`${String(b).padStart(2,'0')}:${m[4]||'00'}`]}
function parseLocation(text){const m=text.match(/(?:treffpunkt|ort)\s*[:\-]?\s*([^\n,.]{2,60})/i);return m?m[1].trim():''}
function extractItems(text){const out=[];const rules=[[/rucksack/i,'Rucksack'],[/trinkflasche/i,'Trinkflasche'],[/znüni|znueni|proviant/i,'Znüni / Proviant'],[/gute[nr]?\s+schuhe|festes schuhwerk/i,'Gute Schuhe'],[/turnsachen|sportzeug/i,'Turnsachen'],[/regenjacke|regenschutz/i,'Regenjacke'],[/leuchtweste/i,'Leuchtweste'],[/helm/i,'Helm'],[/unterschrift|unterschrieben/i,'Unterschrift'],[/bibliotheksbuch|bibliothek.*buch/i,'Bibliotheksbuch']];rules.forEach(([r,n])=>r.test(text)&&out.push(n));const m=text.match(/(?:chf|fr\.?|franken)\s*(\d+[.,]?\d*)|(\d+[.,]?\d*)\s*(?:chf|fr\.?|franken)/i);if(m)out.push(`CHF ${(m[1]||m[2]).replace(',','.')} mitgeben`);return[...new Set(out)]}
function titleFor(text){const map=[[/schulreise/i,'Schulreise'],[/ausflug/i,'Ausflug'],[/waldmorgen/i,'Waldmorgen'],[/sporttag/i,'Sporttag'],[/elternabend/i,'Elternabend'],[/fototermin|schulfoto/i,'Fototermin'],[/zahnarzt|zahn/i,'Zahnarzt / Zahnkontrolle'],[/ferien/i,'Ferien / Schulfrei']];for(const[r,n]of map)if(r.test(text))return n;return'Schulinformation'}
function splitMultiEvents(text){const lines=text.split(/\n+/).map(x=>x.trim()).filter(Boolean);const found=[];for(let i=0;i<lines.length;i++){if(parseDateToken(lines[i])){let chunk=lines.slice(Math.max(0,i-1),Math.min(lines.length,i+3)).join(' ');found.push(chunk)}}return found.length?found:[text]}
function parseNotice(text,chosen){const cid=detectChild(text,chosen);return splitMultiEvents(text).map(chunk=>{const[start,end]=parseTimeRange(chunk);return{id:uid(),child:cid,title:titleFor(chunk),date:parseDateToken(chunk),start,end,location:parseLocation(chunk),items:extractItems(chunk),sourceText:chunk}})}
function parseTimetable(text,chosen){const cid=detectChild(text,chosen);const out={};DAYS.forEach((day,i)=>{const re=new RegExp(`${day}[^\\n]{0,150}`,'i');const m=text.match(re);if(!m)return;const times=[...m[0].matchAll(/([01]?\d|2[0-3])[:.]([0-5]\d)/g)].map(x=>`${String(+x[1]).padStart(2,'0')}:${x[2]}`);let am='',pm='';if(times.length>=2)am=`${times[0]}–${times[1]}`;if(times.length>=4)pm=`${times[2]}–${times[3]}`;if(/nachmittag\s*frei|nur\s*(am\s*)?morgen|nur\s*vormittag/i.test(m[0]))pm='';if(am||pm)out[DAY_KEYS[i]]=[am,pm]});return{child:cid,out}}
function autoType(text){return /(montag|dienstag|mittwoch|donnerstag|freitag).*(\d{1,2}[:.]\d{2})/is.test(text)?'timetable':'notice'}
function showReview(payload){pendingReview=payload;const box=$('reviewBody');if(payload.type==='timetable'){const p=payload.data;box.innerHTML=`<div class="review-card"><div class="label">Kind</div><select id="rvChild">${state.children.map(c=>`<option value="${c.id}" ${c.id===p.child?'selected':''}>${esc(c.name)}</option>`).join('')}</select>${DAY_KEYS.map((k,i)=>{const z=p.out[k]||['',''];return `<div class="review-grid"><div class="wide label">${DAYS[i]}</div><input class="input rvtt" data-k="${k}" data-p="0" value="${esc(z[0])}" placeholder="Vormittag frei"><input class="input rvtt" data-k="${k}" data-p="1" value="${esc(z[1])}" placeholder="Nachmittag frei"></div>`}).join('')}</div>`}else{box.innerHTML=payload.data.map((e,i)=>`<div class="review-card" data-e="${i}"><div class="review-grid"><div><div class="label">Kind</div><select class="rvc">${state.children.map(c=>`<option value="${c.id}" ${c.id===e.child?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div><div class="label">Datum</div><input class="input rvd" type="date" value="${esc(e.date)}"></div><div class="wide"><div class="label">Anlass</div><input class="input rvt" value="${esc(e.title)}"></div><div><div class="label">Beginn</div><input class="input rvs" type="time" value="${esc(e.start)}"></div><div><div class="label">Ende</div><input class="input rve" type="time" value="${esc(e.end)}"></div><div class="wide"><div class="label">Ort</div><input class="input rvl" value="${esc(e.location)}"></div><div class="wide"><div class="label">Mitnehmen / erledigen</div><textarea class="rvi">${esc((e.items||[]).join('\n'))}</textarea></div></div></div>`).join('')}$('reviewModal').classList.add('on')}
async function commitReview(){if(!pendingReview)return;if(pendingReview.type==='timetable'){const cid=$('rvChild').value;state.timetable[cid]??={};$('reviewBody').querySelectorAll('.rvtt').forEach(x=>{state.timetable[cid][x.dataset.k]??=['',''];state.timetable[cid][x.dataset.k][+x.dataset.p]=x.value.trim()});await saveCurrentDoc(cid,'timetable',`Stundenplan ${child(cid)?.name}`)}else{const cards=[...$('reviewBody').querySelectorAll('[data-e]')];cards.forEach((card,i)=>{const e=pendingReview.data[i];e.child=card.querySelector('.rvc').value;e.date=card.querySelector('.rvd').value;e.title=card.querySelector('.rvt').value.trim()||'Schulinformation';e.start=card.querySelector('.rvs').value;e.end=card.querySelector('.rve').value;e.location=card.querySelector('.rvl').value.trim();e.items=card.querySelector('.rvi').value.split(/\n+/).map(x=>x.trim()).filter(Boolean);if(e.date)state.events.push(e)});const cid=cards[0]?.querySelector('.rvc').value||state.children[0]?.id;await saveCurrentDoc(cid,'notice',pendingReview.data.map(e=>e.title).join(', '));const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);const ti=isoDate(tomorrow);pendingReview.data.filter(e=>e.date===ti).forEach(e=>{state.tasks[e.child]??=[];(e.items||[]).forEach(x=>{if(!state.tasks[e.child].some(y=>y[0]===x))state.tasks[e.child].push([x,0])})})}$('reviewModal').classList.remove('on');pendingReview=null;save();toast('Dokument & wichtige Daten gespeichert')}
async function saveCurrentDoc(cid,type,summary=''){if(!currentFile)return;let id=uid();try{await putFile(id,currentFile)}catch{}state.documents.unshift({id,child:cid,type,name:currentFile.name,mime:currentFile.type,summary,saved:new Date().toISOString()})}
async function pdfFirstPage(file){const pdfjs=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.8.69/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.8.69/pdf.worker.min.mjs';const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;const page=await pdf.getPage(1),vp=page.getViewport({scale:2}),c=document.createElement('canvas');c.width=vp.width;c.height=vp.height;await page.render({canvasContext:c.getContext('2d'),viewport:vp}).promise;return new Promise(res=>c.toBlob(res,'image/jpeg',.92))}
async function doOCR(){if(!currentFile)return toast('Bitte zuerst ein Dokument auswählen');$('ocrStatus').classList.add('on');$('ocrBar').style.width='4%';$('ocrLabel').textContent='Dokument wird vorbereitet…';try{let src=currentFile;if(currentFile.type==='application/pdf')src=await pdfFirstPage(currentFile);if(!window.Tesseract)throw new Error('OCR library unavailable');const result=await Tesseract.recognize(src,'deu',{logger:m=>{if(m.progress){const p=Math.round(m.progress*100);$('ocrBar').style.width=p+'%';$('ocrLabel').textContent=m.status==='recognizing text'?`Text wird erkannt… ${p}%`:'OCR wird vorbereitet…'}}});$('docText').value=result.data.text.trim();$('ocrBar').style.width='100%';$('ocrLabel').textContent='Texterkennung abgeschlossen';toast('Text erkannt')}catch(e){$('ocrLabel').textContent='OCR nicht abgeschlossen – Text kann manuell eingefügt oder diktiert werden';toast('OCR konnte nicht abgeschlossen werden')}}
function analyseCurrent(){const text=$('docText').value.trim();if(!text)return toast('Bitte zuerst Text erkennen oder eingeben');let type=$('docType').value;if(type==='auto')type=autoType(text);const chosen=$('docChild').value;if(type==='timetable'){const data=parseTimetable(text,chosen);if(!data.child){toast('Kind nicht sicher erkannt – bitte Kind auswählen');return}showReview({type,data})}else{const data=parseNotice(text,chosen);if(data.some(e=>!e.child)){toast('Kind nicht sicher erkannt – bitte Kind auswählen');return}showReview({type:'notice',data})}}
function renderAll(){renderHome();renderWeek();renderFamily();renderDocSelect();renderDocs()}
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(b.dataset.tab).classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('on',x===b));scrollTo(0,0)});
$('todayToggle').onclick=()=>{dayMode='today';renderHome()};$('tomorrowToggle').onclick=()=>{dayMode='tomorrow';renderHome()};$('prevWeek').onclick=()=>{weekOffset--;renderWeek()};$('nextWeek').onclick=()=>{weekOffset++;renderWeek()};$('addChild').onclick=()=>{const n=$('newChild').value.trim();if(!n)return;const id=n.toLowerCase().replace(/[^a-z0-9]/g,'')+Date.now();state.children.push({id,name:n});state.tasks[id]=[];state.timetable[id]={};$('newChild').value='';save();toast(`${n} hinzugefügt`)};
$('docFile').onchange=()=>{currentFile=$('docFile').files[0]||null;$('fileName').textContent=currentFile?`${currentFile.name} · ${(currentFile.size/1024/1024).toFixed(1)} MB`:'Noch keine Datei ausgewählt';$('ocrBtn').disabled=!currentFile;if(currentFile?.type.startsWith('image/')){$('docPreview').src=URL.createObjectURL(currentFile);$('docPreview').hidden=false}else $('docPreview').hidden=true};$('ocrBtn').onclick=doOCR;$('analyseText').onclick=analyseCurrent;$('sampleText').onclick=()=>{$('docText').value='Jayden hat eine Schulreise am 20. August 2026 von 7:00 bis 17:00 Uhr. Treffpunkt: Schulhaus. Bitte 5 Franken mitgeben, Rucksack, Trinkflasche und gute Schuhe.'};$('reviewCancel').onclick=()=>{$('reviewModal').classList.remove('on');pendingReview=null};$('reviewConfirm').onclick=commitReview;$('reviewModal').onclick=e=>{if(e.target===$('reviewModal'))$('reviewModal').classList.remove('on')};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
renderAll();
