function mondayOfOffset(offset){const t=new Date();t.setHours(12,0,0,0);const m=new Date(t);m.setDate(t.getDate()-((t.getDay()+6)%7)+offset*7);return m}
function renderWeek(){filterChips(weekFilter,weekFilterValue,true,v=>{weekFilterValue=v;renderWeek()});const mon=mondayOfOffset(weekOffset),fmt=new Intl.DateTimeFormat('de-CH',{day:'2-digit',month:'2-digit'});const fri=new Date(mon);fri.setDate(mon.getDate()+4);weekRange.textContent=`${fmt.format(mon)} – ${fmt.format(fri)}`;const visible=state.children.filter(c=>weekFilterValue==='all'||c.id===weekFilterValue);weekList.innerHTML=WEEKDAYS.map(([key,label],i)=>{const d=new Date(mon);d.setDate(mon.getDate()+i);const iso=d.toISOString().slice(0,10);let body='';visible.forEach(c=>{const z=state.timetables[c.id]?.[key]||['',''];if(z[0]||z[1])body+=`<div class="schedule"><div class="schedule-time">${z[0]&&z[1]?'Schule':z[0]?'Morgen':'Nachm.'}</div><div><div class="kidline"><span class="kid-tag">👦 ${esc(c.name)}</span><b>${esc(z[0]||'frei')}${z[0]&&z[1]?' · '+esc(z[1]):''}</b></div><small>${z[1]?'Schule auch am Nachmittag':'Nachmittag frei'}</small></div></div>`});
    state.events.filter(e=>e.date===iso&&(weekFilterValue==='all'||e.child===weekFilterValue)).forEach(e=>{body+=`<div class="event"><div class="event-top"><div class="event-icon">${iconFor(e.title)}</div><div class="event-main"><div class="event-title"><div><span class="kid-tag">👦 ${esc(child(e.child)?.name||'Nicht zugeordnet')}</span> <b>${esc(e.title)}</b></div></div><div class="event-meta">${e.start?`🕒 ${esc(e.start)}${e.end?'–'+esc(e.end):''}`:''}${e.location?`${e.start?' · ':''}📍 ${esc(e.location)}`:''}</div>${e.items?.length?`<div class="pills">${e.items.map(x=>`<span class="pill">${iconFor(x)} ${esc(x)}</span>`).join('')}</div>`:''}</div></div></div>`});
    return `<div class="day"><div class="day-title"><span>${label}</span><span>${fmt.format(d)}</span></div>${body||'<div class="empty">Keine Einträge.</div>'}</div>`}).join('')}

function renderDocControls(){docChild.innerHTML='<option value="auto">Automatisch erkennen</option>'+state.children.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');filterChips(docFilter,docFilterValue,true,v=>{docFilterValue=v;renderDocuments()})}
function renderDocuments(){renderDocControls();const docs=state.docs.filter(d=>docFilterValue==='all'||d.child===docFilterValue);docList.innerHTML=docs.length?docs.map(d=>`<div class="doc"><div class="doc-icon">${d.type==='timetable'?'🗓️':'📄'}</div><div class="doc-meta"><b>${esc(d.name)}</b><small>👦 ${esc(child(d.child)?.name||'Nicht zugeordnet')} · ${esc(d.summary||typeLabel(d.type))}${d.extractedCount?` · ${d.extractedCount} Einträge`:''}</small></div><div class="doc-actions"><button class="mini-btn" data-open="${d.id}">Öffnen</button></div></div>`).join(''):'<div class="empty">Noch keine Dokumente gespeichert.</div>';docList.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openStoredFile(b.dataset.open))}
function typeLabel(t){return t==='timetable'?'Stundenplan':t==='notice'?'Schulzettel / Termine':'Dokument'}

function renderFamily(){familyList.innerHTML=state.children.map(c=>{const tt=state.timetables[c.id]||{};return `<div class="family-card" data-family="${c.id}"><div class="family-top"><div class="child-title"><div class="kid-avatar ${esc(c.tone)}">👦</div><div><b>${esc(c.name)}</b><div class="muted">Stundenplan & Dokumente verknüpft</div></div></div><span class="badge">${state.docs.filter(d=>d.child===c.id).length} Dokumente</span></div><div class="timetable"><div class="tt-row"><span></span><span class="tt-head">Vormittag</span><span class="tt-head">Nachmittag</span></div>${WEEKDAYS.map(([k,l])=>{const z=tt[k]||['',''];return `<div class="tt-row"><b>${l.slice(0,2)}</b><input class="input" data-day="${k}" data-part="0" value="${esc(z[0]||'')}" placeholder="frei"><input class="input" data-day="${k}" data-part="1" value="${esc(z[1]||'')}" placeholder="frei"></div>`}).join('')}</div><button class="btn soft save-tt" style="width:100%;margin-top:11px">Stundenplan speichern</button></div>`}).join('');familyList.querySelectorAll('[data-family]').forEach(card=>card.querySelector('.save-tt').onclick=()=>{const id=card.dataset.family;state.timetables[id]=state.timetables[id]||{};card.querySelectorAll('input[data-day]').forEach(inp=>{state.timetables[id][inp.dataset.day]=state.timetables[id][inp.dataset.day]||['',''];state.timetables[id][inp.dataset.day][+inp.dataset.part]=inp.value.trim()});save();toastMsg('Stundenplan gespeichert')})}
function renderAll(){renderToday();renderWeek();renderDocuments();renderFamily()}

function detectChildFromText(text){const n=norm(text);const hits=state.children.filter(c=>n.includes(norm(c.name)));return hits.length===1?hits[0].id:null}
function detectType(text){const n=norm(text);if(/stundenplan|montag|dienstag|mittwoch|donnerstag|freitag/.test(n)&&countTimeTokens(text)>=4)return'timetable';return'notice'}
function countTimeTokens(text){return (String(text).match(/\b(?:[01]?\d|2[0-3])[:.]([0-5]\d)\b/g)||[]).length}
