async function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open('morgenklar-docs-v5',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('files'))r.result.createObjectStore('files')};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function putFile(id,file){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').put(file,id);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function getFile(id){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction('files').objectStore('files').get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function openStoredFile(id){const f=await getFile(id);if(!f)return toastMsg('Originaldatei nicht gefunden');window.open(URL.createObjectURL(f),'_blank')}
async function pdfToImage(file){const pdfjs=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.8.69/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.8.69/pdf.worker.min.mjs';const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;const page=await pdf.getPage(1);const viewport=page.getViewport({scale:2});const canvas=document.createElement('canvas');canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;return await new Promise(r=>canvas.toBlob(r,'image/jpeg',.92))}
async function runOCR(file){docStatus.classList.add('on');docProgress.style.width='5%';docStatusText.textContent='Dokument wird vorbereitet…';let src=file;if(file.type==='application/pdf')src=await pdfToImage(file);if(!window.Tesseract)throw new Error('OCR nicht geladen');const result=await Tesseract.recognize(src,'deu',{logger:m=>{if(m.progress){docProgress.style.width=Math.round(m.progress*100)+'%';docStatusText.textContent=m.status==='recognizing text'?`Text wird erkannt… ${Math.round(m.progress*100)}%`:'OCR wird vorbereitet…'}}});docProgress.style.width='100%';docStatusText.textContent='Texterkennung abgeschlossen';return result.data.text.trim()}
function analyseDocumentText(){const text=docText.value.trim();if(!text)return toastMsg('Bitte zuerst Text erkennen oder eingeben');const forcedChild=docChild.value==='auto'?null:docChild.value;const type=docType.value==='auto'?detectType(text):docType.value;if(type==='timetable')buildReview(parseTimetable(text,forcedChild),'timetable');else buildReview(parseNotice(text,forcedChild),'notice')}
async function persistReviewed(){const data=readReview();if(!data)return;const docId=uid();if(currentFile)await putFile(docId,currentFile);let childId,summary,count=0;if(pendingReview.type==='timetable'){childId=data.child;state.timetables[childId]={...(state.timetables[childId]||{}),...data.timetable};summary='Stundenplan';count=Object.keys(data.timetable).length}else{childId=data[0]?.child||(docChild.value!=='auto'?docChild.value:state.children[0]?.id);data.forEach(e=>{e.sourceDocId=docId;if(e.date)state.events.push(e)});summary=data[0]?.title||'Schulzettel';count=data.filter(e=>e.date).length;const tomorrow=new Date();tomorrow.setHours(12,0,0,0);tomorrow.setDate(tomorrow.getDate()+1);const tiso=tomorrow.toISOString().slice(0,10);data.filter(e=>e.date===tiso).forEach(e=>{state.tasks.tomorrow[e.child]=state.tasks.tomorrow[e.child]||[];(e.items||[]).forEach(item=>{if(!state.tasks.tomorrow[e.child].some(t=>norm(t.label)===norm(item)))state.tasks.tomorrow[e.child].push(task(item,false,`${e.title} · ${formatDate(e.date)}`))})})}
  state.docs.unshift({id:docId,child:childId,type:pendingReview.type==='timetable'?'timetable':'notice',name:currentFile?.name||'Manueller Eintrag',summary,extractedCount:count,text:docText.value.trim().slice(0,12000),savedAt:new Date().toISOString()});save();reviewModal.classList.remove('on');pendingReview=null;toastMsg('Dokument und wichtige Daten gespeichert')}
function formatDate(iso){if(!iso)return'';const [y,m,d]=iso.split('-');return`${d}.${m}.${y}`}
