// interactions
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(b.dataset.tab).classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('on',x===b));window.scrollTo({top:0,behavior:'smooth'})});
todayToggle.onclick=()=>{dayMode='today';renderToday()};tomorrowToggle.onclick=()=>{dayMode='tomorrow';renderToday()};prevWeek.onclick=()=>{weekOffset--;renderWeek()};nextWeek.onclick=()=>{weekOffset++;renderWeek()};
document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>{if(todayFilterValue==='all'){toastMsg('Bitte zuerst ein Kind auswählen');return}state.tasks[dayMode][todayFilterValue]=state.tasks[dayMode][todayFilterValue]||[];state.tasks[dayMode][todayFilterValue].push(task(b.dataset.quick,false,dayMode==='tomorrow'?'für morgen':'für heute'));save();toastMsg(`${b.dataset.quick} hinzugefügt`)});
docFile.onchange=()=>{currentFile=docFile.files[0]||null;docFilename.textContent=currentFile?`${currentFile.name} · ${(currentFile.size/1024/1024).toFixed(1)} MB`:'';processDoc.disabled=!currentFile;docText.value='';docStatus.classList.remove('on')};
processDoc.onclick=async()=>{if(!currentFile)return;processDoc.disabled=true;const old=processDoc.textContent;processDoc.textContent='✨ Wird verarbeitet…';try{docText.value=await runOCR(currentFile);analyseDocumentText()}catch(e){docStatus.classList.add('on');docStatusText.textContent='Texterkennung nicht abgeschlossen. Du kannst den Text manuell einfügen oder diktieren.';toastMsg('OCR konnte nicht abgeschlossen werden')}finally{processDoc.textContent=old;processDoc.disabled=false}};
analyseText.onclick=analyseDocumentText;
sampleText.onclick=()=>{docText.value='Jayden – Schulreise am 20. August 2026 von 07:00 bis 17:00 Uhr. Treffpunkt: Schulhaus. Bitte 5 Franken mitgeben, Rucksack, Trinkflasche und gute Schuhe mitnehmen.';docType.value='notice';docChild.value='auto'};
reviewCancel.onclick=()=>{reviewModal.classList.remove('on');pendingReview=null};reviewConfirm.onclick=persistReviewed;reviewModal.onclick=e=>{if(e.target===reviewModal){reviewModal.classList.remove('on');pendingReview=null}};
addChild.onclick=()=>{const n=newChild.value.trim();if(!n)return;const id=slug(n);state.children.push({id,name:n,tone:['blue','green','orange','purple'][state.children.length%4]});state.tasks.today[id]=[];state.tasks.tomorrow[id]=[];state.timetables[id]={};newChild.value='';save();toastMsg(`${n} hinzugefügt`)};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
renderAll();
