renderWeek=function(){
  filterPeopleChips(weekFilter,weekFilterValue,v=>{weekFilterValue=v;renderWeek()});const mon=mondayOfOffset(weekOffset),fmt=new Intl.DateTimeFormat('de-CH',{day:'2-digit',month:'2-digit'});const fri=new Date(mon);fri.setDate(mon.getDate()+4);weekRange.textContent=`${fmt.format(mon)} – ${fmt.format(fri)}`;
  const visible=state.children.filter(c=>weekFilterValue==='all'||c.id===weekFilterValue);
  weekList.innerHTML=WEEKDAYS.map(([key,label],i)=>{const d=new Date(mon);d.setDate(mon.getDate()+i);const iso=d.toISOString().slice(0,10);let body='';
    visible.forEach(c=>{const z=state.timetables[c.id]?.[key]||['',''];if(z[0]||z[1])body+=`<div class="schedule"><div class="schedule-time">${z[0]&&z[1]?'Schule':z[0]?'Morgen':'Nachm.'}</div><div><div class="kidline"><span class="kid-tag">👦 ${esc(c.name)}</span><b>${esc(z[0]||'frei')}${z[0]&&z[1]?' · '+esc(z[1]):''}</b></div><small>${z[1]?'Schule auch am Nachmittag':'Nachmittag frei'}</small></div></div>`});
    state.events.filter(e=>e.date===iso&&(weekFilterValue==='all'||e.child===weekFilterValue)).forEach(e=>{body+=`<div class="event"><div class="event-top"><div class="event-icon">${iconFor(e.title)}</div><div class="event-main"><div class="event-title"><div><span class="kid-tag">${personIcon(e.child)} ${esc(personName(e.child))}</span> <b>${esc(e.title)}</b></div></div><div class="event-meta">${e.start?`🕒 ${esc(e.start)}${e.end?'–'+esc(e.end):''}`:''}${e.location?`${e.start?' · ':''}📍 ${esc(e.location)}`:''}${e.note?`${e.start||e.location?' · ':''}📝 ${esc(e.note)}`:''}</div>${e.items?.length?`<div class="pills">${e.items.map(x=>`<span class="pill">${iconFor(x)} ${esc(x)}</span>`).join('')}</div>`:''}</div></div></div>`});
    return `<div class="day"><div class="day-title"><span>${label}</span><span>${fmt.format(d)}</span></div>${body||'<div class="empty">Keine Einträge.</div>'}</div>`}).join('');
};

renderDocControls=function(){const keep=docChild.value||'auto';docChild.innerHTML=personOptions(keep,true);filterPeopleChips(docFilter,docFilterValue,v=>{docFilterValue=v;renderDocuments()})};
renderDocuments=function(){renderDocControls();const docs=state.docs.filter(d=>docFilterValue==='all'||d.child===docFilterValue);docList.innerHTML=docs.length?docs.map(d=>`<div class="doc"><div class="doc-icon">${d.type==='timetable'?'🗓️':d.type==='appointment'?'📅':'📄'}</div><div class="doc-meta"><b>${esc(d.name)}</b><small>${personIcon(d.child)} ${esc(personName(d.child))} · ${esc(typeLabel(d.type))}${d.summary?` · ${esc(d.summary)}`:''}${d.extractedCount?` · ${d.extractedCount} Einträge`:''}</small></div><div class="doc-actions"><button class="mini-btn" data-open="${d.id}">Öffnen</button></div></div>`).join(''):'<div class="empty">Noch keine Dokumente gespeichert.</div>';docList.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openStoredFile(b.dataset.open))};
typeLabel=function(t){return t==='timetable'?'Stundenplan':t==='notice'?'Schulzettel / Termine':t==='appointment'?'Eigener Termin':'Dokument'};

inferTitle=function(segment){const n=norm(segment);const map=[['schulreise','Schulreise'],['ausflug','Ausflug'],['waldmorgen','Waldmorgen'],['sporttag','Sporttag'],['elternabend','Elternabend'],['fototermin','Fototermin'],['schulfoto','Fototermin'],['zahnarzt','Zahnarzt'],['arzt','Arzttermin'],['therapie','Therapietermin'],['physio','Physiotherapie'],['spital','Spitaltermin'],['gemeinde','Termin Gemeinde'],['beratung','Beratungstermin'],['bibliothek','Bibliothek'],['schwimmen','Schwimmen'],['ferien','Ferien / schulfrei'],['projekttag','Projekttag']];for(const [k,v] of map)if(n.includes(k))return v;const line=segment.split(/\n/).map(s=>s.trim()).find(s=>s.length>3&&s.length<70&&!/\d{1,2}[.\/-]\d{1,2}/.test(s));return line?.slice(0,60)||'Termin'};
extractTimes=function(segment){const s=segment.replace(/\b\d{1,2}[.\/-]\d{1,2}(?:[.\/-]\d{2,4})?\b/g,' ');let m=s.match(/(?:von\s*)?(\d{1,2})(?::|\.)(\d{2})\s*(?:uhr)?\s*(?:bis|[-–])\s*(\d{1,2})(?::|\.)(\d{2})/i);if(!m)m=s.match(/(?:von\s*)?(\d{1,2})\s*(?:uhr)?\s*(?:bis|[-–])\s*(\d{1,2})\s*(?:uhr)?/i);if(m){if(m.length>=5)return{start:`${String(+m[1]).padStart(2,'0')}:${m[2]}`,end:`${String(+m[3]).padStart(2,'0')}:${m[4]}`};return{start:`${String(+m[1]).padStart(2,'0')}:00`,end:`${String(+m[2]).padStart(2,'0')}:00`}}const one=s.match(/(?:um|termin\s*(?:um)?|beginn\s*:?)[\s]*(\d{1,2})(?::|\.)(\d{2})\s*(?:uhr)?/i)||s.match(/\b([01]?\d|2[0-3])(?::|\.)([0-5]\d)\s*(?:uhr)\b/i);return one?{start:`${String(+one[1]).padStart(2,'0')}:${one[2]}`,end:''}:{start:'',end:''}};
extractLocation=function(segment){const m=segment.match(/(?:Treffpunkt|Ort|Besammlung|Treffen|Start|Adresse|Praxis)\s*:?\s*([^\n.;]{3,90})/i);return m?m[1].trim():''};
parseNotice=function(text,forcedChild){const dates=extractDateTokens(text),detected=forcedChild||detectChildFromText(text)||state.children[0]?.id;const segments=[];if(dates.length){dates.forEach((d,i)=>{const start=Math.max(0,d.index-120),end=Math.min(text.length,(dates[i+1]?.index??text.length)+220);segments.push({date:d.date,text:text.slice(start,end)})})}else segments.push({date:'',text});return segments.slice(0,12).map((seg,i)=>{const times=extractTimes(seg.text);return{id:uid(),child:detected,title:inferTitle(seg.text),date:seg.date,start:times.start,end:times.end,location:extractLocation(seg.text),items:extractItems(seg.text),note:'',sourceDocId:null,_index:i}})};
