buildReview=function(result,type){pendingReview={type,result};if(type==='timetable'){reviewBody.innerHTML=`<div class="review-card"><div class="label">Kind</div><select data-tt-child>${state.children.map(x=>`<option value="${x.id}" ${x.id===result.child?'selected':''}>${esc(x.name)}</option>`).join('')}</select><div class="timetable"><div class="tt-row"><span></span><span class="tt-head">Vormittag</span><span class="tt-head">Nachmittag</span></div>${WEEKDAYS.map(([k,l])=>{const z=result.timetable[k]||['',''];return `<div class="tt-row"><b>${l.slice(0,2)}</b><input class="input" data-rday="${k}" data-rpart="0" value="${esc(z[0])}" placeholder="frei"><input class="input" data-rday="${k}" data-rpart="1" value="${esc(z[1])}" placeholder="frei"></div>`}).join('')}</div></div>`}else{reviewBody.innerHTML=result.map((e,i)=>`<div class="review-card" data-event-index="${i}"><div class="review-grid"><div><div class="label">Person / Kind</div><select data-field="child">${personOptions(e.child,false)}</select></div><div><div class="label">Datum</div><input class="input" data-field="date" type="date" value="${esc(e.date)}"></div><div class="wide"><div class="label">Termin / Ereignis</div><input class="input" data-field="title" value="${esc(e.title)}"></div><div><div class="label">Von</div><input class="input" data-field="start" type="time" value="${esc(e.start)}"></div><div><div class="label">Bis</div><input class="input" data-field="end" type="time" value="${esc(e.end)}"></div><div class="wide"><div class="label">Ort / Treffpunkt</div><input class="input" data-field="location" value="${esc(e.location)}"></div><div class="wide"><div class="label">Notiz</div><input class="input" data-field="note" value="${esc(e.note||'')}" placeholder="z. B. 10 Minuten vorher dort sein"></div><div class="wide"><div class="label">Mitnehmen (durch Komma trennen)</div><input class="input" data-field="items" value="${esc((e.items||[]).join(', '))}"></div></div></div>`).join('')||'<div class="empty">Keine Termine sicher erkannt. Du kannst abbrechen und den Text korrigieren.</div>'}reviewModal.classList.add('on')};
readReview=function(){if(!pendingReview)return null;if(pendingReview.type==='timetable'){const card=reviewBody.querySelector('.review-card');const out={};card.querySelectorAll('[data-rday]').forEach(inp=>{out[inp.dataset.rday]=out[inp.dataset.rday]||['',''];out[inp.dataset.rday][+inp.dataset.rpart]=inp.value.trim()});return{kind:'timetable',child:card.querySelector('[data-tt-child]').value,timetable:out}}return [...reviewBody.querySelectorAll('[data-event-index]')].map(card=>{const f=k=>card.querySelector(`[data-field="${k}"]`).value.trim();return{id:uid(),child:f('child'),title:f('title')||'Termin',date:f('date'),start:f('start'),end:f('end'),location:f('location'),note:f('note'),items:f('items').split(',').map(x=>x.trim()).filter(Boolean),sourceDocId:null}})};
analyseDocumentText=function(){const text=docText.value.trim();if(!text)return toastMsg('Bitte zuerst Text erkennen oder eingeben');const type=docType.value==='auto'?detectType(text):docType.value;const forcedChild=type==='appointment'?SELF_ID:(docChild.value==='auto'?null:docChild.value);if(type==='timetable')buildReview(parseTimetable(text,forcedChild),'timetable');else buildReview(parseNotice(text,forcedChild),type==='appointment'?'appointment':'notice')};
persistReviewed=async function(){const data=readReview();if(!data)return;const docId=uid();if(currentFile)await putFile(docId,currentFile);let childId,summary,count=0;if(pendingReview.type==='timetable'){childId=data.child;state.timetables[childId]={...(state.timetables[childId]||{}),...data.timetable};summary='Stundenplan';count=Object.keys(data.timetable).length}else{childId=data[0]?.child||(docChild.value!=='auto'?docChild.value:state.children[0]?.id);data.forEach(e=>{e.sourceDocId=docId;if(e.date)state.events.push(e)});summary=data[0]?.title||(pendingReview.type==='appointment'?'Eigener Termin':'Schulzettel');count=data.filter(e=>e.date).length;const tomorrow=new Date();tomorrow.setHours(12,0,0,0);tomorrow.setDate(tomorrow.getDate()+1);const tiso=tomorrow.toISOString().slice(0,10);data.filter(e=>e.date===tiso&&e.child!==SELF_ID).forEach(e=>{state.tasks.tomorrow[e.child]=state.tasks.tomorrow[e.child]||[];(e.items||[]).forEach(item=>{if(!state.tasks.tomorrow[e.child].some(t=>norm(t.label)===norm(item)))state.tasks.tomorrow[e.child].push(task(item,false,`${e.title} · ${formatDate(e.date)}`))})})}state.docs.unshift({id:docId,child:childId,type:pendingReview.type,name:currentFile?.name||'Manueller Eintrag',summary,extractedCount:count,text:docText.value.trim().slice(0,12000),savedAt:new Date().toISOString()});save();reviewModal.classList.remove('on');pendingReview=null;toastMsg('Dokument und wichtige Daten gespeichert')};

// Neue Interaktionen nach den V5-Handlern setzen
const openCustomTaskBtn=document.getElementById('openCustomTask');
const customTaskModalEl=document.getElementById('customTaskModal');
const appointmentFileEl=document.getElementById('appointmentFile');
openCustomTaskBtn.onclick=()=>openTaskEditor();
document.getElementById('customTaskCancel').onclick=()=>{customTaskModalEl.classList.remove('on');editingTaskRef=null};
document.getElementById('customTaskSave').onclick=persistCustomTask;
customTaskModalEl.onclick=e=>{if(e.target===customTaskModalEl){customTaskModalEl.classList.remove('on');editingTaskRef=null}};
document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>{if(todayFilterValue==='all'){toastMsg('Bitte zuerst ein Kind auswählen');return}state.tasks[dayMode][todayFilterValue]=state.tasks[dayMode][todayFilterValue]||[];state.tasks[dayMode][todayFilterValue].push(task(b.dataset.quick,false,dayMode==='tomorrow'?'für morgen':'für heute'));save();toastMsg(`${b.dataset.quick} hinzugefügt`)});
appointmentFileEl.onchange=()=>{currentFile=appointmentFileEl.files[0]||null;if(!currentFile)return;docChild.value=SELF_ID;docType.value='appointment';docFilename.textContent=`📸 ${currentFile.name}`;docText.value='';docStatus.classList.remove('on');processDoc.disabled=false;processDoc.click()};
analyseText.onclick=analyseDocumentText;
reviewConfirm.onclick=persistReviewed;

renderAll();
