(()=>{
const NS='http://www.w3.org/2000/svg';
const W=1280,H=720,G=520,TOP=78,FLOOR=690,START={x:230,y:542},ANCHOR={x:154,y:548};
const $=id=>document.getElementById(id);const world=$('world'),player=$('player'),rope=$('rope'),traj=$('trajectory'),aimArrow=$('aimArrow'),lootLayer=$('lootLayer'),bumperLayer=$('bumperLayer'),glassLayer=$('glassLayer'),laserLayer=$('laserLayer'),particleLayer=$('particles');
const ui={job:$('jobLabel'),goal:$('goalLabel'),loot:$('lootStat'),shots:$('shotStat'),hint:$('hint'),toast:$('toast'),intro:$('intro'),result:$('result'),stars:$('stars'),rshots:$('resultShots'),rloot:$('resultLoot'),next:$('next'),play:$('play'),restart:$('restart'),rotate:$('rotate'),rtitle:$('resultTitle')};
const levels=[
 {name:'MUSEUM',required:3,par:4,loot:[[500,470],[790,255],[1050,455]],bumpers:[],glass:[],lasers:[]},
 {name:'JUWELENBÖRSE',required:4,par:6,loot:[[465,190],[655,455],[895,185],[1080,455]],bumpers:[[705,410,48]],glass:[[565,120,18,275],[875,305,18,250]],lasers:[]},
 {name:'LASER-VAULT',required:5,par:8,loot:[[440,175],[615,430],[780,150],[970,435],[1100,235]],bumpers:[[720,350,46],[1030,390,45]],glass:[[535,105,18,260],[885,260,18,285]],lasers:[[580,265,810,265,1.1],[915,180,1120,180,1.35]]}
];
let state=null,levelIndex=0,last=performance.now(),dragging=false,dragStart=null,pointer=null,toastTimer=0,flightStart=0,returnStart=null,returnFrom=null,returnTimer=0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function svgEl(tag,attrs={}){const e=document.createElementNS(NS,tag);for(const [k,v] of Object.entries(attrs))e.setAttribute(k,v);return e}
function toWorld(e){const r=world.getBoundingClientRect();const scale=Math.min(r.width/W,r.height/H);const ox=(r.width-W*scale)/2,oy=(r.height-H*scale)/2;return{x:(e.clientX-r.left-ox)/scale,y:(e.clientY-r.top-oy)/scale}}
function createState(i){const L=levels[i];return{L,x:START.x,y:START.y,vx:0,vy:0,shots:0,got:0,ready:true,flying:false,returning:false,ended:false,flightT:0,loot:L.loot.map((p,n)=>({x:p[0],y:p[1],taken:false,n})),bumpers:L.bumpers.map(b=>({x:b[0],y:b[1],r:b[2]})),glass:L.glass.map(g=>({x:g[0],y:g[1],w:g[2],h:g[3],broken:false})),lasers:L.lasers.map(l=>({x1:l[0],y1:l[1],x2:l[2],y2:l[3],speed:l[4],cool:0}))}}
function reset(i=levelIndex){levelIndex=(i+levels.length)%levels.length;state=createState(levelIndex);dragging=false;dragStart=pointer=null;returnStart=returnFrom=null;returnTimer=0;ui.result.classList.add('hidden');renderLevel();updateHud();setPlayer(START.x,START.y);traj.setAttribute('opacity','0');aimArrow.setAttribute('opacity','0');ui.hint.innerHTML='<strong>Finger auf den Banditen</strong> → in Flugrichtung wischen → loslassen'}
function updateHud(){ui.job.textContent=`JOB ${levelIndex+1} · ${state.L.name}`;ui.goal.textContent=state.got>=state.L.required?'Beute gesichert · Rückkehr läuft':'Sammle alle Edelsteine';ui.loot.textContent=`${state.got} / ${state.L.required}`;ui.shots.textContent=state.shots}
function renderLevel(){lootLayer.innerHTML='';bumperLayer.innerHTML='';glassLayer.innerHTML='';laserLayer.innerHTML='';
 state.loot.forEach(l=>{const g=svgEl('g',{class:'loot',transform:`translate(${l.x} ${l.y})`,'data-n':l.n,filter:'url(#gemGlow)'});g.innerHTML='<path d="M0 -28 L24 -7 L13 26 L-13 26 L-24 -7 Z" fill="url(#gemGrad)" stroke="#fff1a2" stroke-width="2"/><path d="M0 -28 L0 26 M-24 -7 H24 M-13 26 L0 -7 L13 26" stroke="#fff7c9" stroke-width="1.5" opacity=".55"/>';lootLayer.appendChild(g)});
 state.bumpers.forEach((b,n)=>{const g=svgEl('g',{transform:`translate(${b.x} ${b.y})`,'data-b':n});g.innerHTML=`<circle r="${b.r+6}" fill="#0d1625" stroke="#30435b" stroke-width="5"/><circle r="${b.r}" fill="url(#bumperGrad)" stroke="#8f550e" stroke-width="5"/><path d="M-12 8 L4 -10 L4 1 L16 1 L0 18 L0 8Z" fill="#6b3b05" opacity=".9"/>`;bumperLayer.appendChild(g)});
 state.glass.forEach((g,n)=>{const el=svgEl('g',{'data-g':n});el.innerHTML=`<rect x="${g.x}" y="${g.y}" width="${g.w}" height="${g.h}" rx="6" fill="#b8efff" fill-opacity=".10" stroke="#bdefff" stroke-opacity=".78" stroke-width="2"/><path d="M${g.x+4} ${g.y+20} l${g.w-8} 35 M${g.x+4} ${g.y+90} l${g.w-8} 30" stroke="#eaffff" stroke-opacity=".25"/>`;glassLayer.appendChild(el)});
 state.lasers.forEach((l,n)=>{const line=svgEl('line',{x1:l.x1,y1:l.y1,x2:l.x2,y2:l.y2,stroke:'#ff5a6d','stroke-width':4,'stroke-linecap':'round',filter:'url(#cyanGlow)','data-l':n});laserLayer.appendChild(line)});
}
function calcLaunchVector(delta){const raw=Math.hypot(delta.x,delta.y);if(raw<18)return null;const used=Math.min(330,raw);const t=clamp((used-18)/(330-18),0,1);const speed=430+860*Math.pow(t,.72);return{vx:delta.x/raw*speed,vy:delta.y/raw*speed,speed,t}}
function circleRect(x,y,r,g){const cx=clamp(x,g.x,g.x+g.w),cy=clamp(y,g.y,g.y+g.h);const dx=x-cx,dy=y-cy,d2=dx*dx+dy*dy;if(d2>=r*r)return null;const d=Math.sqrt(d2)||.001;return{nx:dx/d,ny:dy/d,pen:r-d}}
function pointSegDist(px,py,x1,y1,x2,y2){const vx=x2-x1,vy=y2-y1,l2=vx*vx+vy*vy||1;const t=clamp(((px-x1)*vx+(py-y1)*vy)/l2,0,1);return Math.hypot(px-(x1+t*vx),py-(y1+t*vy))}
function physicsStep(p,dt,sim=false){p.vy+=G*dt;p.vx*=Math.pow(.997,dt*60);p.vy*=Math.pow(.998,dt*60);p.x+=p.vx*dt;p.y+=p.vy*dt;const r=27;
 if(p.x<r){p.x=r;p.vx=Math.abs(p.vx)*.78} if(p.x>W-r){p.x=W-r;p.vx=-Math.abs(p.vx)*.78} if(p.y<TOP+r){p.y=TOP+r;p.vy=Math.abs(p.vy)*.74} if(p.y>FLOOR-r){p.y=FLOOR-r;p.vy=-Math.abs(p.vy)*.70}
 for(const b of state.bumpers){const dx=p.x-b.x,dy=p.y-b.y,d=Math.hypot(dx,dy),rr=r+b.r;if(d<rr){const nx=dx/(d||1),ny=dy/(d||1),pen=rr-d;p.x+=nx*pen;p.y+=ny*pen;const vn=p.vx*nx+p.vy*ny;if(vn<0){p.vx-=1.92*vn*nx;p.vy-=1.92*vn*ny;if(!sim)burst(p.x,p.y,'#ffd15a',11)}}}
 for(const g of state.glass){if(g.broken)continue;const c=circleRect(p.x,p.y,r,g);if(c){const speed=Math.hypot(p.vx,p.vy);if(speed>420){if(!sim){g.broken=true;syncGlass();burst(p.x,p.y,'#baf2ff',28);toast('GLAS GEBROCHEN')} }else{p.x+=c.nx*c.pen;p.y+=c.ny*c.pen;const vn=p.vx*c.nx+p.vy*c.ny;if(vn<0){p.vx-=1.55*vn*c.nx;p.vy-=1.55*vn*c.ny}}}}
 return p}
function predict(v){let p={x:state.x,y:state.y,vx:v.vx,vy:v.vy};const pts=[[p.x,p.y]];for(let i=0;i<34;i++){const before={x:p.x,y:p.y};physicsStep(p,.035,true);pts.push([p.x,p.y]);const hitOuter=(p.x<=28||p.x>=W-28||p.y<=TOP+28||p.y>=FLOOR-28);if(hitOuter||i>24&&Math.hypot(p.vx,p.vy)<85)break}return pts}
function setPlayer(x,y){state.x=x;state.y=y;player.setAttribute('transform',`translate(${x} ${y})`);const mx=(ANCHOR.x+x)/2,my=(ANCHOR.y+y)/2+Math.min(70,Math.abs(x-ANCHOR.x)*.08);rope.setAttribute('d',`M${ANCHOR.x} ${ANCHOR.y} Q${mx} ${my} ${x} ${y}`)}
function aim(){if(!dragging||!dragStart||!pointer)return;const delta={x:pointer.x-dragStart.x,y:pointer.y-dragStart.y};const v=calcLaunchVector(delta);if(!v){traj.setAttribute('opacity','0');aimArrow.setAttribute('opacity','0');return}const pts=predict(v);traj.setAttribute('d','M'+pts.map(p=>p[0].toFixed(1)+' '+p[1].toFixed(1)).join(' L'));traj.setAttribute('opacity','1');const ang=Math.atan2(delta.y,delta.x)*180/Math.PI;aimArrow.setAttribute('transform',`translate(${state.x} ${state.y}) rotate(${ang}) scale(${.72+v.t*.55})`);aimArrow.setAttribute('opacity','1');ui.hint.innerHTML=`<strong>${Math.round(v.t*100)}% Kraft</strong> · gepunktete Linie = echte Flugbahn`}
function launch(){if(!dragging)return;const delta={x:pointer.x-dragStart.x,y:pointer.y-dragStart.y};const v=calcLaunchVector(delta);dragging=false;traj.setAttribute('opacity','0');aimArrow.setAttribute('opacity','0');if(!v){ui.hint.innerHTML='<strong>Etwas weiter wischen</strong> → dann loslassen';return}state.vx=v.vx;state.vy=v.vy;state.flying=true;state.ready=false;state.flightT=0;state.shots++;flightStart=performance.now();updateHud();ui.hint.textContent='Flug läuft…';burst(state.x,state.y,'#4fe3ff',12)}
function startReturn(delay=0){if(state.returning||state.ended)return;state.flying=false;state.returning=true;returnFrom={x:state.x,y:state.y};returnStart=performance.now()+delay;returnTimer=0;ui.hint.textContent=state.got>=state.L.required?'Beute gesichert · zurück zum Van':'Seil zieht dich zurück…'}
function finishReturn(){state.returning=false;state.ready=true;setPlayer(START.x,START.y);if(state.got>=state.L.required)complete();else ui.hint.innerHTML='<strong>Nächster Schuss</strong> · Finger auf den Banditen → zum Ziel wischen'}
function complete(){if(state.ended)return;state.ended=true;const delta=state.shots-state.L.par;const stars=delta<=0?3:delta<=2?2:1;ui.stars.textContent='★'.repeat(stars)+'☆'.repeat(3-stars);ui.rshots.textContent=state.shots;ui.rloot.textContent=`${state.got}/${state.L.required}`;ui.rtitle.textContent=stars===3?'PERFEKTER JOB!':stars===2?'SAUBER!':'GESCHAFFT!';ui.next.textContent=levelIndex<levels.length-1?'NÄCHSTER JOB':'NOCH EINE RUNDE';setTimeout(()=>ui.result.classList.remove('hidden'),260);burst(START.x,START.y,'#42e59b',45)}
function syncGlass(){[...glassLayer.children].forEach((el,i)=>{if(state.glass[i]?.broken){el.setAttribute('opacity','.12');el.setAttribute('transform','rotate(7)');}})}
function checkLoot(){for(const l of state.loot){if(l.taken)continue;if(Math.hypot(state.x-l.x,state.y-l.y)<55){l.taken=true;state.got++;const el=lootLayer.querySelector(`[data-n="${l.n}"]`);if(el){el.style.transition='transform .17s, opacity .17s';el.style.opacity='0';el.setAttribute('transform',`translate(${l.x} ${l.y}) scale(1.7)`)}burst(l.x,l.y,'#ffd04f',32);toast(state.got>=state.L.required?'ALLE EDELSTEINE!':'BEUTE +1');updateHud();if(state.got>=state.L.required)setTimeout(()=>startReturn(),160)}}}
function checkLasers(dt){state.lasers.forEach((l,n)=>{l.cool=Math.max(0,l.cool-dt);const on=Math.sin(performance.now()/1000*l.speed*Math.PI*2)>-.15;const el=laserLayer.querySelector(`[data-l="${n}"]`);if(el){el.setAttribute('opacity',on?'1':'.14');el.setAttribute('stroke-width',on?'5':'2')}if(on&&l.cool<=0&&pointSegDist(state.x,state.y,l.x1,l.y1,l.x2,l.y2)<33){l.cool=.85;state.vx*=-.55;state.vy=-Math.abs(state.vy)-130;burst(state.x,state.y,'#ff5a6d',24);toast('LASER!')}})}
function toast(msg){ui.toast.textContent=msg;ui.toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>ui.toast.classList.remove('show'),600)}
function burst(x,y,color,count=18){for(let i=0;i<count;i++){const c=svgEl('circle',{cx:x,cy:y,r:2+Math.random()*4,fill:color,opacity:'1'});particleLayer.appendChild(c);const a=Math.random()*Math.PI*2,s=60+Math.random()*260,vx=Math.cos(a)*s,vy=Math.sin(a)*s,life=420+Math.random()*300,start=performance.now();const tick=now=>{const t=(now-start)/life;if(t>=1){c.remove();return}c.setAttribute('cx',x+vx*t*.55);c.setAttribute('cy',y+vy*t*.55+120*t*t);c.setAttribute('opacity',String(1-t));requestAnimationFrame(tick)};requestAnimationFrame(tick)}}
function frame(now){const dt=Math.min(.028,(now-last)/1000||.016);last=now;if(state&&!state.ended){if(state.flying){state.flightT+=dt;physicsStep(state,dt,false);setPlayer(state.x,state.y);checkLoot();checkLasers(dt);const ropeLen=Math.hypot(state.x-ANCHOR.x,state.y-ANCHOR.y);const speed=Math.hypot(state.vx,state.vy);if(!state.returning&&(ropeLen>1110||state.flightT>2.45||(state.flightT>.75&&speed<78)))startReturn()}
 if(state.returning&&returnStart!==null&&now>=returnStart){returnTimer+=dt;const t=clamp(returnTimer/.52,0,1),e=1-Math.pow(1-t,3);setPlayer(returnFrom.x+(START.x-returnFrom.x)*e,returnFrom.y+(START.y-returnFrom.y)*e);if(t>=1)finishReturn()}}
requestAnimationFrame(frame)}
world.addEventListener('pointerdown',e=>{if(!state||state.ended||!state.ready||!ui.intro.classList.contains('hidden'))return;const p=toWorld(e);if(dist(p,{x:state.x,y:state.y})<160){dragging=true;dragStart=p;pointer=p;world.setPointerCapture?.(e.pointerId);ui.hint.innerHTML='<strong>Zieh direkt zum Ziel</strong> · die Flugbahn erscheint'}});
world.addEventListener('pointermove',e=>{if(dragging){pointer=toWorld(e);aim()}});world.addEventListener('pointerup',()=>launch());world.addEventListener('pointercancel',()=>{dragging=false;traj.setAttribute('opacity','0');aimArrow.setAttribute('opacity','0')});
ui.play.onclick=()=>{ui.intro.classList.add('hidden');reset(0)};ui.restart.onclick=()=>reset(levelIndex);ui.next.onclick=()=>{ui.result.classList.add('hidden');reset(levelIndex<levels.length-1?levelIndex+1:0)};
function resize(){ui.rotate.classList.toggle('hidden',innerWidth>=innerHeight)}addEventListener('resize',resize);resize();reset(0);requestAnimationFrame(frame);
window.__BBV4__={state:()=>JSON.parse(JSON.stringify(state)),calcLaunchVector,predict,reset};
})();