function update(dt){
 if(!running||finished||paused){fx(dt);return}if(deadT>0){deadT=Math.max(0,deadT-dt);fx(dt*.45);if(deadT===0)respawn(respawnLabel||'CRASH!');return}if(hitStop>0){hitStop=Math.max(0,hitStop-dt);fx(dt*.35);return}
 worldTime+=dt;beatTick();failLock=Math.max(0,failLock-dt);overclockT=Math.max(0,overclockT-dt);speedBoostT=Math.max(0,speedBoostT-dt);jumpBuffer=Math.max(0,jumpBuffer-dt);coyote=Math.max(0,coyote-dt);player.r=lerp(player.r,player.targetR,1-Math.pow(.0007,dt));
 const fever=combo>=5,oc=overclockT>0,baseSpeed=activeRun.speed||400;player.vx=baseSpeed*(oc?1.07:1)*(speedBoostT>0?1.11:1);
 const gravity=player.heavy?3500:1550;player.vy+=gravity*dt;player.vy*=Math.pow(player.heavy?.9975:.9966,dt*60);player.x+=player.vx*dt;player.y+=player.vy*dt;player.rot+=player.vx*dt/player.r*.019;
 const activePit=objects.find(o=>o.type==='pit'&&player.x>o.x&&player.x<o.x+o.w),fragile=objects.find(o=>o.type==='fragile'&&player.x>o.x&&player.x<o.x+o.w);if(activePit&&player.y>H+54){hardCrash('ABGRUND!');fx(dt);return}let floorY=FLOOR;if(activePit)floorY=H+240;
 player.grounded=false;if(player.y+player.r>floorY){player.y=floorY-player.r;if(player.vy>0){landingPulse=Math.max(landingPulse,Math.min(1,player.vy/880));if(player.heavy&&player.vy>560){spark(player.x,player.y+player.r,20);emit(player.x,player.y+player.r,'#ffd45c',16,190,260);shock(player.x,player.y+player.r,'#ffd45c');shake=Math.max(shake,7)}player.vy=0}player.grounded=true;coyote=.12;airRecoverUsed=false;if(jumpBuffer>0&&!player.heavy)jumpNow(-1025)}if(player.y-player.r<88){player.y=88+player.r;if(player.vy<0)player.vy=40;hardCrash('DECKE!')}
 for(const o of objects){
  if(o.type==='glass'&&!o.done){const c=rectCircle(o);if(c){if(player.heavy){o.done=true;shake=13;spark(o.x,o.y+o.h*.55,28);emit(o.x,o.y+o.h*.5,'#ffd45c',34,380);shock(o.x,o.y+o.h*.55,'#ffd45c');reward('CRUSH',o.score)}else{player.x-=Math.max(2,c.pen+2);player.vx*=.18;fail('HALTEN!')}}}
  else if(o.type==='ceiling'){const c=rectCircle(o);if(c){player.x-=Math.max(1,c.pen*.7);player.vy=Math.max(player.vy,110);if(!player.heavy)fail('ZU GROSS!')}}
  else if(o.type==='pad'&&!o.done){if(player.x>o.x-player.r&&player.x<o.x+o.w+player.r&&player.y+player.r>o.y&&player.y<o.y+38&&player.vy>0){player.y=o.y-player.r;player.vy=player.heavy?-460:-980;o.done=true;shake=7;emit(player.x,o.y,'#ffd45c',20,270);shock(player.x,o.y,'#ffd45c');if(!player.heavy)reward('BOOST',o.score);else fail('LOSLASSEN!')}}
  else if(o.type==='fragile'&&!o.done){if(player.x>o.x&&player.x<o.x+o.w&&player.y+player.r>o.y&&player.y<o.y+45&&player.vy>0){if(player.heavy){o.done=true;player.vy+=350;shake=14;spark(player.x,o.y,30);emit(player.x,o.y,'#ffd45c',28,320);shock(player.x,o.y,'#ffd45c');reward('BREAK',o.score)}else{player.y=o.y-player.r;player.vy*=-.48}}}
  else if(o.type==='fan'){if(player.x>o.x&&player.x<o.x+o.w&&player.y>o.y&&player.y<o.y+o.h&&!player.heavy){player.vy-=1340*dt;if(Math.random()<.2)particles.push({x:o.x+Math.random()*o.w,y:o.y+o.h,vx:(Math.random()-.5)*35,vy:-230-Math.random()*190,life:.65,size:2,color:'#8cf8ff',gravity:0});if(!o.done&&player.x>o.x+o.w*.45&&player.y<o.y+95){o.done=true;reward('LIFT',o.score)}}}
  else if(o.type==='lightgate'){const c=rectCircle(o);if(c&&player.heavy){player.x-=Math.max(3,c.pen+3);player.vx*=.4;fail('LOSLASSEN!')}else if(!o.done&&!player.heavy&&player.x>o.x+o.w*.55&&player.y>o.y-10&&player.y<o.y+o.h+10){o.done=true;ring(o.x+o.w*.5,player.y,'#8cf8ff');emit(o.x+o.w*.5,player.y,'#8cf8ff',16,180,80);reward('PHASE',o.score,true)}}
  else if(o.type==='bumper'&&!o.done){const dx=player.x-o.x,dy=player.y-o.y,limit=player.r+o.r;if(dx*dx+dy*dy<limit*limit&&player.vy>-280){const d=Math.max(.001,Math.hypot(dx,dy)),nx=dx/d,ny=dy/d;player.x=o.x+nx*(limit+2);player.y=o.y+ny*(limit+2);player.vy=player.heavy?-480:-1010;player.vx+=player.heavy?0:24;shake=Math.max(shake,player.heavy?5:8);ring(o.x,o.y,player.heavy?'#ff9aa9':'#8cf8ff');emit(o.x,o.y,player.heavy?'#ff9aa9':'#8cf8ff',player.heavy?12:20,player.heavy?160:240);o.done=true;if(player.heavy)fail('ZU SCHWER!');else reward('BOUNCE',o.score,true)}}
  else if(o.type==='spikes'){if(player.x+player.r>o.x&&player.x-player.r<o.x+o.w&&player.y+player.r>o.y+2){hardCrash('SPIKES!')}else if(!o.done&&player.x>o.x+o.w+20){o.done=true;reward('CLEAR',o.score||140,true)}}
  else if(o.type==='saw'){const dx=player.x-o.x,dy=player.y-o.y,lim=player.r+o.r*.76;if(dx*dx+dy*dy<lim*lim){hardCrash('SAW!')}else if(!o.done&&player.x>o.x+o.r+50){o.done=true;reward('DODGE',o.score||180,true)}}
  else if(o.type==='speedgate'&&!o.done){if(player.x>o.x&&player.x<o.x+o.w+player.r){o.done=true;speedBoostT=2.15;chargeFlow(10);ring(o.x+o.w/2,player.y,'#72efad',.42);emit(o.x+o.w/2,player.y,'#72efad',22,260,60);reward('BOOST',o.score||120,true)}}
  else if(o.type==='slam'&&!o.done){if(player.x+player.r>o.x&&player.x-player.r<o.x+o.w&&player.y+player.r>=o.y-4){if(player.heavy&&player.vy>520){o.done=true;speedBoostT=1.35;player.vy=0;shake=10;spark(player.x,o.y,24);shock(player.x,o.y,'#ffd45c');reward('SLAM',o.score||200,true)}else if(!player.heavy&&player.x>o.x+o.w){o.done=true}}}
  else if(o.type==='checkpoint'&&!o.done&&player.x>o.x){o.done=true;checkpointX=Math.max(START_X,o.x-100);points+=100;chargeFlow(12);checkpointState={x:checkpointX,time:worldTime,points,perfects,fluxCount,flowMeter,overclockCount,bestCombo,objects:objects.map(q=>!!q.done),flux:flux.map(f=>!!f.taken)};toast('FLOW ANCHOR +100');tone(660,.09,'triangle',.035);ring(o.x,o.y,'#72efad');updateHud()}
  else if(o.type==='crusher'){const cyc=(Math.sin(worldTime*2.4+o.phase)+1)/2,bottom=125+cyc*255,hazard={x:o.x,y:88,w:o.w,h:bottom-88},c=rectCircle(hazard);if(c){hardCrash('CRUSHER!')}else if(!o.done&&player.x>o.x+o.w+60){o.done=true;reward('DODGE',o.score||190,true)}}
 }
 for(const f of flux){if(!f.taken&&Math.hypot(player.x-f.x,player.y-f.y)<player.r+20){f.taken=true;fluxCount++;fluxChain=(worldTime-lastFluxAt<1.25)?fluxChain+1:1;lastFluxAt=worldTime;const bonus=75+combo*5+Math.min(90,fluxChain*12)*(overclockT>0?2:1);points+=bonus;chargeFlow(5);emit(f.x,f.y,'#bba7ff',18,180,100);ring(f.x,f.y,'#bba7ff');tone(900,.045,'sine',.03);if(fluxChain>=3)toast(`FLUX CHAIN ×${fluxChain} +${bonus}`);updateHud()}}
 for(const pit of objects.filter(o=>o.type==='pit'))if(!pit.done&&player.x>pit.x+45&&player.x<pit.x+pit.w-25&&!player.heavy&&player.y<575){pit.done=true;reward('FLOAT',pit.score)}
 if(player.y>H+72)hardCrash('ABGRUND!');if(player.x>=END_X)finish();updateHud();fx(dt);trails.push({x:player.x,y:player.y,life:oc?.40:(fever?.34:.24),r:player.r*(oc?.9:(fever?.82:.7)),heavy:player.heavy});if(trails.length>(oc?58:fever?48:34))trails.shift();
}

function fx(dt){landingPulse*=Math.pow(.004,dt);toastT=Math.max(0,toastT-dt);for(const p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=(p.gravity??420)*dt;p.vx*=.985}particles=particles.filter(p=>p.life>0);for(const s of sparks){s.life-=dt;s.x+=s.vx*dt;s.y+=s.vy*dt;s.vy+=800*dt;s.vx*=.98}sparks=sparks.filter(s=>s.life>0);for(const r of rings){r.life-=dt;r.r+=280*dt}rings=rings.filter(r=>r.life>0);for(const s of shockwaves){s.life-=dt;s.r+=360*dt}shockwaves=shockwaves.filter(s=>s.life>0);for(const t of trails)t.life-=dt;trails=trails.filter(t=>t.life>0);shake*=Math.pow(.015,dt);flash*=Math.pow(.01,dt);beatPulse*=Math.pow(.004,dt)}
function updateHud(){const pct=clamp((player.x-START_X)/(END_X-START_X)*100,0,100);ui.fill.style.width=`${pct}%`;ui.distance.textContent=`${Math.round(pct)}%`;ui.flowFill.style.width=`${flowMeter}%`;ui.scoreLive.textContent=Math.round(points).toLocaleString('de-CH');ui.combo.textContent=`×${combo}`;ui.sector.textContent=`${activeRun.name} RUN`;ui.runTag.textContent=activeRun.tag;ui.overclock.classList.toggle('hidden',overclockT<=0);if(overclockT>0)ui.overclockTime.textContent=overclockT.toFixed(1);ui.attempt.textContent=attempt;ui.beatFlash.classList.toggle('on',beatPulse>.52)}
function finish(){finished=true;running=false;const timeBonus=Math.max(0,1100-worldTime*13),score=Math.round(points+bestCombo*80+perfects*34+fluxCount*35+timeBonus),ratio=worldTime/activeRun.target;let rank='C',starN=1;if(score>3300&&ratio<1.32){rank='B';starN=2}if(score>4300&&ratio<1.15){rank='A';starN=3}if(score>5100&&ratio<1.03&&perfects>=6){rank='S';starN=3}const key=`hl10_${activeRun.id}`,prevScore=storeNum(key+'_score'),prevTime=storeNum(key+'_time'),isBest=score>prevScore;if(isBest)store(key+'_score',score);if(!prevTime||worldTime<prevTime)store(key+'_time',worldTime);store(key+'_stars',Math.max(storeNum(key+'_stars'),starN));ui.score.textContent=score.toLocaleString('de-CH');ui.title.textContent=rank==='S'?'PERFEKTER FLOW!':rank==='A'?'STARKER RUN!':rank==='B'?'SAUBER!':'GESCHAFFT!';ui.rank.textContent=rank;ui.stars.textContent='★'.repeat(starN)+'☆'.repeat(3-starN);ui.time.textContent=`${worldTime.toFixed(1)}s`;ui.comboStat.textContent=`×${bestCombo}`;ui.fluxStat.textContent=`${fluxCount}/${flux.length}`;ui.overclockStat.textContent=`${overclockCount}×`;ui.resultRun.textContent=`${activeRun.name} · COMPLETE`;ui.text.textContent=`${perfects} perfekte Aktionen · ${Math.round(timeBonus)} Zeitbonus${isBest?' · NEUER BESTSCORE!':prevScore?` · Best ${prevScore.toLocaleString('de-CH')}`:''}`;ui.next.classList.toggle('hidden',selectedRun>=RUNS.length-1);tone(740,.23,'triangle',.065);setTimeout(()=>{ui.hud.classList.add('hidden');ui.mode.classList.add('hidden');ui.overclock.classList.add('hidden');ui.result.classList.remove('hidden')},320)}
function refreshMenu(){document.querySelectorAll('.runCard').forEach((el,i)=>{el.classList.toggle('active',i===selectedRun);const run=RUNS[i],score=storeNum(`hl10_${run.id}_score`),stars=storeNum(`hl10_${run.id}_stars`),record=$(`record${i}`);record.textContent=score?`${'★'.repeat(stars)} ${score.toLocaleString('de-CH')}`:'NEU'});ui.play.textContent=`RUN 0${selectedRun+1} STARTEN`}

document.querySelectorAll('.runCard').forEach(el=>el.onclick=()=>{cloneRun(Number(el.dataset.run))});ui.play.onclick=()=>startRun(selectedRun);ui.restart.onclick=()=>{resetRun();running=true};ui.again.onclick=()=>startRun(selectedRun);ui.next.onclick=()=>startRun(Math.min(RUNS.length-1,selectedRun+1));ui.menuBtn.onclick=showMenu;
cloneRun(0);showMenu();requestAnimationFrame(function frame(now){const dt=Math.min(.03,(now-last)/1000||.016);last=now;update(dt);draw();requestAnimationFrame(frame)});
window.__HL10__={player,get objects(){return objects},get flux(){return flux},RUNS,startRun,setMode,state:()=>({run:selectedRun,x:player.x,y:player.y,heavy:player.heavy,points,combo,bestCombo,fluxCount,flowMeter,overclockT,overclockCount,beatPulse,finished,worldTime,checkpointX,attempt,speedBoostT,landingPulse})};
