const APP_VERSION='2026-08-20-family-v2';
const STORE='family-command-personal-v2';
const CHECKS='family-command-checks-v2';
const DAYS=['Sonntag','Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag'];
const COLORS={oli:'#111827',jayden:'#2563eb',fynn:'#b45309',eliyah:'#059669'};
const PUSH_BASE='https://lmrvapstojcecljjdgds.supabase.co/functions/v1/family-command-app';
const VAPID='BC157M9MAFwOjUFcM6ZyG332hznCA0_VA4rxamO6I7ZOK5nKX2eWgJmsaoyIMGGTUF4bOQH0z2HGXoyq3RBdh6M';

const seed={version:APP_VERSION,people:[
{id:'oli',name:'Oli',role:'Papa',color:COLORS.oli,school:'',teachers:[],notes:['Eigene Termine erscheinen zusammen mit den Kinderterminen in der Familienübersicht.']},
{id:'jayden',name:'Jayden',role:'5. Klasse · Schuljahr 2026/27',color:COLORS.jayden,school:'Schule Herzogenbuchsee · Klasse 5/6 A',teachers:[
{name:'Rageta Rasaratnam (RR)',role:'Klassenlehrperson',phone:'077 963 31 77'},
{name:'Jannik Glauser (JG)',role:'Teilpensenlehrperson',phone:'079 586 43 73'},
{name:'Susanna Kessler (SK)',role:'Integrative Förderung IF',phone:'079 432 61 51'},
{name:'Carolin Steinmann (CS)',role:'TTG-Lehrperson',phone:'079 745 38 32'},
{name:'Barbara Meyer (BM)',role:'TTG-Lehrperson',phone:'079 270 69 04'}],notes:['TTG = Technisches und Textiles Gestalten.','MuI = Medien und Informatik.','Mittwoch Sport/Schwimmen; Freitag Sport.','Schulfotos können nach dem Fototermin über eine persönliche Online-Galerie bestellt werden.','Elternsprechstunde Schulleitung: während der Schulzeit am letzten Freitag des Monats, 07:00–08:30 Uhr, Büro Mittelholz; ohne Voranmeldung.']},
{id:'fynn',name:'Fynn',role:'3. Klasse · Klasse 34e',color:COLORS.fynn,school:'Schule Herzogenbuchsee · Klasse 34e',teachers:[
{name:'Barbara Ingold',role:'Klassenlehrerin',phone:'078 889 33 06'},
{name:'Ramona Huwiler',role:'Teilpensenlehrerin',phone:'079 524 50 93'},
{name:'Susanna Kessler',role:'Schulische Heilpädagogin',phone:'079 474 62 65'},
{name:'Marietta Bättig',role:'Technisches Gestalten',phone:''},
{name:'Sandra Kühne',role:'DaZ · Deutsch als Zweitsprache',phone:''}],notes:['Werkgruppe: Technisch – Textil.','Montag und Mittwoch Bewegung und Sport.','AdS am Mittwoch- und Freitagnachmittag.','Montag: Ingold · Dienstag: Huwiler · Mittwoch: Ingold · Donnerstag: Huwiler/Ingold · Freitag: Ingold.','17.08.–04.09.2026: Frau Huwiler wird durch Frau Romano vertreten.','Frau Hügli absolviert bis zu den Herbstferien ein sechswöchiges Praktikum in der Klasse.','Jahresthema: Rund um die Welt.','Absenzen immer über KLAPP; keine separate Nachricht an eine Lehrperson.','Schulfotos können nach dem Fototermin über eine persönliche Online-Galerie bestellt werden.','Elternsprechstunde Schulleitung: während der Schulzeit am letzten Freitag des Monats, 07:00–08:30 Uhr, Büro Mittelholz; ohne Voranmeldung.']},
{id:'eliyah',name:'Eliyah',role:'Kindergarten Rosenweg 1',color:COLORS.eliyah,school:'Kindergarten Rosenweg 1 · Herzogenbuchsee',teachers:[
{name:'Cornelia Straub',role:'Klassenlehrperson',phone:''},
{name:'Denise Ruch',role:'Teilpensum und IF-Lehrperson',phone:''},
{name:'Nathalie Wyttenbach',role:'Klassenassistenz',phone:''},
{name:'Esther Gschwind',role:'Unterstützung am Turnmorgen',phone:''}],notes:['Montag Tagesschule · Abfahrt ca. 07:20 Uhr.','Mittwoch Tagesschule · Abfahrt ca. 07:00 Uhr.','Dienstag nur am Nachmittag Kindergarten.','Mittwoch Turnmorgen: Turnzeug bereits anziehen; Turnschuhe, Trinkflasche und Znüni mitnehmen.','24.08.–17.09.2026 Praktikum: Michelle Meier montags den ganzen Tag; Lariya Siegenthaler dienstagnachmittags und donnerstagvormittags.']}
],schedules:{
jayden:{1:[{start:'07:30',end:'11:50',label:'Schule'},{start:'13:30',end:'16:05',label:'Schule'}],2:[{start:'08:20',end:'11:50',label:'Schule'},{start:'13:30',end:'16:05',label:'Schule'}],3:[{start:'07:30',end:'11:50',label:'Schule · Sport/Schwimmen'}],4:[{start:'08:20',end:'11:50',label:'Schule'},{start:'13:30',end:'15:05',label:'Schule'}],5:[{start:'07:30',end:'11:50',label:'Schule · Sport'}]},
fynn:{1:[{start:'08:20',end:'11:50',label:'Schule · Sport'},{start:'13:30',end:'16:05',label:'Schule · Franz 3'}],2:[{start:'08:20',end:'11:50',label:'Schule'},{start:'13:30',end:'15:05',label:'Schule'}],3:[{start:'07:30',end:'11:50',label:'Schule · Sport'},{start:'13:30',end:'15:05',label:'AdS'}],4:[{start:'08:20',end:'11:50',label:'Schule · TTG'},{start:'13:30',end:'15:05',label:'Schule'}],5:[{start:'08:20',end:'11:50',label:'Schule'},{start:'13:30',end:'15:05',label:'AdS'}]},
eliyah:{1:[{start:'08:20',end:'11:50',label:'Kindergarten',depart:'07:20',note:'Tagesschule'}],2:[{start:'13:25',end:'15:15',label:'Kindergarten · NINI-Kinder'}],3:[{start:'08:20',end:'11:50',label:'Kindergarten · Turnen',depart:'07:00',note:'Tagesschule'}],4:[{start:'08:20',end:'11:50',label:'Kindergarten'}],5:[{start:'08:20',end:'11:50',label:'Kindergarten'}]}
},reminders:[
{id:'eli-daily',personId:'eliyah',days:[1,2,3,4,5],items:['Rucksack','Znüni-Box','Leuchtweste']},
{id:'eli-wed',personId:'eliyah',days:[3],items:['Trinkflasche','Turnschuhe','Turnzeug anziehen']},
{id:'jay-wed',personId:'jayden',days:[3],items:['Turn- oder Badezeug mitnehmen']},
{id:'jay-fri',personId:'jayden',days:[5],items:['Turnzeug mitnehmen']},
{id:'fyn-mon',personId:'fynn',days:[1],items:['Turnzeug mitnehmen']},
{id:'fyn-wed',personId:'fynn',days:[3],items:['Turn- oder Badezeug mitnehmen']}
],events:[
{id:'oli-party',personIds:['oli'],title:'Mathias’ 40. Geburtstagsparty',date:'2026-08-22',time:'15:00',end:'',note:'Schützenhaus in Bettlach.'},
{id:'fynn-elternabend',personIds:['fynn'],title:'Elternabend 3./4. Klassen',date:'2026-08-25',time:'19:00',end:'',note:'Start 19:00 Uhr in der Aula.'},
{id:'jayden-elternabend',personIds:['jayden'],title:'Elternabend 5./6. Klasse',date:'2026-08-27',time:'19:00',end:'',note:'An- und Abmeldung via KLAPP.'},
{id:'jayden-besuch',personIds:['jayden'],title:'Besuchswoche',date:'2026-08-31',endDate:'2026-09-04',time:'',end:'',note:'Eltern dürfen ohne Voranmeldung den Unterricht besuchen.'},
{id:'fynn-biblio',personIds:['fynn'],title:'Bibliothek',date:'2026-09-01',time:'',end:'',note:''},
{id:'fynn-herbstbummel',personIds:['fynn'],title:'Herbstbummel',date:'2026-09-03',time:'',end:'',note:''},
{id:'fynn-ingold',personIds:['fynn'],title:'Geburtstag Frau Ingold',date:'2026-09-06',time:'',end:'',note:''},
{id:'eli-aaron',personIds:['eliyah'],title:'Geburtstag Aaron · Znünibuffet',date:'2026-09-07',time:'',end:'',note:'Gemeinsames Znünibuffet im Kindergarten.'},
{id:'jay-bike',personIds:['jayden'],title:'Praktisches Fahrradfahren',date:'2026-09-08',time:'',end:'',note:'5. Klasse mit Herrn Hufenus.'},
{id:'oli-psy',personIds:['oli'],title:'Psychiatrisches Ambulatorium',date:'2026-09-08',time:'09:00',end:'',note:'SRO AG PanoramaPark, Stellweg 24, 3360 Herzogenbuchsee. Tel. 062 955 51 20.'},
{id:'evac',personIds:['jayden','fynn','eliyah'],title:'Evakuationsübung',date:'2026-09-10',time:'',end:'',note:'Während der Unterrichtszeit.'},
{id:'open-door',personIds:['jayden','fynn'],title:'Tag der offenen Tür Neubau Oenz',date:'2026-09-12',time:'',end:'',note:'Bei Fynn gleichzeitig Eröffnungsfest Pumptrack Niederönz.'},
{id:'jay-teeth',personIds:['jayden'],title:'Zähneputzen',date:'2026-09-14',time:'',end:'',note:''},
{id:'eli-walk',personIds:['eliyah'],title:'Herbstbummel',date:'2026-09-18',time:'08:30',end:'13:30',note:'Kleine Wanderung in die nähere Umgebung. Genauere Infos folgen.'},
{id:'autumn',personIds:['jayden','fynn','eliyah'],title:'Herbstferien',date:'2026-09-19',endDate:'2026-10-11',time:'',end:'',note:'Offizieller Ferienplan Schule Herzogenbuchsee.'},
{id:'school-resume',personIds:['jayden','fynn','eliyah'],title:'Unterrichtsbeginn nach Stundenplan',date:'2026-10-12',time:'',end:'',note:''},
{id:'oli-social',personIds:['oli'],title:'Sozialberatung bei Frau Zwygart',date:'2026-10-26',time:'14:00',end:'',note:''},
{id:'eli-dentist',personIds:['eliyah'],title:'Besuch Schulzahnarzt',date:'2026-11-05',time:'',end:'',note:'Korrigierter Termin. Eltern begleiten ihr Kind. Ursprünglich war 29.10. kommuniziert.'},
{id:'jay-future',personIds:['jayden'],title:'Nationaler Zukunftstag',date:'2026-11-12',time:'',end:'',note:'Einblick in die Berufswelt; weitere Informationen gemäss Schulbrief.'}
],common:{school:{name:'Schulverwaltung Herzogenbuchsee',address:'Mittelholzstrasse 34, 3360 Herzogenbuchsee',phone:'062 961 57 06'},care:[{name:'Saibe Kabashi · Kinderhut',phone:'076 403 81 98',email:'saibe.kabashi@kinderhut.ch'},{name:'Tagesschule Herzogenbuchsee',phone:'079 619 79 00',email:'tagesschule@kinderhut.ch'}]}};

let data=load(),selectedProfile='jayden',weekOffset=0,selectedWeekDay=null;
function clone(v){return JSON.parse(JSON.stringify(v))}
function load(){try{const x=JSON.parse(localStorage.getItem(STORE)||'null');if(x&&x.version===APP_VERSION)return x}catch(e){}const s=clone(seed);localStorage.setItem(STORE,JSON.stringify(s));return s}
function save(){data.version=APP_VERSION;localStorage.setItem(STORE,JSON.stringify(data));syncPush().catch(()=>{})}
function person(id){return data.people.find(p=>p.id===id)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function iso(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function todayISO(){return iso(new Date())}
function fmtDate(s,o={}){if(!s)return'';const d=new Date(s+'T12:00:00');return new Intl.DateTimeFormat('de-CH',{day:'2-digit',month:'2-digit',year:o.year?'numeric':undefined,weekday:o.weekday?'short':undefined}).format(d)}
function longDate(d){return new Intl.DateTimeFormat('de-CH',{weekday:'long',day:'numeric',month:'long'}).format(d)}
function phoneHref(s){return'tel:'+String(s).replace(/\s/g,'')}
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function eventPersons(e){return(e.personIds||[]).map(id=>person(id)).filter(Boolean)}
function eventsOn(date){return data.events.filter(e=>e.date===date||(e.endDate&&e.date<=date&&e.endDate>=date)).sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99'))}
function upcoming(limit=6){const t=todayISO();return data.events.filter(e=>(e.endDate||e.date)>=t).sort((a,b)=>(a.date+(a.time||'99:99')).localeCompare(b.date+(b.time||'99:99'))).slice(0,limit)}
function scheduleFor(id,day){return data.schedules[id]?.[day]||[]}
function remindersFor(day){return data.reminders.filter(r=>r.days.includes(day))}
function checkKey(date,rid,item){return date+'|'+rid+'|'+item}
function checks(){try{return JSON.parse(localStorage.getItem(CHECKS)||'{}')}catch(e){return{}}}
function setCheck(key,on){const c=checks();c[key]=on;localStorage.setItem(CHECKS,JSON.stringify(c));renderToday()}
function nextImportant(){const now=new Date(),date=todayISO(),mins=now.getHours()*60+now.getMinutes();let items=[];for(const p of data.people){for(const s of scheduleFor(p.id,now.getDay())){const[h,m]=s.start.split(':').map(Number);items.push({when:h*60+m,title:p.name+' · '+s.label,sub:(s.depart?'Abfahrt '+s.depart+' · ':'')+s.start+'–'+s.end,time:s.depart||s.start})}}for(const e of eventsOn(date)){if(e.time){const[h,m]=e.time.split(':').map(Number);items.push({when:h*60+m,title:e.title,sub:eventPersons(e).map(x=>x.name).join(', '),time:e.time})}}items=items.filter(x=>x.when>=mins-5).sort((a,b)=>a.when-b.when);if(items[0])return items[0];const up=upcoming(1)[0];return up?{title:up.title,sub:fmtDate(up.date,{weekday:true})+' · '+eventPersons(up).map(x=>x.name).join(', '),time:up.time||'Termin'}:null}
function eventRow(e,showDate=false){const ps=eventPersons(e),time=e.time?e.time+(e.end?'–'+e.end:''):(showDate?fmtDate(e.date,{weekday:true}):'ganztägig');return'<div class="eventrow"><div class="eventtime">'+esc(time)+'</div><div class="eventmain"><b>'+esc(e.title)+'</b>'+(e.note?'<p>'+esc(e.note)+'</p>':'')+'<div class="chips">'+ps.map(p=>'<span class="chip" style="background:'+p.color+'12;color:'+p.color+'">'+esc(p.name)+'</span>').join('')+'</div></div></div>'}

function renderToday(){const root=document.getElementById('today'),now=new Date(),date=iso(now),day=now.getDay(),c=checks(),next=nextImportant();const peopleHtml=data.people.map(p=>{const slots=scheduleFor(p.id,day);let state='Heute keine feste Zeit',strong='frei';if(slots.length){state=slots.map(s=>s.label).join(' · ');strong=slots.map(s=>(s.depart?'Abfahrt '+s.depart:'Start '+s.start)).join(' / ')}return'<div class="person-card"><div class="person-top"><i class="dot" style="background:'+p.color+'"></i><b>'+esc(p.name)+'</b></div><div class="state">'+esc(state)+'</div><div class="strong">'+esc(strong)+'</div></div>'}).join('');const reminderHtml=remindersFor(day).map(r=>{const p=person(r.personId);return'<div class="check-group"><div class="check-title"><i class="dot" style="background:'+p.color+'"></i>'+esc(p.name)+'</div><div class="checklist">'+r.items.map(item=>{const k=checkKey(date,r.id,item),on=!!c[k];return'<label class="checkrow '+(on?'done':'')+'"><input type="checkbox" '+(on?'checked':'')+' onchange="setCheck('+JSON.stringify(k)+',this.checked)"><span>'+esc(item)+'</span></label>'}).join('')+'</div></div>'}).join('')||'<div class="empty">Heute gibt es keine Pack-Erinnerungen.</div>';const todays=eventsOn(date).map(e=>eventRow(e)).join('')||'<div class="empty">Heute keine zusätzlichen Termine.</div>';const up=upcoming(5).map(e=>eventRow(e,true)).join('')||'<div class="empty">Keine kommenden Termine.</div>';root.innerHTML='<div class="hero"><div class="eyebrow">'+esc(longDate(now))+'</div><h2>'+(day===0||day===6?'Wochenende im Blick.':'Heute sofort sehen, was zählt.')+'</h2><p>Stundenpläne, Abfahrten, Packlisten und Termine für die ganze Familie.</p>'+(next?'<div class="hero-next"><div><b>'+esc(next.title)+'</b><span>'+esc(next.sub)+'</span></div><div class="timebadge">'+esc(next.time)+'</div></div>':'')+'</div><div class="section"><div class="section-head"><h3>Heute</h3><span>'+DAYS[day]+'</span></div><div class="people-strip">'+peopleHtml+'</div></div><div class="section grid2"><div><div class="section-head"><h3>Nicht vergessen</h3><span>morgens abhaken</span></div><div class="card"><div class="card-pad">'+reminderHtml+'</div></div></div><div><div class="section-head"><h3>Termine heute</h3></div><div class="card"><div class="card-pad timeline">'+todays+'</div></div></div></div><div class="section"><div class="section-head"><h3>Demnächst</h3><button class="plainbtn" onclick="openScreen(\'events\')">Alle Termine</button></div><div class="card"><div class="card-pad timeline">'+up+'</div></div></div>'}
function mondayOf(d){const x=new Date(d),diff=(x.getDay()+6)%7;x.setDate(x.getDate()-diff);x.setHours(12,0,0,0);return x}
function renderWeek(){const root=document.getElementById('week'),base=mondayOf(new Date());base.setDate(base.getDate()+weekOffset*7);if(!selectedWeekDay)selectedWeekDay=iso(base);let btns='',dates=[];for(let i=0;i<5;i++){const d=new Date(base);d.setDate(base.getDate()+i);dates.push(d);const di=iso(d);btns+='<button class="daybtn '+(selectedWeekDay===di?'active':'')+'" onclick="selectedWeekDay=\''+di+'\';renderWeek()"><b>'+DAYS[d.getDay()].slice(0,2)+'</b><span>'+String(d.getDate()).padStart(2,'0')+'.'+String(d.getMonth()+1).padStart(2,'0')+'</span></button>'}const cur=dates.find(d=>iso(d)===selectedWeekDay)||dates[0],day=cur.getDay();let rows=['jayden','fynn','eliyah'].map(id=>{const p=person(id),slots=scheduleFor(id,day);return'<div class="schedule-row"><div class="schedule-name"><i class="dot" style="background:'+p.color+'"></i>'+p.name+'</div><div class="schedule-blocks">'+(slots.length?slots.map(s=>'<div class="slot '+(s.depart?'special':'')+'"><b>'+s.start+'–'+s.end+'</b><br>'+esc(s.label)+(s.depart?'<br>Abfahrt '+s.depart:'')+'</div>').join(''):'<div class="slot">frei</div>')+'</div></div>'}).join('');const rem=remindersFor(day);if(rem.length)rows+='<div class="card"><div class="card-pad"><div class="check-title">Morgen-Check</div>'+rem.map(r=>'<div class="note"><b>'+person(r.personId).name+':</b> '+r.items.map(esc).join(' · ')+'</div>').join('')+'</div></div>';const ev=eventsOn(iso(cur));if(ev.length)rows+='<div class="card"><div class="card-pad timeline">'+ev.map(e=>eventRow(e)).join('')+'</div></div>';root.innerHTML='<div class="section-head"><div><h3>Wochenplan</h3><span>'+fmtDate(iso(base))+' – '+fmtDate(iso(dates[4]),{year:true})+'</span></div><div><button class="pill" onclick="weekOffset--;selectedWeekDay=null;renderWeek()">‹</button> <button class="pill" onclick="weekOffset++;selectedWeekDay=null;renderWeek()">›</button></div></div><div class="days">'+btns+'</div><div class="week-stack">'+rows+'</div>'}
function renderPeople(){const root=document.getElementById('people'),p=person(selectedProfile),tabs=data.people.map(x=>'<button class="pill '+(x.id===selectedProfile?'active':'')+'" onclick="selectedProfile=\''+x.id+'\';renderPeople()">'+esc(x.name)+'</button>').join(''),teachers=p.teachers.length?p.teachers.map(t=>'<div class="contact"><div><b>'+esc(t.name)+'</b><span>'+esc(t.role)+'</span></div>'+(t.phone?'<a class="call" href="'+phoneHref(t.phone)+'">'+esc(t.phone)+'</a>':'')+'</div>').join(''):'<div class="empty">Keine Lehrpersonen hinterlegt.</div>';let schedule='';if(data.schedules[p.id])for(let d=1;d<=5;d++){const slots=scheduleFor(p.id,d);schedule+='<div class="contact"><div><b>'+DAYS[d]+'</b><span>'+(slots.length?slots.map(s=>s.start+'–'+s.end).join(' · '):'frei')+'</span></div></div>'}else schedule='<div class="empty">Kein wiederkehrender Stundenplan.</div>';root.innerHTML='<div class="profile-tabs">'+tabs+'</div><div class="card"><div class="card-pad"><div class="profile-hero"><div class="avatar" style="background:'+p.color+'">'+esc(p.name.slice(0,1))+'</div><div><h2>'+esc(p.name)+'</h2><p>'+esc(p.role)+'</p>'+(p.school?'<p>'+esc(p.school)+'</p>':'')+'</div></div></div></div><div class="info-grid"><div class="info-card"><h4>'+(p.id==='oli'?'Kontakte':'Lehrpersonen & Kontakte')+'</h4>'+teachers+'</div><div class="info-card"><h4>Wochenzeiten</h4>'+schedule+'</div></div><div class="section"><div class="section-head"><h3>Wichtige Hinweise</h3></div><div class="card"><div class="card-pad">'+p.notes.map(n=>'<div class="note">• '+esc(n)+'</div>').join('')+'</div></div></div>'}
function renderEvents(filter='all'){const root=document.getElementById('events'),filters=['all',...data.people.map(p=>p.id)].map(id=>'<button class="pill '+(filter===id?'active':'')+'" onclick="renderEvents(\''+id+'\')">'+(id==='all'?'Alle':person(id).name)+'</button>').join(''),t=todayISO();const es=data.events.filter(e=>(e.endDate||e.date)>=t&&(filter==='all'||e.personIds.includes(filter))).sort((a,b)=>(a.date+(a.time||'99:99')).localeCompare(b.date+(b.time||'99:99')));let html='',last='';for(const e of es){if(e.date!==last){last=e.date;html+='<div class="term-group"><div class="term-date">'+fmtDate(e.date,{weekday:true,year:true})+(e.endDate?' – '+fmtDate(e.endDate,{year:true}):'')+'</div>'}html+='<div class="term-card"><div class="term-top"><b>'+esc(e.title)+'</b><span class="term-time">'+esc(e.time?e.time+(e.end?'–'+e.end:''):'')+'</span></div>'+(e.note?'<p>'+esc(e.note)+'</p>':'')+'<div class="chips">'+eventPersons(e).map(p=>'<span class="chip" style="background:'+p.color+'12;color:'+p.color+'">'+p.name+'</span>').join('')+'</div></div>'}root.innerHTML='<div class="section-head"><h3>Termine</h3><button class="pill" onclick="openEventModal()">＋ Neu</button></div><div class="filterbar">'+filters+'</div>'+(html||'<div class="empty">Keine kommenden Termine.</div>')}

function renderMore(){const root=document.getElementById('more');root.innerHTML='<div class="section-head"><h3>Mehr</h3></div><div class="settings-stack"><div class="setting"><h4>Morgenbericht · 06:30</h4><p>Auf dem iPhone als App zum Home-Bildschirm hinzufügen und Push aktivieren. Danach kann Family Command den Morgenbericht auch bei geschlossener App senden.</p><button class="action secondary" id="pushEnable">Push einrichten</button><button class="action light" style="margin-top:8px" id="pushTest">Test-Push senden</button><div class="status" id="pushStatus">Status wird geprüft …</div></div><div class="setting"><h4>Dokumente fotografieren</h4><p>Schulbriefe und Zettel kannst du direkt fotografieren und lokal auf diesem Gerät ablegen.</p><div class="row2"><select id="docPerson" class="pill" style="width:100%">'+data.people.filter(p=>p.id!=='oli').map(p=>'<option value="'+p.id+'">'+p.name+'</option>').join('')+'</select><input id="docTitle" placeholder="Titel" style="width:100%;border:1px solid var(--line);border-radius:12px;padding:10px"></div><input id="docFile" type="file" accept="image/*" capture="environment" style="margin-top:10px;width:100%"><button class="action light" style="margin-top:10px" onclick="saveDoc()">Foto speichern</button><div class="doc-list" id="docList"></div></div><div class="setting"><h4>Schule & Betreuung</h4><div class="contact"><div><b>'+esc(data.common.school.name)+'</b><span>'+esc(data.common.school.address)+'</span></div><a class="call" href="'+phoneHref(data.common.school.phone)+'">'+esc(data.common.school.phone)+'</a></div>'+data.common.care.map(x=>'<div class="contact"><div><b>'+esc(x.name)+'</b><span>'+esc(x.email||'')+'</span></div><a class="call" href="'+phoneHref(x.phone)+'">'+esc(x.phone)+'</a></div>').join('')+'</div><div class="setting"><h4>Daten sichern</h4><p>Alle Familien- und Termin-Daten lassen sich als JSON sichern. Dokumentfotos bleiben separat lokal gespeichert.</p><button class="action light" onclick="exportData()">Backup exportieren</button><button class="action light" style="margin-top:8px" onclick="resetSeed()">Auf vorbereitete Daten zurücksetzen</button></div></div>';setupPushUI();renderDocs()}
function openScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));if(id==='today')renderToday();if(id==='week')renderWeek();if(id==='people')renderPeople();if(id==='events')renderEvents();if(id==='more')renderMore();window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.navbtn').forEach(b=>b.onclick=()=>openScreen(b.dataset.screen));
function openEventModal(){document.getElementById('eventPerson').innerHTML=data.people.map(p=>'<option value="'+p.id+'">'+p.name+'</option>').join('');document.getElementById('eventDate').value=todayISO();document.getElementById('eventModal').classList.add('open')}
function closeEventModal(){document.getElementById('eventModal').classList.remove('open')}
document.getElementById('quickAdd').onclick=openEventModal;document.getElementById('closeEvent').onclick=closeEventModal;document.getElementById('eventModal').onclick=e=>{if(e.target.id==='eventModal')closeEventModal()};
document.getElementById('saveEvent').onclick=()=>{const title=document.getElementById('eventTitle').value.trim(),date=document.getElementById('eventDate').value;if(!title||!date)return toast('Titel und Datum fehlen');data.events.push({id:'custom-'+Date.now(),personIds:[document.getElementById('eventPerson').value],title,date,time:document.getElementById('eventTime').value,end:'',note:document.getElementById('eventNote').value.trim()});save();closeEventModal();renderEvents();toast('Termin gespeichert')};
function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='family-command-backup-'+todayISO()+'.json';a.click();URL.revokeObjectURL(a.href)}
function resetSeed(){if(!confirm('Wirklich auf die vorbereiteten Daten zurücksetzen? Eigene nachträgliche Termine gehen verloren.'))return;data=clone(seed);save();renderToday();toast('Daten zurückgesetzt')}

let dbp=null;function db(){if(dbp)return dbp;dbp=new Promise((res,rej)=>{const r=indexedDB.open('fc-personal-docs',1);r.onupgradeneeded=()=>r.result.createObjectStore('docs',{keyPath:'id'});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return dbp}
async function saveDoc(){const f=document.getElementById('docFile').files[0];if(!f)return toast('Bitte zuerst ein Foto wählen');const rec={id:'doc-'+Date.now(),personId:document.getElementById('docPerson').value,title:document.getElementById('docTitle').value.trim()||f.name,created:new Date().toISOString(),blob:f},d=await db();await new Promise((res,rej)=>{const tx=d.transaction('docs','readwrite');tx.objectStore('docs').put(rec);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});document.getElementById('docTitle').value='';document.getElementById('docFile').value='';renderDocs();toast('Dokument gespeichert')}
async function listDocs(){const d=await db();return new Promise((res,rej)=>{const r=d.transaction('docs').objectStore('docs').getAll();r.onsuccess=()=>res(r.result.sort((a,b)=>b.created.localeCompare(a.created)));r.onerror=()=>rej(r.error)})}
async function renderDocs(){const el=document.getElementById('docList');if(!el)return;const ds=await listDocs().catch(()=>[]);el.innerHTML=ds.length?ds.map(x=>{const u=URL.createObjectURL(x.blob);return'<div class="doc"><img class="thumb" src="'+u+'"><div><b>'+esc(x.title)+'</b><span>'+esc(person(x.personId)?.name||'')+' · '+fmtDate(x.created.slice(0,10),{year:true})+'</span></div></div>'}).join(''):'<div class="empty">Noch keine Dokumentfotos gespeichert.</div>'}

const DID='fc-push-device-v2',DTOK='fc-push-token-v2';let swreg=null;
function b64(a){return btoa(String.fromCharCode(...a)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function randomToken(n){const a=new Uint8Array(n);crypto.getRandomValues(a);return b64(a)}
function device(){let id=localStorage.getItem(DID),token=localStorage.getItem(DTOK);if(!id){id=crypto.randomUUID?.()||randomToken(18);localStorage.setItem(DID,id)}if(!token){token=randomToken(32);localStorage.setItem(DTOK,token)}return{id,token}}
function key(s){const p='='.repeat((4-s.length%4)%4),raw=atob((s+p).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from(raw,c=>c.charCodeAt(0))}
function isIOS(){return/iphone|ipad|ipod/i.test(navigator.userAgent)}function standalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}
function reminderTasks(daysAhead=180){const out=[],start=new Date();start.setHours(12,0,0,0);for(let i=0;i<daysAhead;i++){const d=new Date(start);d.setDate(start.getDate()+i);const day=d.getDay(),date=iso(d);for(const r of data.reminders){if(!r.days.includes(day))continue;for(const item of r.items)out.push({id:'rem-'+r.id+'-'+date+'-'+item,personId:r.personId,title:person(r.personId).name+': '+item,date,note:'Morgen-Check',done:false})}}return out}
function pushSnapshot(){const rules=[];for(const[pid,days]of Object.entries(data.schedules))for(const[day,slots]of Object.entries(days))for(const s of slots)rules.push({id:pid+'-'+day+'-'+s.start,personId:pid,title:s.label,day:Number(day),time:s.depart||s.start,end:s.end,note:s.note||''});return{people:data.people.map(p=>({id:p.id,name:p.name,color:p.color})),settings:{travel:0,prep:0,pickup:0,evening:'19:00'},events:data.events.map(e=>({id:e.id,personId:e.personIds?.[0]||'',title:e.title,date:e.date,time:e.time||'',end:e.end||'',note:e.note||'',reminder:0})),tasks:reminderTasks(),rules}}
async function post(path,payload){const r=await fetch(PUSH_BASE+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'HTTP '+r.status);return j}
async function reg(){if(swreg)return swreg;if(!('serviceWorker'in navigator))throw new Error('Service Worker nicht unterstützt');swreg=await navigator.serviceWorker.register('./sw.js',{scope:'./'});await navigator.serviceWorker.ready;return swreg}
async function pushSub(){return(await reg()).pushManager.getSubscription()}
async function enablePush(){try{if(isIOS()&&!standalone())return alert('Auf dem iPhone zuerst Safari → Teilen → Zum Home-Bildschirm. Danach Family Command von dort öffnen und Push nochmals einrichten.');const r=await reg(),perm=await Notification.requestPermission();if(perm!=='granted')throw new Error('Mitteilungen wurden nicht erlaubt');let s=await r.pushManager.getSubscription();if(!s)s=await r.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key(VAPID)});const d=device();await post('/push/subscribe',{deviceId:d.id,deviceToken:d.token,subscription:s.toJSON(),state:pushSnapshot(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'Europe/Zurich',morningTime:'06:30'});setPushStatus('Aktiv · Morgenbericht täglich um 06:30');toast('Push aktiviert')}catch(e){setPushStatus('Fehler: '+e.message)}}
async function syncPush(){try{if(!('Notification'in window)||Notification.permission!=='granted')return;const s=await pushSub();if(!s)return;const d=device();await post('/push/sync',{deviceId:d.id,deviceToken:d.token,state:pushSnapshot(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'Europe/Zurich',morningTime:'06:30'})}catch(e){}}
async function testPush(){try{const s=await pushSub();if(!s)return setPushStatus('Bitte Push zuerst einrichten.');await syncPush();const d=device();await post('/push/test',{deviceId:d.id,deviceToken:d.token});setPushStatus('Test-Push wurde gesendet.')}catch(e){setPushStatus('Test fehlgeschlagen: '+e.message)}}
function setPushStatus(t){const e=document.getElementById('pushStatus');if(e)e.textContent=t}
async function setupPushUI(){const a=document.getElementById('pushEnable'),b=document.getElementById('pushTest');if(!a)return;a.onclick=enablePush;b.onclick=testPush;if(!('PushManager'in window)||!('Notification'in window))return setPushStatus('Dieses Gerät unterstützt Web-Push nicht.');if(isIOS()&&!standalone())return setPushStatus('iPhone: zuerst zum Home-Bildschirm hinzufügen.');try{const s=await pushSub();setPushStatus(s&&Notification.permission==='granted'?'Aktiv · Morgenbericht um 06:30':'Noch nicht eingerichtet.')}catch(e){setPushStatus(e.message)}}
window.addEventListener('pagehide',()=>syncPush());document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')syncPush()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{});
renderToday();