/* Familienzentrale V9.63.0 · Tagescheck · read-only aggregation of canonical family data */
(()=>{'use strict';if(window.__fcDailyCheckInstalled)return;window.__fcDailyCheckInstalled=true;
const D=()=>{try{return typeof data!=='undefined'&&data?data:{}}catch(_){return{}}},iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,today=()=>iso(new Date()),dayOf=x=>new Date(x+'T12:00:00').getDay();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function person(id){return(D().people||[]).find(p=>String(p.id)===String(id))||null}function name(id){return person(id)?.name||String(id||'Familie')}function events(date){return(D().events||[]).filter(e=>String(e.date)===date||(e.endDate&&String(e.date)<=date&&String(e.endDate)>=date))}function todos(date){let a=[];try{a=window.__fcChatCommandSync?.all?.()||D().todos||[]}catch(_){a=D().todos||[]}return a.filter(x=>x&&!x.archived&&!x.done&&String(x.date||'')===date)}function homework(date){return(D().homework||[]).filter(x=>x&&!x.done&&String(x.dueDate||'')===date)}
function reminders(date){const day=dayOf(date),out=[];for(const r of(D().reminders||[])){if(!Array.isArray(r.days)||!r.days.includes(day))continue;for(const item of(r.items||[]))out.push({personId:r.personId,title:String(item)})}return out}
function scheduleNotes(date){const day=dayOf(date),out=[];for(const p of(D().people||[])){if(String(p.id)==='oli')continue;const slots=D().schedules?.[p.id]?.[day]||[];for(const s of slots){const note=String(s.note||'').trim();if(note&&/(mitnehmen|rucksack|turn|bad|schwimm|zeug|angezogen|abfahrt|los)/i.test(note))out.push({personId:p.id,title:note})}}return out}
function uniq(arr){const seen=new Set;return arr.filter(x=>{const k=(x.personId||'')+'|'+String(x.title||'').toLowerCase().replace(/\s+/g,' ').trim();if(!k||seen.has(k))return false;seen.add(k);return true})}
function dataFor(date){const pack=uniq([...reminders(date),...scheduleNotes(date)]),td=todos(date),hw=homework(date),ev=events(date).filter(e=>!/ferien/i.test(String(e.title||'')));const important=td.map(x=>({title:x.title,personId:x.personId||'',time:x.section==='evening'?'Abends':x.section==='morning'?'Morgens':'',priority:!!x.priority})).concat(hw.map(x=>({title:(x.subject?x.subject+' · ':'')+(x.title||'Schulaufgabe'),personId:x.personId||'',time:'',priority:true})));const timeline=ev.map(e=>({title:e.title||'Termin',personId:(e.personIds||[])[0]||'',time:e.time||'Ganztägig',note:e.note||''})).sort((a,b)=>String(a.time==='Ganztägig'?'00:00':a.time).localeCompare(String(b.time==='Ganztägig'?'00:00':b.time)));return{pack,important,timeline,count:pack.length+important.length+timeline.length}}
function row(icon,x){return`<div class="fc-dc-row"><span class="fc-dc-icon">${icon}</span><div><b>${x.personId?esc(name(x.personId))+' · ':''}${esc(x.title)}</b>${x.time||x.note?`<small>${esc([x.time,x.note].filter(Boolean).join(' · '))}</small>`:''}</div></div>`}
function render(root,date){const d=dataFor(date),label=date===today()?'Heute':new Intl.DateTimeFormat('de-CH',{weekday:'long',day:'numeric',month:'long'}).format(new Date(date+'T12:00:00'));root.dataset.dailyCheckDate=date;root.innerHTML=`<section class="fc-dc"><header><div><small>TAGESCHECK</small><h2>${esc(label)}</h2><p>${d.count?`${d.count} wichtige${d.count===1?'r Punkt':' Punkte'} im Blick`:'Nichts Zusätzliches zu beachten'}</p></div><button data-dc-open aria-label="Tagescheck öffnen">›</button></header>${d.count?`<div class="fc-dc-preview">${d.pack.slice(0,2).map(x=>row('🎒',x)).join('')}${d.important.slice(0,2).map(x=>row('●',x)).join('')}${d.timeline.slice(0,2).map(x=>row('◷',x)).join('')}</div>`:`<div class="fc-dc-clear"><b>✓ Alles im Blick</b><span>Für heute gibt es nichts Zusätzliches zu beachten.</span></div>`}</section>`;root.querySelector('[data-dc-open]').onclick=()=>open(date)}
function open(date=today()){document.getElementById('fcDailyCheckModal')?.remove();const d=dataFor(date),m=document.createElement('div');m.id='fcDailyCheckModal';m.className='fc-dc-modal';m.innerHTML=`<section class="fc-dc-sheet"><header><button data-close>‹</button><div><small>TAGESCHECK</small><h2>${esc(new Intl.DateTimeFormat('de-CH',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(date+'T12:00:00')))}</h2></div><span></span></header><nav><button data-shift="-1">‹ Vortag</button><button data-now>Heute</button><button data-shift="1">Nächster Tag ›</button></nav><main>${d.count?`${d.pack.length?`<section><h3>🎒 Mitnehmen & vorbereiten</h3><div class="fc-dc-list">${d.pack.map(x=>row('✓',x)).join('')}</div></section>`:''}${d.important.length?`<section><h3>📌 Wichtig</h3><div class="fc-dc-list">${d.important.map(x=>row(x.priority?'!':'✓',x)).join('')}</div></section>`:''}${d.timeline.length?`<section><h3>🗓 Termine & Ablauf</h3><div class="fc-dc-list">${d.timeline.map(x=>row('◷',x)).join('')}</div></section>`:''}`:`<div class="fc-dc-empty"><b>✓ Alles im Blick</b><p>An diesem Tag gibt es keine zusätzlichen wichtigen Punkte.</p></div>`}</main></section>`;m.querySelector('[data-close]').onclick=()=>m.remove();m.querySelector('[data-now]').onclick=()=>{m.remove();open(today())};m.querySelectorAll('[data-shift]').forEach(b=>b.onclick=()=>{const x=new Date(date+'T12:00:00');x.setDate(x.getDate()+Number(b.dataset.shift));m.remove();open(iso(x))});document.body.appendChild(m)}
function mount(force=false){const todayRoot=document.getElementById('today');if(!todayRoot)return false;let host=todayRoot.querySelector('.fc-dc-host');if(host&&!force&&host.dataset.dailyCheckDate===today())return true;if(!host){const page=todayRoot.querySelector('.fc9-page');if(!page)return false;host=document.createElement('div');host.className='fc-dc-host';const head=page.querySelector('.fc9-pagehead');head?.insertAdjacentElement('afterend',host)}render(host,today());return true}
function install(){const scheduleMount=()=>setTimeout(()=>mount(false),20);document.addEventListener('fc:v9-ready',scheduleMount);const obs=new MutationObserver(()=>{if(document.getElementById('today')?.classList.contains('active')&&!document.querySelector('#today .fc-dc-host'))scheduleMount()});obs.observe(document.getElementById('today')||document.body,{childList:true,subtree:true});window.addEventListener('pageshow',()=>mount(true));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')mount(true)});setTimeout(()=>mount(false),80)}
window.fcOpenDailyCheck=open;window.__fcDailyCheck={version:'9.63.0',open,dataFor,mount,health:()=>({version:'9.63.0',readOnly:true,sources:['reminders','schedules','todos','homework','events'],stableMount:true})};install();
})();