/* Familienzentrale V9.13 · native readable document viewer */
(()=>{
  'use strict';
  if(window.__fcDocumentViewerInstalled)return;window.__fcDocumentViewerInstalled=true;
  const VERSION='1.0.0';
  const DOC_BASE='https://lmrvapstojcecljjdgds.supabase.co/functions/v1/family-command-documents';
  const MODAL='fcDocumentViewer';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function accessKey(){try{const p=document.cookie.split(';').map(x=>x.trim()).find(x=>x.startsWith('fc_private_access='));if(p)return decodeURIComponent(p.split('=').slice(1).join('='))}catch(e){}try{return localStorage.getItem('fc-private-access-v1')||''}catch(e){return''}}
  async function request(path){const h=new Headers();h.set('x-fc-access',accessKey());return fetch(DOC_BASE+path,{headers:h,cache:'no-store'})}
  function tableHtml(t){const cols=Array.isArray(t?.columns)?t.columns:[],rows=Array.isArray(t?.rows)?t.rows:[];if(!cols.length&&!rows.length)return'';return `<div class="fc-dv-table-wrap"><table class="fc-dv-table"><thead>${cols.length?`<tr>${cols.map(x=>`<th>${esc(x)}</th>`).join('')}</tr>`:''}</thead><tbody>${rows.map(r=>`<tr>${(Array.isArray(r)?r:[]).map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
  function notesHtml(items,cls='fc-dv-note'){return Array.isArray(items)?items.filter(Boolean).map(x=>`<div class="${cls}">${esc(x)}</div>`).join(''):''}
  function sectionHtml(s){if(!s||typeof s!=='object')return'';let out='';if(s.heading)out+=`<h3>${esc(s.heading)}</h3>`;if(s.paragraph)out+=`<p>${esc(s.paragraph)}</p>`;if(s.highlight)out+=`<div class="fc-dv-callout">${esc(s.highlight)}</div>`;if(s.important)out+=`<div class="fc-dv-callout important">${esc(s.important)}</div>`;if(s.table)out+=tableHtml(s.table);return out}
  function readableHtml(content){if(!content||typeof content!=='object')return'<div class="fc-dv-empty">Keine Lesefassung vorhanden.</div>';let body=`<article class="fc-dv-readable"><div class="fc-dv-readable-head"><span>LESefassung</span><h2>${esc(content.title||'Dokument')}</h2>${content.subtitle?`<p>${esc(content.subtitle)}</p>`:''}</div>`;if(content.kind==='schedule'){body+=tableHtml({columns:content.columns,rows:content.rows});body+=notesHtml(content.notes);if(Array.isArray(content.legend)&&content.legend.length)body+=`<div class="fc-dv-legend"><b>Legende</b>${content.legend.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`}else{body+=(Array.isArray(content.sections)?content.sections:[]).map(sectionHtml).join('')}return body+'<div class="fc-dv-source-note">Die Lesefassung dient der schnellen Übersicht. Das unveränderte Original bleibt jederzeit verfügbar.</div></article>'}
  function createShell(title='Dokument'){document.getElementById(MODAL)?.remove();const m=document.createElement('div');m.id=MODAL;m.className='fc-dv-modal';m.innerHTML=`<section class="fc-dv-shell" role="dialog" aria-modal="true" aria-label="Dokument"><header class="fc-dv-head"><div><small>DOKUMENT</small><h1>${esc(title)}</h1></div><button type="button" class="fc-dv-close" aria-label="Schliessen">×</button></header><div class="fc-dv-tabs"><button type="button" data-mode="readable" class="active">Lesefassung</button><button type="button" data-mode="original">Original</button></div><div class="fc-dv-toolbar" hidden><button type="button" data-zoom-out aria-label="Verkleinern">−</button><span data-zoom-label>100 %</span><button type="button" data-zoom-in aria-label="Vergrössern">＋</button><button type="button" data-fit>Einpassen</button></div><main class="fc-dv-body"><div class="fc-dv-loading">Dokument wird vorbereitet …</div></main></section>`;m.querySelector('.fc-dv-close').onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()};document.body.appendChild(m);return m}
  async function open(id){id=String(id||'').trim();if(!id)return;const m=createShell(),body=m.querySelector('.fc-dv-body'),tabs=[...m.querySelectorAll('[data-mode]')],toolbar=m.querySelector('.fc-dv-toolbar');let readable=null,original=null,zoom=1,mode='readable';
    function title(s){const h=m.querySelector('.fc-dv-head h1');if(h&&s)h.textContent=String(s)}
    function active(k){mode=k;tabs.forEach(b=>b.classList.toggle('active',b.dataset.mode===k));toolbar.hidden=k!=='original'||String(original?.mimeType||'').includes('pdf')}
    function applyZoom(){zoom=Math.max(1,Math.min(3,zoom));const img=body.querySelector('.fc-dv-original-img');if(img){img.style.width=Math.round(zoom*100)+'%';img.style.maxWidth='none'}const l=m.querySelector('[data-zoom-label]');if(l)l.textContent=Math.round(zoom*100)+' %'}
    async function loadReadable(){if(readable)return readable;const r=await request('/readable?id='+encodeURIComponent(id));if(!r.ok)throw new Error('no readable');const j=await r.json();if(!j?.content)throw new Error('no readable');readable=j;title(j.title);return j}
    async function loadOriginal(){if(original)return original;const r=await request('/file?id='+encodeURIComponent(id)+'&json=1');if(!r.ok)throw new Error('original failed');const j=await r.json();if(!j?.url)throw new Error('original failed');original=j;title(j.title);return j}
    async function showReadable(){active('readable');body.innerHTML='<div class="fc-dv-loading">Lesefassung wird geladen …</div>';try{const j=await loadReadable();if(mode!=='readable')return;body.innerHTML=readableHtml(j.content);body.scrollTop=0}catch(e){tabs.find(b=>b.dataset.mode==='readable')?.setAttribute('disabled','');await showOriginal()}}
    async function showOriginal(){active('original');body.innerHTML='<div class="fc-dv-loading">Original wird geladen …</div>';try{const j=await loadOriginal();if(mode!=='original')return;const mime=String(j.mimeType||'');if(mime.includes('pdf')){body.innerHTML=`<iframe class="fc-dv-pdf" src="${esc(j.url)}" title="Original PDF"></iframe>`}else{body.innerHTML=`<div class="fc-dv-original-stage"><img class="fc-dv-original-img" src="${esc(j.url)}" alt="${esc(j.title||'Originaldokument')}"></div>`;zoom=1;applyZoom()}body.scrollTop=0}catch(e){body.innerHTML='<div class="fc-dv-empty">Das Original konnte nicht geladen werden.</div>'}}
    tabs.forEach(b=>b.onclick=()=>b.dataset.mode==='original'?showOriginal():showReadable());m.querySelector('[data-zoom-in]').onclick=()=>{zoom+=.25;applyZoom()};m.querySelector('[data-zoom-out]').onclick=()=>{zoom-=.25;applyZoom()};m.querySelector('[data-fit]').onclick=()=>{zoom=1;applyZoom()};
    await showReadable();return m
  }
  window.fcOpenOriginal=open;
  window.__fcDocumentViewerHealth={version:VERSION,v9Native:true,readable:true,original:true,zoom:true,legacyWrapper:false};
})();