/* Familienzentrale V9.56 · Familienbudget & Ausgaben · additive feature module */
(()=>{
'use strict';
if(window.__fcFamilyBudgetInstalled)return;window.__fcFamilyBudgetInstalled=true;
const VERSION='9.56.0';
const EXPENSE_CATS=['Lebensmittel','Haushalt','Kinder','Schule','Gesundheit','Mobilität','Freizeit','Kleidung','Wohnen','Versicherungen','Sonstiges'];
const INCOME_CATS=['Lohn','Unterhalt','Zulage','Rückerstattung','Sonstiges'];
const ICONS={Lebensmittel:'🥕',Haushalt:'🏠',Kinder:'👦',Schule:'🎒',Gesundheit:'🩺',Mobilität:'🚗',Freizeit:'🎟️',Kleidung:'👕',Wohnen:'🔑',Versicherungen:'🛡️',Sonstiges:'📦',Lohn:'💼',Unterhalt:'🤝',Zulage:'➕',Rückerstattung:'↩️'};
const D=()=>{try{return typeof data!=='undefined'&&data?data:{}}catch(_){return{}}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const monthOf=(v=today())=>String(v).slice(0,7);
const money=n=>new Intl.NumberFormat('de-CH',{style:'currency',currency:'CHF',minimumFractionDigits:2}).format(Number(n||0));
const num=v=>{const n=Number(String(v??'').replace(/[^0-9,.-]/g,'').replace(',','.'));return Number.isFinite(n)?Math.round(n*100)/100:0};
function persist(){try{if(typeof save==='function')save()}catch(e){console.error('fc_budget_save',e)}try{window.__fcV9?.invalidate?.(['more'])}catch(_){}}
function store(create=true){const d=D();if(!d.finance&&create)d.finance={version:1,transactions:{},monthlyBudgets:{}};if(d.finance){if(!d.finance.transactions||typeof d.finance.transactions!=='object'||Array.isArray(d.finance.transactions))d.finance.transactions={};if(!d.finance.monthlyBudgets||typeof d.finance.monthlyBudgets!=='object'||Array.isArray(d.finance.monthlyBudgets))d.finance.monthlyBudgets={};}return d.finance||null}
function people(){return (D().people||[]).map(p=>({id:String(p.id),name:String(p.name||p.id)}))}
function personName(id){if(!id||id==='all')return'Familie';return people().find(p=>p.id===String(id))?.name||'Familie'}
function txs(){return Object.values(store(false)?.transactions||{}).filter(x=>x&&!x.archived).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))||String(b.createdAt||'').localeCompare(String(a.createdAt||'')))}
let selectedMonth=monthOf(),filterType='all',filterPerson='all';
function monthTx(){return txs().filter(x=>monthOf(x.date)===selectedMonth&&(filterType==='all'||x.type===filterType)&&(filterPerson==='all'||String(x.personId||'all')===filterPerson))}
function totals(list=monthTx()){let income=0,expense=0;for(const x of list){if(x.type==='income')income+=Number(x.amount||0);else expense+=Number(x.amount||0)}return{income,expense,balance:income-expense}}
function budget(){return Number(store(false)?.monthlyBudgets?.[selectedMonth]?.amount||0)}
function expenseTotal(){return txs().filter(x=>monthOf(x.date)===selectedMonth&&x.type==='expense').reduce((s,x)=>s+Number(x.amount||0),0)}
function monthLabel(){const d=new Date(`${selectedMonth}-01T12:00:00`);return new Intl.DateTimeFormat('de-CH',{month:'long',year:'numeric'}).format(d)}
function shiftMonth(n){const d=new Date(`${selectedMonth}-01T12:00:00`);d.setMonth(d.getMonth()+n);selectedMonth=monthOf(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`)}
function tile(){const root=document.getElementById('more');if(!root)return;const old=root.querySelector('[data-fc-budget]');const t=totals(txs().filter(x=>monthOf(x.date)===monthOf()));if(old){old.querySelector('span').textContent=`${money(t.expense)} Ausgaben`;return}const grid=root.querySelector('.fc9-more-grid');if(!grid)return;const b=document.createElement('button');b.type='button';b.className='fc9-tile';b.dataset.fcBudget='1';b.innerHTML=`<i>💳</i><b>Budget & Ausgaben</b><span>${money(t.expense)} Ausgaben</span>`;b.onclick=open;const recipes=grid.querySelector('[data-fc-recipes]');recipes?.after(b)||grid.appendChild(b);document.documentElement.dataset.fcFamilyBudget='v56'}
function close(){document.getElementById('fcBudgetModal')?.remove();document.getElementById('fcBudgetEdit')?.remove()}
function shell(){close();const m=document.createElement('div');m.id='fcBudgetModal';m.className='fc-budget-modal';m.innerHTML=`<section class="fc-budget-shell" role="dialog" aria-modal="true" aria-label="Familienbudget und Ausgaben"><header class="fc-budget-head"><div><small>FAMILY COMMAND</small><h2>Budget & Ausgaben</h2><p>Monat im Blick – Einnahmen, Ausgaben und Budget.</p></div><button type="button" class="fc-budget-close" aria-label="Schließen">×</button></header><main class="fc-budget-main"></main></section>`;m.querySelector('.fc-budget-close').onclick=close;m.onclick=e=>{if(e.target===m)close()};document.body.appendChild(m);render();return m}
function progress(){const b=budget(),spent=expenseTotal(),pct=b>0?Math.min(100,spent/b*100):0;return `<section class="fc-budget-budget"><div><small>MONATSBUDGET</small><b>${b?money(b):'Noch nicht gesetzt'}</b><span>${money(spent)} ausgegeben${b?` · ${Math.max(0,100-Math.round(pct))}% übrig`:''}</span></div><button type="button" data-edit-budget>${b?'Ändern':'Budget setzen'}</button>${b?`<div class="fc-budget-progress"><i style="width:${pct}%"></i></div>`:''}</section>`}
function filters(){const persons=['<option value="all">Alle Personen</option>',...people().map(p=>`<option value="${esc(p.id)}" ${filterPerson===p.id?'selected':''}>${esc(p.name)}</option>`)].join('');return `<div class="fc-budget-filters"><select data-filter-type><option value="all" ${filterType==='all'?'selected':''}>Alle</option><option value="expense" ${filterType==='expense'?'selected':''}>Ausgaben</option><option value="income" ${filterType==='income'?'selected':''}>Einnahmen</option></select><select data-filter-person>${persons}</select></div>`}
function row(x){return `<button type="button" class="fc-budget-row" data-budget-id="${esc(x.id)}"><span class="fc-budget-icon">${ICONS[x.category]||'📦'}</span><span class="fc-budget-copy"><b>${esc(x.title||x.category)}</b><small>${esc([x.category,personName(x.personId),x.note].filter(Boolean).join(' · '))}</small></span><span class="fc-budget-amount ${x.type==='income'?'income':''}">${x.type==='income'?'+':'−'} ${money(x.amount)}</span><time>${esc(String(x.date||'').slice(8,10)+'.'+String(x.date||'').slice(5,7)+'.')}</time></button>`}
function render(){const m=document.getElementById('fcBudgetModal');if(!m)return;const list=monthTx(),t=totals(list);m.querySelector('.fc-budget-main').innerHTML=`<div class="fc-budget-monthbar"><button type="button" data-month="-1" aria-label="Vorheriger Monat">‹</button><div><small>MONAT</small><b>${esc(monthLabel())}</b></div><button type="button" data-month="1" aria-label="Nächster Monat">›</button></div><section class="fc-budget-summary"><div><small>EINNAHMEN</small><b class="income">${money(t.income)}</b></div><div><small>AUSGABEN</small><b>${money(t.expense)}</b></div><div><small>SALDO</small><b class="${t.balance>=0?'income':''}">${money(t.balance)}</b></div></section>${progress()}<div class="fc-budget-actions"><button type="button" data-add-expense>− Ausgabe</button><button type="button" class="primary" data-add-income>＋ Einnahme</button></div>${filters()}<section class="fc-budget-list"><header><h3>Buchungen</h3><span>${list.length}</span></header>${list.length?list.map(row).join(''):'<div class="fc-budget-empty"><strong>Noch keine Buchungen</strong><span>Füge die erste Ausgabe oder Einnahme hinzu.</span></div>'}</section>`;bind(m);tile()}
function bind(root){root.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{shiftMonth(Number(b.dataset.month));render()});root.querySelector('[data-filter-type]').onchange=e=>{filterType=e.target.value;render()};root.querySelector('[data-filter-person]').onchange=e=>{filterPerson=e.target.value;render()};root.querySelector('[data-add-expense]').onclick=()=>editTx('',{type:'expense'});root.querySelector('[data-add-income]').onclick=()=>editTx('',{type:'income'});root.querySelector('[data-edit-budget]').onclick=editBudget;root.querySelectorAll('[data-budget-id]').forEach(b=>b.onclick=()=>editTx(b.dataset.budgetId))}
function editBudget(){const current=budget();form('Monatsbudget',`<label>BETRAG (CHF)<input id="fcBudgetAmount" inputmode="decimal" value="${current||''}" placeholder="z. B. 1800"></label>`,{save:x=>{const amount=num(x.querySelector('#fcBudgetAmount').value);const s=store();if(amount<=0)delete s.monthlyBudgets[selectedMonth];else s.monthlyBudgets[selectedMonth]={month:selectedMonth,amount,updatedAt:new Date().toISOString()};persist();return true}})}
function form(title,body,{save:saveFn,remove=null}={}){document.getElementById('fcBudgetEdit')?.remove();const x=document.createElement('div');x.id='fcBudgetEdit';x.className='fc-budget-edit-modal';x.innerHTML=`<section class="fc-budget-edit-sheet"><header><h3>${esc(title)}</h3><button type="button" data-close>×</button></header><div class="fc-budget-form">${body}</div><footer>${remove?'<button type="button" class="danger" data-remove>Löschen</button>':'<span></span>'}<button type="button" data-cancel>Abbrechen</button><button type="button" class="primary" data-save>Speichern</button></footer></section>`;const done=()=>x.remove();x.querySelector('[data-close]').onclick=done;x.querySelector('[data-cancel]').onclick=done;x.onclick=e=>{if(e.target===x)done()};x.querySelector('[data-save]').onclick=()=>{if(saveFn?.(x)!==false){done();render()}};x.querySelector('[data-remove]')?.addEventListener('click',()=>{if(confirm('Buchung wirklich löschen?')){remove?.();done();render()}});document.body.appendChild(x);setTimeout(()=>x.querySelector('input,select')?.focus(),30)}
function editTx(id='',defaults={}){const s=store(),existing=id?s.transactions[id]:null,x=existing||{type:defaults.type||'expense',date:selectedMonth===monthOf()?today():`${selectedMonth}-01`,title:'',amount:'',category:'',personId:'all',note:''};const cats=x.type==='income'?INCOME_CATS:EXPENSE_CATS;const persons=['<option value="all">Familie</option>',...people().map(p=>`<option value="${esc(p.id)}" ${String(x.personId)===p.id?'selected':''}>${esc(p.name)}</option>`)].join('');form(existing?'Buchung bearbeiten':x.type==='income'?'Einnahme hinzufügen':'Ausgabe hinzufügen',`<div class="fc-budget-form-grid"><label>ART<select id="fcBudgetType"><option value="expense" ${x.type==='expense'?'selected':''}>Ausgabe</option><option value="income" ${x.type==='income'?'selected':''}>Einnahme</option></select></label><label>DATUM<input id="fcBudgetDate" type="date" value="${esc(x.date)}"></label></div><label>BEZEICHNUNG<input id="fcBudgetTitle" maxlength="80" value="${esc(x.title||'')}" placeholder="z. B. Wocheneinkauf"></label><div class="fc-budget-form-grid"><label>BETRAG (CHF)<input id="fcBudgetValue" inputmode="decimal" value="${esc(x.amount||'')}" placeholder="0.00"></label><label>KATEGORIE<select id="fcBudgetCat">${cats.map(c=>`<option ${c===(x.category||cats[0])?'selected':''}>${esc(c)}</option>`).join('')}</select></label></div><label>FÜR WEN?<select id="fcBudgetPerson">${persons}</select></label><label>NOTIZ<textarea id="fcBudgetNote" maxlength="180">${esc(x.note||'')}</textarea></label>`,{save:m=>{const amount=num(m.querySelector('#fcBudgetValue').value),title=m.querySelector('#fcBudgetTitle').value.trim(),date=m.querySelector('#fcBudgetDate').value,type=m.querySelector('#fcBudgetType').value;if(amount<=0||!date)return false;const row=existing||{id:uid('finance'),createdAt:new Date().toISOString()};row.type=type;row.date=date;row.title=title||m.querySelector('#fcBudgetCat').value;row.amount=amount;row.category=m.querySelector('#fcBudgetCat').value;row.personId=m.querySelector('#fcBudgetPerson').value;row.note=m.querySelector('#fcBudgetNote').value.trim();row.updatedAt=new Date().toISOString();s.transactions[row.id]=row;selectedMonth=monthOf(date);persist();return true},remove:existing?()=>{existing.archived=true;existing.updatedAt=new Date().toISOString();persist()}:null});const modal=document.getElementById('fcBudgetEdit'),typeSel=modal?.querySelector('#fcBudgetType');if(typeSel&&!existing)typeSel.onchange=()=>{const type=typeSel.value,cats2=type==='income'?INCOME_CATS:EXPENSE_CATS;modal.querySelector('#fcBudgetCat').innerHTML=cats2.map(c=>`<option>${esc(c)}</option>`).join('')}}
function open(){selectedMonth=monthOf();filterType='all';filterPerson='all';shell()}
function install(){const root=document.getElementById('more');if(!root){setTimeout(install,60);return}const obs=new MutationObserver(()=>{clearTimeout(obs._t);obs._t=setTimeout(tile,25)});obs.observe(root,{childList:true,subtree:true});tile();document.querySelector('.fc9-nav button[data-screen="more"]')?.addEventListener('click',()=>setTimeout(tile,25));document.documentElement.dataset.fcFamilyBudget='v56'}
window.fcOpenFamilyBudget=open;window.__fcFamilyBudget={version:VERSION,open,render,store,health:()=>({version:VERSION,transactions:txs().length,month:selectedMonth,budget:budget(),cloudCompatible:true,objectMergeModel:true,currency:'CHF'})};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();