/* Familienzentrale V9.54 · Mahlzeiten & Wochenmenü · additive feature module */
(()=>{
'use strict';
if(window.__fcMealPlannerInstalled)return;window.__fcMealPlannerInstalled=true;
const VERSION='9.54.0',MEALS=[['breakfast','Frühstück','☕'],['lunch','Mittagessen','🍽️'],['dinner','Abendessen','🌙']];
const CATS=['Lebensmittel','Getränke','Haushalt','Drogerie','Schule','Sonstiges'];
const D=()=>{try{return typeof data!=='undefined'&&data?data:{}}catch(_){return{}}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function dateObj(v){return new Date(String(v)+'T12:00:00')}
function monday(v=new Date()){const d=v instanceof Date?new Date(v):dateObj(v),n=(d.getDay()+6)%7;d.setDate(d.getDate()-n);return d}
function add(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function weekKey(d){return iso(monday(d))}
function fmtDay(d){return new Intl.DateTimeFormat('de-CH',{weekday:'short',day:'numeric',month:'numeric'}).format(d)}
function fmtRange(start){const end=add(start,6),a=new Intl.DateTimeFormat('de-CH',{day:'numeric',month:'short'}).format(start),b=new Intl.DateTimeFormat('de-CH',{day:'numeric',month:'short',year:'numeric'}).format(end);return `${a} – ${b}`}
function persist(){try{if(typeof save==='function')save()}catch(e){console.error('fc_meals_save',e)}try{window.__fcV9?.invalidate?.(['more'])}catch(_){}}
function store(create=true){const d=D();if(!d.meals&&create)d.meals={version:1,weeks:{}};if(d.meals&&(!d.meals.weeks||typeof d.meals.weeks!=='object'||Array.isArray(d.meals.weeks)))d.meals.weeks={};return d.meals||null}
let selectedWeek=weekKey(new Date());
function week(create=true){const s=store(create);if(!s)return null;if(!s.weeks[selectedWeek]&&create)s.weeks[selectedWeek]={id:selectedWeek,createdAt:new Date().toISOString(),days:{}};const w=s.weeks[selectedWeek];if(w&&(!w.days||typeof w.days!=='object'||Array.isArray(w.days)))w.days={};return w||null}
function entry(date,type){return week(false)?.days?.[date]?.[type]||null}
function filledCount(){const w=week(false);if(!w)return 0;let n=0;for(const day of Object.values(w.days||{}))for(const [k] of MEALS)if(day?.[k]?.title)n++;return n}
function tile(){const root=document.getElementById('more');if(!root)return;const old=root.querySelector('[data-fc-meals]');if(old){old.querySelector('span').textContent=`${filledCount()} geplant`;return}const grid=root.querySelector('.fc9-more-grid');if(!grid)return;const b=document.createElement('button');b.type='button';b.className='fc9-tile';b.dataset.fcMeals='1';b.innerHTML=`<i>🍲</i><b>Mahlzeiten</b><span>${filledCount()} geplant</span>`;b.onclick=open;const shopping=grid.querySelector('[data-fc-shopping]');shopping?.after(b)||grid.prepend(b);document.documentElement.dataset.fcMealPlanner='v54'}
function close(){document.getElementById('fcMealModal')?.remove();document.getElementById('fcMealEdit')?.remove()}
function shell(){close();const m=document.createElement('div');m.id='fcMealModal';m.className='fc-meal-modal';m.innerHTML=`<section class="fc-meal-shell" role="dialog" aria-modal="true" aria-label="Mahlzeiten und Wochenmenü"><header class="fc-meal-head"><div><small>FAMILY COMMAND</small><h2>Mahlzeiten & Wochenmenü</h2><p>Die Woche planen und Zutaten direkt einkaufen.</p></div><button type="button" class="fc-meal-close" aria-label="Schließen">×</button></header><main class="fc-meal-main"></main></section>`;m.querySelector('.fc-meal-close').onclick=close;m.onclick=e=>{if(e.target===m)close()};document.body.appendChild(m);render();return m}
function mealCard(date,type,label,icon){const x=entry(date,type);return `<button type="button" class="fc-meal-card ${x?.title?'filled':''}" data-meal-date="${date}" data-meal-type="${type}"><span class="fc-meal-icon">${icon}</span><span class="fc-meal-copy"><small>${label}</small><b>${esc(x?.title||'Planen')}</b>${x?.note?`<em>${esc(x.note)}</em>`:''}</span><span class="fc-meal-arrow">›</span></button>`}
function render(){const m=document.getElementById('fcMealModal');if(!m)return;const start=dateObj(selectedWeek),days=Array.from({length:7},(_,i)=>add(start,i)),main=m.querySelector('.fc-meal-main');main.innerHTML=`<div class="fc-meal-weekbar"><button type="button" data-week="-1" aria-label="Vorherige Woche">‹</button><div><small>WOCHENMENÜ</small><b>${fmtRange(start)}</b></div><button type="button" data-week="1" aria-label="Nächste Woche">›</button></div><div class="fc-meal-days">${days.map(d=>{const k=iso(d),today=k===iso(new Date());return `<section class="fc-meal-day ${today?'today':''}"><header><div><small>${today?'HEUTE':'TAG'}</small><h3>${fmtDay(d)}</h3></div><span>${MEALS.filter(([t])=>entry(k,t)?.title).length}/3</span></header><div>${MEALS.map(([t,l,i])=>mealCard(k,t,l,i)).join('')}</div></section>`}).join('')}</div>`;main.querySelectorAll('[data-week]').forEach(b=>b.onclick=()=>{selectedWeek=weekKey(add(start,Number(b.dataset.week)*7));render();tile()});main.querySelectorAll('[data-meal-date]').forEach(b=>b.onclick=()=>editMeal(b.dataset.mealDate,b.dataset.mealType));tile()}
function ingredients(x){return Array.isArray(x?.ingredients)?x.ingredients.filter(i=>i&&String(i.name||'').trim()):[]}
function ingredientRows(x){const rows=ingredients(x);return `<div id="fcMealIngredients">${rows.map((r,i)=>ingredientRow(r,i)).join('')}</div><button type="button" class="fc-meal-add-ing" data-add-ing>＋ Zutat</button>`}
function ingredientRow(r={},i=0){return `<div class="fc-meal-ing" data-ing-row><input data-ing-name maxlength="70" placeholder="Zutat" value="${esc(r.name||'')}"><input data-ing-qty maxlength="24" placeholder="Menge" value="${esc(r.quantity||'')}"><select data-ing-cat>${CATS.map(c=>`<option ${c===(r.category||'Lebensmittel')?'selected':''}>${c}</option>`).join('')}</select><button type="button" data-remove-ing aria-label="Zutat entfernen">×</button></div>`}
function editMeal(date,type){const [_,label]=MEALS.find(x=>x[0]===type)||[type,type],existing=entry(date,type),x=existing||{title:'',note:'',ingredients:[]};document.getElementById('fcMealEdit')?.remove();const e=document.createElement('div');e.id='fcMealEdit';e.className='fc-meal-edit-modal';e.innerHTML=`<section class="fc-meal-edit-sheet"><header><div><small>${esc(fmtDay(dateObj(date)))} · ${esc(label)}</small><h3>${existing?'Mahlzeit bearbeiten':'Mahlzeit planen'}</h3></div><button type="button" data-close>×</button></header><div class="fc-meal-form"><label>GERICHT<input id="fcMealTitle" maxlength="90" value="${esc(x.title||'')}" placeholder="z. B. Spaghetti Bolognese"></label><label>NOTIZ<textarea id="fcMealNote" maxlength="240" placeholder="Optional">${esc(x.note||'')}</textarea></label><div class="fc-meal-ing-head"><b>Zutaten</b><span>Optional</span></div>${ingredientRows(x)}</div><footer>${existing?'<button type="button" class="danger" data-delete>Löschen</button>':'<span></span>'}${existing&&ingredients(x).length?'<button type="button" data-shop>🛒 Zur Einkaufsliste</button>':''}<button type="button" data-cancel>Abbrechen</button><button type="button" class="primary" data-save>Speichern</button></footer></section>`;const done=()=>e.remove();e.querySelector('[data-close]').onclick=done;e.querySelector('[data-cancel]').onclick=done;e.onclick=v=>{if(v.target===e)done()};e.querySelector('[data-add-ing]').onclick=()=>{e.querySelector('#fcMealIngredients').insertAdjacentHTML('beforeend',ingredientRow());bindIngredientRemovers(e)};bindIngredientRemovers(e);e.querySelector('[data-save]').onclick=()=>{const title=e.querySelector('#fcMealTitle').value.trim();if(!title)return;const w=week(true);if(!w.days[date])w.days[date]={};const now=new Date().toISOString(),row=existing||{id:uid('meal'),createdAt:now};row.title=title;row.note=e.querySelector('#fcMealNote').value.trim();row.ingredients=readIngredients(e);row.updatedAt=now;w.days[date][type]=row;w.updatedAt=now;persist();done();render()};e.querySelector('[data-delete]')?.addEventListener('click',()=>{if(!confirm('Mahlzeit wirklich löschen?'))return;const w=week(false);if(w?.days?.[date])delete w.days[date][type];persist();done();render()});e.querySelector('[data-shop]')?.addEventListener('click',()=>{const out=addToShopping(existing);if(out.added||out.skipped){announce(`${out.added} Zutat${out.added===1?'':'en'} hinzugefügt${out.skipped?` · ${out.skipped} bereits vorhanden`:''}`);done();render()}});document.body.appendChild(e);setTimeout(()=>e.querySelector('#fcMealTitle')?.focus(),30)}
function bindIngredientRemovers(root){root.querySelectorAll('[data-remove-ing]').forEach(b=>b.onclick=()=>b.closest('[data-ing-row]')?.remove())}
function readIngredients(root){return [...root.querySelectorAll('[data-ing-row]')].map(r=>({name:r.querySelector('[data-ing-name]').value.trim(),quantity:r.querySelector('[data-ing-qty]').value.trim(),category:r.querySelector('[data-ing-cat]').value})).filter(r=>r.name)}
function shoppingList(){const api=window.__fcShoppingLists,s=api?.store?.();if(!s)return null;let l=s.lists?.[s.activeListId];if(!l||l.archived)l=Object.values(s.lists||{}).find(x=>x&&!x.archived);return l||null}
function addToShopping(meal){const l=shoppingList();if(!l){announce('Einkaufsliste ist noch nicht bereit.');return{added:0,skipped:0}}if(!l.items||typeof l.items!=='object')l.items={};let added=0,skipped=0,order=Math.max(0,...Object.values(l.items).map(x=>Number(x?.order||0)));for(const ing of ingredients(meal)){const name=ing.name.trim(),same=Object.values(l.items).find(x=>x&&!x.archived&&!x.done&&String(x.title||'').trim().toLowerCase()===name.toLowerCase());if(same){skipped++;continue}order+=10;const id=uid('item'),now=new Date().toISOString();l.items[id]={id,title:name,quantity:ing.quantity||'',category:ing.category||'Lebensmittel',personId:'all',done:false,order,createdAt:now,updatedAt:now,source:'meal-planner',sourceMealId:meal.id};added++}if(added){l.updatedAt=new Date().toISOString();persist();try{window.__fcShoppingLists?.render?.()}catch(_){}}return{added,skipped}}
function announce(msg){try{if(typeof toast==='function')toast(msg);else{const t=document.getElementById('toast');if(t){t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}}}catch(_){}}
function open(){selectedWeek=weekKey(new Date());shell()}
function install(){const root=document.getElementById('more');if(!root){setTimeout(install,60);return}const obs=new MutationObserver(()=>{clearTimeout(obs._t);obs._t=setTimeout(tile,25)});obs.observe(root,{childList:true,subtree:true});tile();document.querySelector('.fc9-nav button[data-screen="more"]')?.addEventListener('click',()=>setTimeout(tile,30));document.documentElement.dataset.fcMealPlanner='v54'}
window.fcOpenMealPlanner=open;window.__fcMealPlanner={version:VERSION,open,render,store,addToShopping,health:()=>({version:VERSION,week:selectedWeek,planned:filledCount(),shoppingIntegration:!!window.__fcShoppingLists,cloudCompatible:true,objectMergeModel:true})};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();