/* Family Command · Pendenzen · V8.5 lean */
(()=>{
  'use strict';
  if(window.__fcPendenciesV85)return;window.__fcPendenciesV85=true;if(typeof data==='undefined')return;if(!Array.isArray(data.pendencies))data.pendencies=[];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const open=()=>data.pendencies.filter(x=>!x.done),money=x=>Number(x||0).toFixed(2);
  function persist(){try{if(typeof save==='function')save()}catch(e){}try{window.__fcV8Shell?.invalidate?.(['more'])}catch(e){}}
  function refresh(){try{if(document.getElementById('more')?.classList.contains('active')){window.__fcV8Shell?.invalidate?.(['more']);window.__fcV8Shell?.render?.('more')}}catch(e){}}
  window.fcTogglePendency=function(id,on){const x=data.pendencies.find(p=>String(p.id)===String(id));if(!x)return;x.done=!!on;x.doneAt=on?new Date().toISOString():null;persist();refresh();try{toast(on?'Pendenz erledigt':'Pendenz wieder geöffnet')}catch(e){}};
  window.fcDeletePendency=function(id){if(!confirm('Pendenz wirklich löschen?'))return;data.pendencies=data.pendencies.filter(p=>String(p.id)!==String(id));persist();refresh()};
  window.fcOpenAddPendency=function(){document.getElementById('fcPendModal')?.remove();const m=document.createElement('div');m.id='fcPendModal';m.className='fcp-modal';m.innerHTML='<div class="fcp-sheet"><div class="fcp-head"><div><small>NEU</small><h3>Pendenz hinzufügen</h3></div><button type="button">×</button></div><label>TITEL</label><input id="fcpTitle" placeholder="z. B. Rechnung zurückfordern"><label>BETRAG <span>optional</span></label><input id="fcpAmount" inputmode="decimal" placeholder="0.00"><label>NOTIZ <span>optional</span></label><textarea id="fcpNote"></textarea><button type="button" class="fcp-save">Speichern</button></div>';const close=()=>m.remove();m.querySelector('.fcp-head button').onclick=close;m.onclick=e=>{if(e.target===m)close()};m.querySelector('.fcp-save').onclick=()=>{const title=(m.querySelector('#fcpTitle').value||'').trim(),raw=(m.querySelector('#fcpAmount').value||'').trim().replace(',','.'),amount=raw?Number(raw):0,note=(m.querySelector('#fcpNote').value||'').trim();if(!title)return;if(raw&&!Number.isFinite(amount))return;data.pendencies.push({id:'pend-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),personId:'oli',title,amount:Number.isFinite(amount)?amount:0,currency:'CHF',note,done:false,createdAt:new Date().toISOString()});persist();close();refresh()};document.body.appendChild(m);setTimeout(()=>m.querySelector('#fcpTitle')?.focus(),40)};
  function row(x){const id=JSON.stringify(String(x.id));return `<div class="fcp-row ${x.done?'done':''}"><label class="fcp-check"><input type="checkbox" ${x.done?'checked':''} onchange="fcTogglePendency(${id},this.checked)"><span></span></label><div class="fcp-main"><div class="fcp-title"><b>${esc(x.title)}</b>${Number(x.amount)>0?`<strong>${esc(x.currency||'CHF')} ${money(x.amount)}</strong>`:''}</div>${x.note?`<p>${esc(x.note)}</p>`:''}</div><button type="button" class="fcp-del" onclick="fcDeletePendency(${id})">Löschen</button></div>`}
  function injectMore(){const root=document.getElementById('more');if(!root)return;root.querySelector('.fcp-v85-box')?.remove();const page=root.querySelector('.v6-page')||root,group=document.createElement('section');group.className='v6-more-group fcp-v85-box';const list=open();group.innerHTML=`<h2>Pendenzen</h2><div class="v6-card fcp-v85-list"><div class="fcp-v85-head"><span>${list.length} offen</span><button type="button" onclick="fcOpenAddPendency()">＋ Neu</button></div>${list.length?list.map(row).join(''):'<div class="fcp-empty">Keine offenen Pendenzen.</div>'}</div>`;const groups=page.querySelector('.v6-more-groups');groups?groups.prepend(group):page.appendChild(group)}
  if(typeof window.renderMore==='function'){const raw=window.renderMore;const w=function(...a){const r=raw.apply(this,a);if(r&&typeof r.then==='function')return r.then(v=>{injectMore();return v});injectMore();return r};window.renderMore=w;try{renderMore=w}catch(e){}}
  if(!document.getElementById('fc-pendencies-v85-style')){const s=document.createElement('style');s.id='fc-pendencies-v85-style';s.textContent='.fcp-v85-list{overflow:hidden}.fcp-v85-head{display:flex;justify-content:space-between;align-items:center;padding:9px 10px;border-bottom:1px solid #e4e8ef;color:#7b879b;font-size:9px}.fcp-v85-head button{border:0;background:#eef0ff;color:#5268ff;border-radius:9px;padding:7px 9px;font-weight:800}.fcp-row{display:grid;grid-template-columns:28px minmax(0,1fr) auto;gap:8px;align-items:start;padding:10px;border-bottom:1px solid #e8ecf2}.fcp-row:last-child{border-bottom:0}.fcp-check input{position:absolute;opacity:0}.fcp-check span{display:block;width:22px;height:22px;border:2px solid #a4adbb;border-radius:7px;background:#fff}.fcp-check input:checked+span{background:#5268ff;border-color:#5268ff}.fcp-main b{color:#172033;font-size:11px}.fcp-title{display:flex;justify-content:space-between;gap:8px}.fcp-title strong{color:#5268ff;font-size:10px}.fcp-main p{margin:3px 0 0;color:#7b879b;font-size:9px}.fcp-del{border:0;background:none;color:#b54b56;font-size:8px}.fcp-empty{padding:12px;color:#7b879b;font-size:10px}.fcp-modal{position:fixed;inset:0;z-index:100300;background:rgba(15,23,42,.42);display:flex;align-items:flex-end;justify-content:center;padding:12px}.fcp-sheet{width:min(100%,460px);background:#fff;border-radius:22px;padding:15px;color:#172033}.fcp-head{display:flex;justify-content:space-between}.fcp-head h3{margin:3px 0 0}.fcp-head small,.fcp-sheet label{font-size:8px;color:#7b879b;font-weight:900;letter-spacing:.08em}.fcp-head button{width:38px;height:38px;border:0;border-radius:999px;background:#f2f4f8;font-size:20px}.fcp-sheet label{display:block;margin:10px 0 5px}.fcp-sheet input,.fcp-sheet textarea{width:100%;box-sizing:border-box;border:1px solid #dfe5ed;border-radius:11px;padding:10px}.fcp-save{width:100%;min-height:44px;margin-top:12px;border:0;border-radius:11px;background:#5268ff;color:#fff;font-weight:850}';document.head.appendChild(s)}
  window.__fcPendencies={version:5,injectMore,open};
})();
