const FC2_BASE='https://lmrvapstojcecljjdgds.supabase.co/functions/v1/family-command-push3';
let FC2_PUBLIC=null;
async function fc2PublicKey(){if(FC2_PUBLIC)return FC2_PUBLIC;const r=await fetch(FC2_BASE+'/key',{cache:'no-store'}),j=await r.json().catch(()=>({}));if(!r.ok||!j.publicKey)throw new Error(j.error||'Push-Schlüssel konnte nicht geladen werden');FC2_PUBLIC=j.publicKey;return FC2_PUBLIC}
async function fc2Post(path,payload){const r=await fetch(FC2_BASE+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'HTTP '+r.status);return j}
function fc2LocalTime(){const d=new Date();return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
enablePush=async function(){try{if(isIOS()&&!standalone())return alert('Auf dem iPhone zuerst Safari → Teilen → Zum Home-Bildschirm. Danach Family Command von dort öffnen und Push nochmals einrichten.');const r=await reg(),perm=await Notification.requestPermission();if(perm!=='granted')throw new Error('Mitteilungen wurden nicht erlaubt');let s=await r.pushManager.getSubscription(),fresh=false;const publicKey=await fc2PublicKey();if(s){const old=s.options&&s.options.applicationServerKey?b64(new Uint8Array(s.options.applicationServerKey)):'';if(old&&old!==publicKey){await s.unsubscribe();s=null}}if(!s){s=await r.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key(publicKey)});fresh=true}const d=device(),payload={deviceId:d.id,deviceToken:d.token,subscription:s.toJSON(),state:pushSnapshot(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'Europe/Zurich',morningTime:'06:30',eveningTime:'19:00'};await fc2Post('/subscribe',payload);const now=fc2LocalTime(),catchUp=fresh&&now>='06:30'&&now<'12:00';if(catchUp){try{await fc2Post('/test',{deviceId:d.id,deviceToken:d.token})}catch(e){console.warn('fc_push_catchup',e)}}setPushStatus('Aktiv · 06:30 Tagesübersicht · 19:00 Vorschau für morgen');toast(catchUp?'Push aktiviert · heutige Übersicht gesendet':'Push aktiviert')}catch(e){setPushStatus('Fehler: '+e.message)}};
syncPush=async function(){try{if(!('Notification'in window)||Notification.permission!=='granted')return;const s=await pushSub();if(!s)return;const d=device();await fc2Post('/sync',{deviceId:d.id,deviceToken:d.token,state:pushSnapshot(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'Europe/Zurich',morningTime:'06:30',eveningTime:'19:00'})}catch(e){}};
testPush=async function(){try{const s=await pushSub();if(!s)return setPushStatus('Bitte Push zuerst einrichten.');await syncPush();const d=device();await fc2Post('/test',{deviceId:d.id,deviceToken:d.token});setPushStatus('Test-Push wurde gesendet.')}catch(e){setPushStatus('Test fehlgeschlagen: '+e.message)}};
setupPushUI=async function(){const a=document.getElementById('pushEnable'),b=document.getElementById('pushTest');if(!a)return;a.onclick=enablePush;b.onclick=testPush;if(!('PushManager'in window)||!('Notification'in window))return setPushStatus('Dieses Gerät unterstützt Web-Push nicht.');if(isIOS()&&!standalone())return setPushStatus('iPhone: zuerst zum Home-Bildschirm hinzufügen.');try{const s=await pushSub();setPushStatus(s&&Notification.permission==='granted'?'Aktiv · 06:30 Tagesübersicht · 19:00 Vorschau':'Noch nicht eingerichtet.')}catch(e){setPushStatus(e.message)}};
