/* Familienzentrale V9.61.7 · vorhandene Erinnerungen sichtbar machen */
(()=>{
'use strict';
if(window.__fcReminderCenterInstalled)return;
window.__fcReminderCenterInstalled=true;
const VERSION='9.61.7',DAY={1:'Mo',2:'Di',3:'Mi',4:'Do',5:'Fr',6:'Sa',0:'So'};
const D=()=>{try{return typeof data!=='undefined'&&data?data:{}}catch(_){return{}}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function reminders(){return(Array.isArray(D().reminders)?D().reminders:[]).filter(x=>x&&Array.isArray(x.items)&&x.items.length)}
function personName(id){const p=(D().people||[]).find(x=>String(x.id)===String(id));return String(p?.name||id||'Familie')}
function daysLabel(days){const a=[...new Set((Array.isArray(days)?days:[]).map(Number))];if(a.length===5&&[1,2,3,4,5].every(x=>a.includes(x)))return'Mo–Fr';return a.map(x=>DAY[x]||String(x)).join(' · ')||'Nach Bedarf'}
function ensureStyle(){if(document.getElementById('fcReminderCenterStyle'))return;const s=document.createElement('style');s.id='fcReminderCenterStyle';s.textContent=`
.fc-reminder-intro{margin:0 0 12px;color:#64748b;font-size:12px;line-height:1.45}.fc-reminder-list{display:grid;gap:10px;max-height:58vh;overflow:auto;padding:1px}.fc-reminder-group{border:1px solid #dbe5f0;border-radius:16px;background:#fff;padding:13px}.fc-reminder-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:9px}.fc-reminder-head b{color:#17345a;font-size:14px}.fc-reminder-days{display:inline-flex;align-items:center;border-radius:999px;background:#eaf2ff;color:#245eaa;padding:4px 8px;font-size:10px;font-weight:800}.fc-reminder-items{display:flex;flex-wrap:wrap;gap:6px}.fc-reminder-item{display:inline-flex;align-items:center;min-height:30px;border-radius:10px;background:#f2f6fb;color:#334a68;padding:4px 9px;font-size:11px;font-weight:700}.fc-reminder-empty{padding:24px 8px;text-align:center;color:#64748b}.fc-reminder-actions{display:grid;grid-template-columns:1fr auto;gap:8px;margin-top:14px}.fc-reminder-actions button{min-height:44px;border-radius:12px;border:1px solid #d5e0ed;background:#fff;color:#27415f;font-weight:800;padding:0 14px}.fc-reminder-actions .primary{border-color:#246fda;background:#246fda;color:#fff}@media(max-width:520px){.fc-reminder-list{max-height:54vh}.fc-reminder-actions{grid-template-columns:1fr}.fc-reminder-actions button{min-height:48px}}
`;document.head.appendChild(s)}
function close(){document.getElementById('fcReminderCenter')?.remove()}
function open(){ensureStyle();close();const arr=reminders(),m=document.createElement('div');m.id='fcReminderCenter';m.className='fc9-modal';m.innerHTML=`<section class="fc9-sheet" aria-label="Erinnerungen"><div class="fc9-sheet-head"><div><small>FAMILIENZENTRALE</small><h2>Erinnerungen</h2></div><button class="fc9-close" type="button" aria-label="Schließen">×</button></div><p class="fc-reminder-intro">Was an bestimmten Wochentagen für die Kinder bereitliegen oder mitgenommen werden soll.</p><div class="fc-reminder-list">${arr.length?arr.map(r=>`<section class="fc-reminder-group" data-reminder-id="${esc(r.id)}"><div class="fc-reminder-head"><b>${esc(personName(r.personId))}</b><span class="fc-reminder-days">${esc(daysLabel(r.days))}</span></div><div class="fc-reminder-items">${r.items.map(i=>`<span class="fc-reminder-item">${esc(i)}</span>`).join('')}</div></section>`).join(''):'<div class="fc-reminder-empty">Aktuell sind keine festen Mitnehm-Erinnerungen hinterlegt.</div>'}</div><div class="fc-reminder-actions"><button type="button" data-close>Fertig</button><button class="primary" type="button" data-push>Push einrichten</button></div></section>`;m.querySelector('.fc9-close').onclick=close;m.querySelector('[data-close]').onclick=close;m.onclick=e=>{if(e.target===m)close()};m.querySelector('[data-push]').onclick=async()=>{try{await window.__fcLoadExtrasNow?.();if(typeof window.enablePush==='function')await window.enablePush();else if(typeof window.toast==='function')window.toast('Push-Einrichtung wird geladen.')}catch(e){console.error('fc_reminder_push',e)}};document.body.appendChild(m)}
function wire(){const tile=document.querySelector('#more [data-feature="push"]');if(!tile)return false;tile.onclick=open;const sub=tile.querySelector('span');if(sub)sub.textContent=`${reminders().length} Merklisten · Push & Morgenbericht`;document.documentElement.dataset.fcReminderCenter='v9617';return true}
function install(){if(!wire())setTimeout(install,60);const root=document.getElementById('more');if(root)new MutationObserver(()=>setTimeout(wire,20)).observe(root,{childList:true,subtree:true})}
window.fcOpenReminderCenter=open;
window.__fcReminderCenter={version:VERSION,open,health:()=>({version:VERSION,groups:reminders().length,items:reminders().reduce((n,r)=>n+r.items.length,0),readOnlyRules:true,pushSetup:true})};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
