/* Familienzentrale V9.53 · Einkaufen & Listen · additive feature module */
(()=>{
'use strict';
if(window.__fcShoppingListsInstalled)return;window.__fcShoppingListsInstalled=true;
const VERSION='9.53.0';
const CATEGORIES=['Lebensmittel','Getränke','Haushalt','Drogerie','Schule','Sonstiges'];
const ICONS={Lebensmittel:'🥕',Getränke:'🥤',Haushalt:'🏠',Drogerie:'🧴',Schule:'🎒',Sonstiges:'📦'};
const D=()=>{try{return typeof data!=='undefined'&&data?data:{}}catch(_){return{}}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
function persist(){try{if(typeof save==='function')save()}catch(e){console.error('fc_shopping_save',e)}try{window.__fcV9?.invalidate?.(['more'])}catch(_){}}
function store(create=true){const d=D();if(!d.shopping&&create)d.shopping={version:1,activeListId:'',lists:{}};if(d.shopping&&(!d.shopping.lists||typeof d.shopping.lists!=='object'||Array.isArray(d.shopping.lists)))d.shopping.lists={};return d.shopping||null}
function lists(){const s=store(false);return Object.values(s?.lists||{}).filter(x=>x&&!x.archived).sort((a,b)=>String(a.createdAt||'').localeCompare(String(b.createdAt||'')))}
function ensureDefault(){let s=store(true),arr=lists();if(!arr.length){const id='shopping-default';s.lists[id]={id,title:'Einkauf',createdAt:new Date().toISOString(),archived:false,items:{}};s.activeListId=id;persist();return s.lists[id]}let active=s.lists[s.activeListId];if(!active||active.archived){s.activeListId=arr[0].id;active=arr[0]}return active}
function activeList(){const s=store(false),arr=lists();return (s&&s.lists?.[s.activeListId]&&!s.lists[s.activeListId].archived?s.lists[s.activeListId]:arr[0])||ensureDefault()}
function people(){return (D().people||[]).map(p=>({id:String(p.id),name:String(p.name||p.id),color:p.color||'#74839a'}))}
function personLabel(id){if(!id||id==='all')return'Familie';return people().find(p=>p.id===String(id))?.name||'Familie'}
function items(list){return Object.values(list?.items||{}).filter(x=>x&&!x.archived).sort((a,b)=>Number(!!a.done)-Number(!!b.done)||Number(a.order||0)-Number(b.order||0)||String(a.createdAt||'').localeCompare(String(b.createdAt||'')))}
function openCount(list){return items(list).filter(x=>!x.done).length}
function allOpenCount(){return lists().reduce((n,l)=>n+openCount(l),0)}
function categoryGroups(list){const open=items(list).filter(x=>!x.done),out=[];for(const c of CATEGORIES){const rows=open.filter(x=>(x.category||'Sonstiges')===c);if(rows.length)out.push([c,rows])}return out}
function tile(){const root=document.getElementById('more');if(!root)return;const existing=root.querySelector('[data-fc-shopping]');if(existing){const count=existing.querySelector('span');if(count)count.textContent=`${allOpenCount()} offen`;document.documentElement.dataset.fcShoppingLists='v53';return}const grid=root.querySelector('.fc9-more-grid');if(!grid)return;const b=document.createElement('button');b.type='button';b.className='fc9-tile';b.dataset.fcShopping='1';b.innerHTML=`<i>🛒</i><b>Einkaufen & Listen</b><span>${allOpenCount()} offen</span>`;b.onclick=open;grid.prepend(b);document.documentElement.dataset.fcShoppingLists='v53'}
function close(){document.getElementById('fcShoppingModal')?.remove()}
function shell(){close();ensureDefault();const m=document.createElement('div');m.id='fcShoppingModal';m.className='fc-shopping-modal';m.innerHTML=`<section class="fc-shopping-shell" role="dialog" aria-modal="true" aria-label="Einkaufen und Listen"><header class="fc-shopping-head"><div><small>FAMILY COMMAND</small><h2>Einkaufen & Listen</h2><p>Gemeinsam planen, schnell abhaken.</p></div><button type="button" class="fc-shopping-close" aria-label="Schließen">×</button></header><div class="fc-shopping-layout"><aside class="fc-shopping-sidebar"><div class="fc-shopping-listtabs" role="tablist"></div><button type="button" class="fc-shopping-new-list">＋ Neue Liste</button></aside><main class="fc-shopping-main"></main></div></section>`;m.querySelector('.fc-shopping-close').onclick=close;m.onclick=e=>{if(e.target===m)close()};document.body.appendChild(m);render();return m}
function listTabs(){const s=store(),active=activeList();return lists().map(l=>`<button type="button" role="tab" aria-selected="${l.id===active.id}" class="${l.id===active.id?'active':''}" data-shopping-list="${esc(l.id)}"><span>${esc(l.title)}</span><b>${openCount(l)}</b></button>`).join('')}
function row(x){const meta=[x.quantity?`${x.quantity}`:'',personLabel(x.personId)].filter(Boolean).join(' · ');return `<div class="fc-shopping-item ${x.done?'done':''}" data-shopping-item="${esc(x.id)}"><label class="fc-shopping-check"><input type="checkbox" ${x.done?'checked':''} aria-label="${x.done?'Wieder öffnen':'Erledigen'}"><i></i></label><div class="fc-shopping-copy"><b>${esc(x.title)}</b><span>${esc(meta)}</span></div><button type="button" class="fc-shopping-edit" aria-label="Bearbeiten">›</button></div>`}
function mainHtml(){const l=activeList(),groups=categoryGroups(l),done=items(l).filter(x=>x.done);return `<div class="fc-shopping-title"><div><small>AKTIVE LISTE</small><h3>${esc(l.title)}</h3><p>${openCount(l)} offen${done.length?` · ${done.length} erledigt`:''}</p></div><button type="button" class="fc-shopping-list-menu" aria-label="Liste bearbeiten">•••</button></div><form class="fc-shopping-add"><input id="fcShoppingNewItem" autocomplete="off" placeholder="Was wird gebraucht?" aria-label="Neuer Eintrag"><button type="submit">＋ Hinzufügen</button></form>${groups.length?groups.map(([c,rows])=>`<section class="fc-shopping-group"><h4><span>${ICONS[c]||'📦'}</span>${esc(c)}<b>${rows.length}</b></h4><div>${rows.map(row).join('')}</div></section>`).join(''):'<div class="fc-shopping-empty"><strong>✓ Alles erledigt</strong><span>Füge oben den nächsten Einkauf hinzu.</span></div>'}${done.length?`<details class="fc-shopping-done"><summary>Erledigt (${done.length})</summary><div>${done.map(row).join('')}</div></details>`:''}`}
function render(){const m=document.getElementById('fcShoppingModal');if(!m)return;const tabs=m.querySelector('.fc-shopping-listtabs'),main=m.querySelector('.fc-shopping-main');tabs.innerHTML=listTabs();main.innerHTML=mainHtml();bind(m);tile()}
function bind(root){root.querySelectorAll('[data-shopping-list]').forEach(b=>b.onclick=()=>{store().activeListId=b.dataset.shoppingList;persist();render()});root.querySelector('.fc-shopping-new-list')?.addEventListener('click',newList);root.querySelector('.fc-shopping-add')?.addEventListener('submit',e=>{e.preventDefault();const input=root.querySelector('#fcShoppingNewItem'),title=input?.value.trim();if(!title)return;editItem('',{title});});root.querySelector('.fc-shopping-list-menu')?.addEventListener('click',editList);root.querySelectorAll('[data-shopping-item]').forEach(r=>{const id=r.dataset.shoppingItem;r.querySelector('input').onchange=e=>toggleItem(id,e.target.checked);r.querySelector('.fc-shopping-edit').onclick=()=>editItem(id)})}
function formModal(title,body,{save:saveFn,remove=null,after=null}={}){document.getElementById('fcShoppingEdit')?.remove();const x=document.createElement('div');x.id='fcShoppingEdit';x.className='fc-shopping-edit-modal';x.innerHTML=`<section class="fc-shopping-edit-sheet"><header><h3>${esc(title)}</h3><button type="button" data-close>×</button></header>${body}<footer>${remove?'<button type="button" class="danger" data-remove>Löschen</button>':'<span></span>'}<button type="button" data-cancel>Abbrechen</button><button type="button" class="primary" data-save>Speichern</button></footer></section>`;const done=()=>x.remove();x.querySelector('[data-close]').onclick=done;x.querySelector('[data-cancel]').onclick=done;x.onclick=e=>{if(e.target===x)done()};x.querySelector('[data-save]').onclick=()=>{if(saveFn?.(x)!==false){done();render()}};x.querySelector('[data-remove]')?.addEventListener('click',()=>{if(confirm('Wirklich löschen?')){remove?.();done();render()}});document.body.appendChild(x);after?.(x);setTimeout(()=>x.querySelector('input,select')?.focus(),30)}
function newList(){formModal('Neue Liste',`<div class="fc-shopping-form"><label>NAME<input id="fcShopListName" maxlength="40" placeholder="z. B. Wocheneinkauf"></label></div>`,{save:x=>{const title=x.querySelector('#fcShopListName').value.trim();if(!title)return false;const s=store(),id=uid('list');s.lists[id]={id,title,createdAt:new Date().toISOString(),archived:false,items:{}};s.activeListId=id;persist();return true}})}
function editList(){const l=activeList();formModal('Liste bearbeiten',`<div class="fc-shopping-form"><label>NAME<input id="fcShopListName" maxlength="40" value="${esc(l.title)}"></label></div>`,{save:x=>{const title=x.querySelector('#fcShopListName').value.trim();if(!title)return false;l.title=title;l.updatedAt=new Date().toISOString();persist();return true},remove:lists().length>1?()=>{l.archived=true;l.updatedAt=new Date().toISOString();const s=store();s.activeListId=lists().find(x=>x.id!==l.id)?.id||'';persist()}:null})}
function editItem(id='',defaults={}){const l=activeList(),existing=id?l.items?.[id]:null,x=existing||{title:defaults.title||'',quantity:'',category:'Lebensmittel',personId:'all'};const personOptions=[`<option value="all" ${!x.personId||x.personId==='all'?'selected':''}>Familie</option>`,...people().map(p=>`<option value="${esc(p.id)}" ${String(x.personId)===p.id?'selected':''}>${esc(p.name)}</option>`)].join('');formModal(existing?'Eintrag bearbeiten':'Eintrag hinzufügen',`<div class="fc-shopping-form"><label>ARTIKEL<input id="fcShopTitle" maxlength="80" value="${esc(x.title)}"></label><div class="fc-shopping-form-grid"><label>MENGE<input id="fcShopQty" maxlength="24" value="${esc(x.quantity||'')}" placeholder="z. B. 2×"></label><label>KATEGORIE<select id="fcShopCat">${CATEGORIES.map(c=>`<option ${c===(x.category||'Lebensmittel')?'selected':''}>${esc(c)}</option>`).join('')}</select></label></div><label>FÜR WEN?<select id="fcShopPerson">${personOptions}</select></label></div>`,{save:m=>{const title=m.querySelector('#fcShopTitle').value.trim();if(!title)return false;if(!l.items||typeof l.items!=='object')l.items={};const now=new Date().toISOString(),row=existing||{id:uid('item'),createdAt:now,done:false,order:Math.max(0,...items(l).map(v=>Number(v.order||0)))+10};row.title=title;row.quantity=m.querySelector('#fcShopQty').value.trim();row.category=m.querySelector('#fcShopCat').value;row.personId=m.querySelector('#fcShopPerson').value;row.updatedAt=now;l.items[row.id]=row;l.updatedAt=now;persist();return true},remove:existing?()=>{existing.archived=true;existing.updatedAt=new Date().toISOString();persist()}:null})}
function toggleItem(id,done){const l=activeList(),x=l.items?.[id];if(!x)return;x.done=!!done;x.completedAt=done?new Date().toISOString():'';x.updatedAt=new Date().toISOString();l.updatedAt=x.updatedAt;persist();render()}
function open(){shell()}
function install(){const root=document.getElementById('more');if(!root){setTimeout(install,50);return}const obs=new MutationObserver(()=>{clearTimeout(obs._t);obs._t=setTimeout(tile,20)});obs.observe(root,{childList:true,subtree:true});tile();document.querySelector('.fc9-nav button[data-screen="more"]')?.addEventListener('click',()=>setTimeout(tile,25));document.documentElement.dataset.fcShoppingLists='v53'}
window.fcOpenShoppingLists=open;window.__fcShoppingLists={version:VERSION,open,render,store,health:()=>({version:VERSION,lists:lists().length,openItems:allOpenCount(),cloudCompatible:true,objectMergeModel:true})};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();