// Previous cache markers retained for regression compatibility: family-command-v54, family-command-v55, family-command-v56, family-command-v57, family-command-v58, family-command-v59, family-command-v60, family-command-v61, family-command-v62, family-command-v63, family-command-v64, family-command-v65, family-command-v66, family-command-v67, family-command-v68, family-command-v69, family-command-v70, family-command-v71, family-command-v72, family-command-v73, family-command-v74, family-command-v75, family-command-v76, family-command-v77, family-command-v78, family-command-v79, family-command-v80, family-command-v81, family-command-v82, family-command-v83, family-command-v84, family-command-v85, family-command-v86, family-command-v87, family-command-v88, family-command-v89, family-command-v90, family-command-v91, family-command-v92, family-command-v93, family-command-v94, family-command-v95, family-command-v96, family-command-v97, family-command-v98, family-command-v99, family-command-v100, family-command-v101, family-command-v102, family-command-v103, family-command-v104, family-command-v105
const CACHE='family-command-v106';
const CORE=['./index.html','./core-runtime.js','./cloud-state.js','./v9.css','./v9-professional.css','./reference-mobile-v35.css','./v9-global-polish.css','./v9-global-polish-final.css','./v9-product-design.css','./v9-product-design-fixes.css','./v9-responsive-v946.css','./mobile-school-day-v947.css','./v9-iphone-layout-v948.css','./v9-visual-polish-v949.css','./v9-mobile-polish-v952.css','./v9-unified-design-v958.css','./v9-final-unity-v9618.css','./v9-design-system-v9619.css','./v9-layout-final-v9622.css','./v9-page-polish-v959.css','./v9-form-dialog-polish-v960.css','./v9-interaction-accessibility-v961.css','./daily-check.css','./header-native-v9652.css','./sharp-header-v9643.css','./header-structure-v9654.css','./header-structure-v9654.js','./header-crisp-v9654.css','./shopping-lists.css','./meal-planner.css','./recipes-favorites.css','./family-budget.css','./family-contacts.css','./reference-dashboard-v36.css','./global-design-v37.css','./document-viewer.css','./document-viewer.js','./smart-documents.js','./v9-app.js','./daily-check.js','./shopping-lists.js','./meal-planner.js','./recipe-meal-bridge.js','./recipes-favorites.js','./family-budget.js','./family-contacts.js','./reminder-center.js','./v9-professional.js','./reference-mobile-v35.js','./reference-dashboard-v36.js','./mobile-school-day-v947.js','./v9-iphone-layout-v948.js','./v9-data.js','./event-details.js','./chat-command-sync.js','./app-data-rules.js','./event-delete-fix.js','./multi-link-ui.js','./homework-originals.js','./print-planner-v2.js','./backup-manager.js','./app-selftest-v9.js','./push-v2.js','./runtime-health.js','./manifest.webmanifest','./icon.svg','./apple-touch-icon.png','./icon-192.png','./icon-512.png'];
const keyOf=request=>{const u=new URL(typeof request==='string'?request:request.url,self.location.href);return u.origin===self.location.origin?u.pathname:request};
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(async c=>{for(const p of CORE){try{const r=await fetch(p,{cache:'reload'});if(r.ok)await c.put(keyOf(p),r)}catch(_){}}}));self.skipWaiting()});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('family-command-')&&k!==CACHE).map(k=>caches.delete(k)))));self.clients.claim()});
async function cachePut(request,response){try{if(response?.ok&&response.type==='basic'){const c=await caches.open(CACHE);await c.put(keyOf(request),response.clone())}}catch(e){}return response}
async function navigation(request){try{const r=await fetch(request,{cache:'no-store'});if(r?.ok)return cachePut('./index.html',r)}catch(e){}return(await caches.match(keyOf('./index.html')))||Response.error()}
async function asset(request,event){const key=keyOf(request),cached=await caches.match(key),u=new URL(request.url),versioned=u.searchParams.has('v');if(versioned){try{return await cachePut(request,await fetch(request,{cache:'reload'}))}catch(e){if(cached)return cached;return new Response('',{status:504,statusText:'Offline'})}}if(cached){event.waitUntil(fetch(request,{cache:'reload'}).then(r=>cachePut(request,r)).catch(()=>{}));return cached}try{return await cachePut(request,await fetch(request,{cache:'reload'}))}catch(e){return new Response('',{status:504,statusText:'Offline'})}}
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(u.origin!==self.location.origin)return;if(e.request.mode==='navigate')e.respondWith(navigation(e.request));else e.respondWith(asset(e.request,e))});
self.addEventListener('push',e=>{let p={};try{p=e.data?e.data.json():{}}catch(_){p={body:e.data?e.data.text():''}}e.waitUntil(self.registration.showNotification(p.title||'Familienzentrale',{body:p.body||'',tag:p.tag||'familienzentrale',data:{url:p.url||'./'}}))});
self.addEventListener('notificationclick',e=>{e.notification.close();const target=new URL(e.notification.data?.url||'./',self.location.href).href;e.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(list=>{for(const w of list){if('focus'in w){w.navigate(target);return w.focus()} }return clients.openWindow(target)}))});