const CACHE='family-command-v32';
const CORE=['./','./index.html','./v8-foundation.css','./v8-ui.css','./v8-overrides.css','./screen-redesign-v6.js','./app-data-rules.js','./today-relevance.js','./tomorrow-screen.js','./daily-checklist.js','./todo-list.js','./tomorrow-preview.js','./pendencies.js','./event-details.js','./multi-link-ui.js','./event-delete-fix.js','./homework-originals.js','./today-addons-stabilizer.js','./v8-shell.js','./chat-command-sync.js','./manifest.webmanifest','./icon.svg'];
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll(CORE)).catch(()=>{}));self.skipWaiting()});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('family-command-')&&k!==CACHE).map(k=>caches.delete(k)))));self.clients.claim()});
async function cachePut(key,response){try{if(response&&response.ok&&response.type==='basic'){const c=await caches.open(CACHE);await c.put(key,response.clone())}}catch(e){}return response}
async function navigation(request,event){const cached=await caches.match('./index.html');if(cached){event.waitUntil(fetch(request,{cache:'no-store'}).then(r=>cachePut('./index.html',r)).catch(()=>{}));return cached}const r=await fetch(request,{cache:'no-store'}).catch(()=>null);return r?cachePut('./index.html',r):Response.error()}
async function staticAsset(request,event){const cached=await caches.match(request,{ignoreSearch:true});if(cached){event.waitUntil(fetch(request,{cache:'no-cache'}).then(r=>cachePut(request,r)).catch(()=>{}));return cached}const r=await fetch(request,{cache:'default'}).catch(()=>null);return r||new Response('',{status:504,statusText:'Offline'})}
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(u.origin!==self.location.origin)return;if(e.request.mode==='navigate'){e.respondWith(navigation(e.request,e));return}e.respondWith(staticAsset(e.request,e))});
self.addEventListener('push',e=>{let p={};try{p=e.data?e.data.json():{}}catch(_){p={body:e.data?e.data.text():''}}e.waitUntil(self.registration.showNotification(p.title||'Family Command',{body:p.body||'',tag:p.tag||'family-command',data:{url:p.url||'./'}}))});
self.addEventListener('notificationclick',e=>{e.notification.close();const target=new URL(e.notification.data?.url||'./',self.location.href).href;e.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(list=>{for(const w of list){if('focus'in w){w.navigate(target);return w.focus()}}return clients.openWindow(target)}))});
