/* Familienzentrale V9.63.1 · persistent HEUTE anchor across all screens */
(()=>{'use strict';if(window.__fcTodayAnchorInstalled)return;window.__fcTodayAnchorInstalled=true;
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,today=()=>iso(new Date()),dateObj=s=>new Date(String(s)+'T12:00:00');
const shortDate=s=>new Intl.DateTimeFormat('de-CH',{weekday:'short',day:'numeric',month:'short'}).format(dateObj(s));
const longDate=s=>new Intl.DateTimeFormat('de-CH',{weekday:'long',day:'numeric',month:'long'}).format(dateObj(s));
function ensureHeader(){const brand=document.querySelector('.fc9-brand');if(!brand)return false;let a=brand.querySelector('.fc-today-anchor');if(!a){a=document.createElement('button');a.type='button';a.className='fc-today-anchor';a.setAttribute('aria-label','Tagescheck für heute öffnen');a.onclick=()=>window.fcOpenDailyCheck?.(today());brand.appendChild(a)}a.innerHTML=`<b>HEUTE</b><span>${shortDate(today())}</span>`;return true}
function decorateCalendar(){const t=today();document.querySelectorAll('.fc9-weekday[data-week-date]').forEach(b=>{const hit=b.dataset.weekDate===t;b.classList.toggle('fc-is-today',hit);let tag=b.querySelector('.fc-today-tag');if(hit&&!tag){tag=document.createElement('small');tag.className='fc-today-tag';tag.textContent='HEUTE';b.appendChild(tag)}if(!hit)tag?.remove()});const expected=longDate(t).replace(/\s+/g,' ').trim().toLowerCase();document.querySelectorAll('#events .fc9-day-label').forEach(x=>{const raw=String(x.childNodes[0]?.textContent||x.textContent||'').replace(/\s+/g,' ').trim().toLowerCase();const hit=raw===expected||raw.startsWith(expected);x.classList.toggle('fc-is-today',hit);let tag=x.querySelector('.fc-today-tag');if(hit&&!tag){tag=document.createElement('span');tag.className='fc-today-tag';tag.textContent='HEUTE';x.appendChild(tag)}if(!hit)tag?.remove()})}
function markScreen(){const active=document.querySelector('.fc9-screen.active');document.documentElement.dataset.fcActiveScreen=active?.id||'';ensureHeader();decorateCalendar()}
let queued=false;function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;markScreen()})}
function install(){markScreen();new MutationObserver(schedule).observe(document.getElementById('fcApp')||document.body,{childList:true,subtree:true});document.addEventListener('fc:v9-ready',schedule);window.addEventListener('pageshow',schedule);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')schedule()});setInterval(schedule,60000)}
window.__fcTodayAnchor={version:'9.63.1',refresh:markScreen,health:()=>({version:'9.63.1',persistent:true,calendarToday:true,opensDailyCheck:true})};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();