/* Family Command · lean personal todos · V8.5 · 2026-08-28 */
(()=>{
  'use strict';
  if(window.__fcTodoListInstalled)return;window.__fcTodoListInstalled=true;
  const SECTION={morning:'Morgens',day:'Tagsüber',evening:'Abends'},ORDER={morning:0,day:1,evening:2};
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const today=()=>{try{return typeof todayISO==='function'?todayISO():new Date().toISOString().slice(0,10)}catch(e){return new Date().toISOString().slice(0,10)}};
  const addDays=(iso,n)=>{const d=new Date(String(iso)+'T12:00:00');d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  const uid=()=>`todo-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
  function all(){try{if(!Array.isArray(data.todos))data.todos=[];return data.todos}catch(e){return[]}}
  function keyOf(t){return String(t?.sourceCommandId||'')||String(t?.clientRef||'')||String(t?.id||'')}
  function sort(rows){return [...rows].sort((a,b)=>Number(!!b.priority)-Number(!!a.priority)||(ORDER[a.section]??1)-(ORDER[b.section]??1)||Number(a.order||0)-Number(b.order||0)||String(a.createdAt||'').localeCompare(String(b.createdAt||'')))}
  function mergedRows(date,includeOverdue=false,includeDone=true){
    try{const api=window.__fcChatCommandSync;if(api?.getTodosFor){const chat=api.getTodosFor(date,{includeOverdue,includeDone:true}),map=new Map();for(const t of [...all(),...chat])map.set(keyOf(t)||`${t.date}|${t.title}`,t);return sort([...map.values()].filter(t=>!t.archived&&(includeDone||!t.done)&&(String(t.date)===String(date)||(includeOverdue&&!t.done&&String(t.date)<String(date)))))} }catch(e){}
    return sort(all().filter(t=>!t.archived&&(includeDone||!t.done)&&(String(t.date)===String(date)||(includeOverdue&&!t.done&&String(t.date)<String(date)))))
  }
  function rowsFor(date,{includeOverdue=false,includeDone=true}={}){return mergedRows(date,includeOverdue,includeDone)}
  function find(id){return all().find(x=>String(x.id)===String(id))||null}
  function persist(){try{if(typeof save==='function')save()}catch(e){console.error('fc_todo_save',e)}try{window.__fcV8Shell?.invalidate?.(['today','tomorrow'])}catch(e){}}
  function rerender(){renderAll();try{if(document.getElementById('today')?.classList.contains('active'))window.__fcTomorrowPreview?.render?.()}catch(e){}try{window.__fcV8?.enhance?.(document.querySelector('.screen.active')?.id||'today')}catch(e){}}
  function toggle(id,val){const t=find(id);if(!t)return;t.done=!!val;t.completedAt=t.done?new Date().toISOString():'';persist();rerender()}
  function remove(id){const t=find(id);if(!t)return;try{window.__fcChatCommandSync?.dismiss?.(t)}catch(e){}data.todos=all().filter(x=>String(x.id)!==String(id));persist();document.getElementById('fcTodoEdit')?.remove();rerender()}
  function fmtDate(v){try{return new Intl.DateTimeFormat('de-CH',{weekday:'short',day:'numeric',month:'short'}).format(new Date(String(v)+'T12:00:00')).replace(',','')}catch(e){return v}}
  function label(t,date){return String(t.date)<String(date)&&!t.done?`Überfällig · ${fmtDate(t.date)}`:(SECTION[t.section]||SECTION.day)}

  function row(t,date,compact=false){return `<div class="fc-todo-row ${t.done?'done':''}" data-id="${esc(t.id)}"><label><input type="checkbox" ${t.done?'checked':''}><span class="fc-todo-box"></span></label><div class="fc-todo-copy">${t.priority?'<em>WICHTIG</em>':''}<b>${esc(t.title)}</b><small>${esc(label(t,date))}</small></div>${compact?'':`<button type="button" class="fc-todo-more" aria-label="To-do bearbeiten">•••</button>`}</div>`}
  function card(root,date,title,includeOverdue=false){
    if(!root)return;root.querySelector('.fc-todo-card')?.remove();const rows=rowsFor(date,{includeOverdue,includeDone:true});if(!rows.length)return;
    const open=rows.filter(x=>!x.done),done=rows.length-open.length,pct=rows.length?Math.round(done/rows.length*100):0;
    const sec=document.createElement('section');sec.className='fc-todo-card';sec.dataset.date=date;
    sec.innerHTML=`<div class="fc-todo-head"><div><h2>${esc(title)}</h2><p>${open.length?`${open.length} offen`:'Alles erledigt'}</p></div><div class="fc-todo-head-actions"><strong>${pct}%</strong><button type="button" data-add aria-label="To-do hinzufügen">＋</button></div></div><div class="fc-todo-progress"><i style="width:${pct}%"></i></div><div class="fc-todo-preview">${rows.slice(0,4).map(t=>row(t,date,true)).join('')}</div>${rows.length>4?`<button type="button" class="fc-todo-open">Alle ${rows.length} anzeigen</button>`:''}`;
    const page=root.querySelector('.v6-page')||root,head=page.querySelector('header,.v6-page-head'),focus=root.querySelector('.v6-focus');if(focus?.parentNode)focus.parentNode.insertBefore(sec,focus.nextSibling);else if(head?.parentNode)head.parentNode.insertBefore(sec,head.nextSibling);else page.prepend(sec);
    bindRows(sec,date);sec.querySelector('[data-add]')?.addEventListener('click',()=>openEdit(date));sec.querySelector('.fc-todo-open')?.addEventListener('click',()=>openList(date));
  }
  function renderAll(){try{card(document.getElementById('today'),today(),'Heute erledigen',true);card(document.getElementById('tomorrow'),addDays(today(),1),'Morgen erledigen',false)}catch(e){console.error('fc_todo_render',e)}}
  function bindRows(root,date){root.querySelectorAll('.fc-todo-row').forEach(r=>{const id=r.dataset.id;r.querySelector('input')?.addEventListener('change',e=>toggle(id,e.target.checked));r.querySelector('.fc-todo-more')?.addEventListener('click',()=>openEdit(date,id))})}

  function openEdit(date=today(),id=''){
    document.getElementById('fcTodoEdit')?.remove();const t=id?find(id):null,m=document.createElement('div');m.id='fcTodoEdit';m.className='fc-todo-modal';
    m.innerHTML=`<section class="fc-todo-edit"><div class="fc-todo-sheet-head"><div><span>${t?'TO-DO BEARBEITEN':'NEUES TO-DO'}</span><h2>${t?'Punkt bearbeiten':'To-do hinzufügen'}</h2></div><button type="button" data-close>×</button></div><div class="fc-todo-form"><label><span>AUFGABE</span><textarea id="fcTodoTitle" rows="3">${esc(t?.title||'')}</textarea></label><div class="fc-todo-form-grid"><label><span>TAG</span><input id="fcTodoDate" type="date" value="${esc(t?.date||date)}"></label><label><span>ZEITBEREICH</span><select id="fcTodoSection"><option value="morning" ${t?.section==='morning'?'selected':''}>Morgens</option><option value="day" ${!t||t?.section==='day'?'selected':''}>Tagsüber</option><option value="evening" ${t?.section==='evening'?'selected':''}>Abends</option></select></label></div><label class="fc-todo-priority"><input id="fcTodoPriority" type="checkbox" ${t?.priority?'checked':''}><span><b>Wichtig</b><small>Ganz oben anzeigen</small></span></label><button type="button" class="fc-todo-save">Speichern</button>${t?'<button type="button" class="fc-todo-delete">To-do löschen</button>':''}</div></section>`;
    const close=()=>m.remove();m.querySelector('[data-close]').onclick=close;m.onclick=e=>{if(e.target===m)close()};
    m.querySelector('.fc-todo-save').onclick=()=>{const title=m.querySelector('#fcTodoTitle').value.trim(),d=m.querySelector('#fcTodoDate').value;if(!title||!d)return;let x=t;if(!x){const max=Math.max(0,...all().map(v=>Number(v.order||0)));x={id:uid(),done:false,archived:false,order:max+10,createdAt:new Date().toISOString(),completedAt:''};all().push(x)}x.title=title;x.date=d;x.section=m.querySelector('#fcTodoSection').value||'day';x.priority=!!m.querySelector('#fcTodoPriority').checked;persist();close();rerender()};
    m.querySelector('.fc-todo-delete')?.addEventListener('click',()=>{if(confirm('Dieses To-do löschen?'))remove(t.id)});document.body.appendChild(m);setTimeout(()=>m.querySelector('#fcTodoTitle')?.focus(),40)
  }
  function openList(date=today()){
    document.getElementById('fcTodoSheet')?.remove();const rows=rowsFor(date,{includeOverdue:date===today(),includeDone:true}),m=document.createElement('div');m.id='fcTodoSheet';m.className='fc-todo-modal';
    m.innerHTML=`<section class="fc-todo-sheet"><div class="fc-todo-sheet-head"><div><span>TAGES-TO-DOS</span><h2>${date===today()?'Heute':fmtDate(date)}</h2><p>${rows.filter(x=>!x.done).length} offen</p></div><button type="button" data-close>×</button></div><div class="fc-todo-sheet-actions"><button type="button" data-new>＋ Neues To-do</button></div><div class="fc-todo-list-body">${rows.length?rows.map(t=>row(t,date,false)).join(''):'<div class="fc-todo-sheet-empty">Keine To-dos für diesen Tag.</div>'}</div></section>`;
    m.querySelector('[data-close]').onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()};m.querySelector('[data-new]').onclick=()=>{m.remove();openEdit(date)};bindRows(m,date);document.body.appendChild(m)
  }

  function ensureStyle(){if(document.getElementById('fc-todo-v85-style'))return;const s=document.createElement('style');s.id='fc-todo-v85-style';s.textContent=`.fc-todo-modal{position:fixed;inset:0;z-index:100300;background:rgba(15,23,42,.42);display:flex;align-items:flex-end;justify-content:center;padding:12px 12px calc(12px + env(safe-area-inset-bottom));backdrop-filter:blur(5px)}.fc-todo-sheet,.fc-todo-edit{width:min(100%,460px);max-height:90dvh;overflow:auto;background:#fff;border:1px solid #e2e7ee;border-radius:22px;padding:15px;color:#172033;box-shadow:0 22px 60px rgba(15,23,42,.22)}.fc-todo-sheet-head{display:flex;justify-content:space-between;gap:10px}.fc-todo-sheet-head span,.fc-todo-form label>span{display:block;color:#7b879b;font-size:8px;font-weight:900;letter-spacing:.09em}.fc-todo-sheet-head h2{margin:3px 0 0;font-size:21px}.fc-todo-sheet-head p{margin:3px 0 0;color:#7b879b;font-size:9px}.fc-todo-sheet-head>button{width:38px;height:38px;border:0;border-radius:999px;background:#f2f4f8;color:#64748b;font-size:20px}.fc-todo-form{display:grid;gap:11px;margin-top:14px}.fc-todo-form textarea,.fc-todo-form input[type=date],.fc-todo-form select{width:100%;min-height:44px;border:1px solid #dfe5ed;border-radius:11px;background:#fff;color:#172033;padding:10px;font:inherit}.fc-todo-form-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.fc-todo-priority{display:flex!important;gap:9px;align-items:center;padding:10px;border:1px solid #e1e6ed;border-radius:11px;background:#f8fafc}.fc-todo-priority input{width:22px;height:22px}.fc-todo-priority span{margin:0!important}.fc-todo-priority b{display:block;font-size:11px}.fc-todo-priority small{display:block;color:#7b879b;font-size:8px}.fc-todo-save,.fc-todo-delete{min-height:44px;border:0;border-radius:11px;background:#5268ff;color:#fff;font-weight:850}.fc-todo-delete{background:#fff5f6;border:1px solid #efcbd0;color:#b23c49}.fc-todo-sheet-actions{margin:12px 0}.fc-todo-sheet-actions button{min-height:42px;width:100%;border:1px solid #dfe5ed;border-radius:11px;background:#f7f9fc;color:#334155;font-weight:800}.fc-todo-list-body{display:grid;gap:3px}.fc-todo-sheet-empty{padding:20px;text-align:center;color:#7b879b;font-size:10px}@media(max-width:350px){.fc-todo-form-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
  function wrap(name){const fn=window[name];if(typeof fn!=='function'||fn.__fcTodoV85)return;const w=function(...a){const out=fn.apply(this,a);if(out&&typeof out.then==='function')return out.then(v=>{renderAll();return v});renderAll();return out};w.__fcTodoV85=true;window[name]=w;try{if(name==='renderToday')renderToday=w;if(name==='renderTomorrow')renderTomorrow=w}catch(e){}}

  ensureStyle();wrap('renderToday');wrap('renderTomorrow');renderAll();
  window.fcTodoOpen=openList;window.fcTodoAdd=openEdit;window.__fcTodo={version:2,rowsFor,open:openList,add:openEdit,render:renderAll,toggle,remove};
})();
