/* Family Command · V8 stable native shell · 2026-08-28 */
(()=>{
  'use strict';
  if(window.__fcV8ShellInstalled)return;window.__fcV8ShellInstalled=true;
  const svg={today:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3.5 10.5 12 3l8.5 7.5v9A1.5 1.5 0 0 1 19 21h-4.5v-6h-5v6H5a1.5 1.5 0 0 1-1.5-1.5z"/></svg>',tomorrow:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3.5"/><path d="M12 2.5v2M12 19.5v2M2.5 12h2M19.5 12h2M5.3 5.3l1.4 1.4M17.3 17.3l1.4 1.4M18.7 5.3l-1.4 1.4M6.7 17.3l-1.4 1.4"/></svg>',calendar:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3.5" y="5" width="17" height="15" rx="2.5"/><path d="M7 3v4M17 3v4M3.5 9.5h17M7 13h3M14 13h3M7 16.5h3"/></svg>',tasks:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="5" y="3.5" width="14" height="17" rx="2.3"/><path d="M8.2 10.2 10 12l3.4-3.5M8.2 16h7.5"/></svg>',more:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="5" cy="12" r="1.4"/><circle cx="12" cy="12" r="1.4"/><circle cx="19" cy="12" r="1.4"/></svg>'};
  const originalOpen=typeof window.openScreen==='function'?window.openScreen:null;
  const raw={today:typeof window.renderToday==='function'?window.renderToday:null,tomorrow:typeof window.renderTomorrow==='function'?window.renderTomorrow:null,week:typeof window.renderWeek==='function'?window.renderWeek:null,events:typeof window.renderEvents==='function'?window.renderEvents:null,homework:typeof window.renderHomeworkScreen==='function'?window.renderHomeworkScreen:null,more:typeof window.renderMore==='function'?window.renderMore:null,people:typeof window.renderPeople==='function'?window.renderPeople:null};
  const rendering=new Set();
  function ensureScreens(){const main=document.querySelector('.content');if(!main)return;if(!document.getElementById('homework')){const s=document.createElement('section');s.id='homework';s.className='screen';const more=document.getElementById('more');more?main.insertBefore(s,more):main.appendChild(s)}}
  function navMarkup(){return `<button type="button" class="navbtn" data-screen="today"><span class="ico">${svg.today}</span><span>Heute</span></button><button type="button" class="navbtn" data-screen="tomorrow"><span class="ico">${svg.tomorrow}</span><span>Morgen</span></button><button type="button" class="navbtn" data-screen="events"><span class="ico">${svg.calendar}</span><span>Kalender</span></button><button type="button" class="navbtn" data-screen="homework"><span class="ico">${svg.tasks}</span><span>Aufgaben</span></button><button type="button" class="navbtn" data-screen="more"><span class="ico">${svg.more}</span><span>Mehr</span></button>`}
  const activeParent=id=>id==='week'?'events':id==='people'?'more':id;
  function setActiveNav(id){const parent=activeParent(id);document.querySelectorAll('.bottomnav-in .navbtn').forEach(b=>b.classList.toggle('active',b.dataset.screen===parent))}
  function ensureNav(){const n=document.querySelector('.bottomnav-in');if(!n)return;const valid=n.dataset.fcV8Nav==='1'&&n.children.length===5&&n.querySelector('[data-screen="events"]')&&n.querySelector('[data-screen="homework"]');if(!valid){n.dataset.fcV8Nav='1';n.removeAttribute('data-fc-six-nav');n.innerHTML=navMarkup()}n.querySelectorAll('.navbtn').forEach(b=>{if(b.dataset.fcV8Bound)return;b.dataset.fcV8Bound='1';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();open(b.dataset.screen)})});setActiveNav(document.querySelector('.screen.active')?.id||'today')}
  function showOnly(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));setActiveNav(id)}
  function invoke(fn,args=[]){try{return typeof fn==='function'?fn(...args):undefined}catch(e){console.error('fc_v8_render',e)}}
  function addCalendarTabs(root,mode){if(!root)return;let tabs=root.querySelector('.v8-calendar-tabs');const page=root.querySelector('.v6-page,.fc-week-v2'),head=page?.querySelector('.v6-page-head');if(!page||!head)return;const h=head.querySelector('h1');if(h&&h.textContent!=='Kalender')h.textContent='Kalender';if(!tabs){tabs=document.createElement('div');tabs.className='v8-calendar-tabs';tabs.innerHTML='<button type="button" data-v8-calendar="agenda">Agenda</button><button type="button" data-v8-calendar="week">Woche</button>';tabs.querySelector('[data-v8-calendar="agenda"]').onclick=()=>open('events');tabs.querySelector('[data-v8-calendar="week"]').onclick=()=>open('week');head.after(tabs)}tabs.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.v8Calendar===mode))}
  function cleanDay(root){if(!root)return;root.classList.add('v8-day');root.querySelectorAll('.fcp-today').forEach(x=>x.hidden=true);[...root.querySelectorAll('.v6-section')].forEach(sec=>{const title=(sec.querySelector('.v6-section-head h2')?.textContent||'').trim();if(/^Pendenzen$/i.test(title))sec.hidden=true})}
  function cleanMore(root){if(!root)return;root.classList.add('v8-more');root.querySelectorAll('.v6-more-row,.v6-more-detail').forEach(x=>{if(/Family AI/i.test(x.textContent||''))x.hidden=true})}
  function post(id){const root=document.getElementById(id);if(!root)return;if(id==='today'||id==='tomorrow')cleanDay(root);if(id==='events')addCalendarTabs(root,'agenda');if(id==='week')addCalendarTabs(root,'week');if(id==='more')cleanMore(root);try{window.__fcTodayAddonsStabilizer?.repair?.(id);window.__fcV8?.enhance?.(id)}catch(e){console.error('fc_v8_post',e)}document.documentElement.dataset.fcV8Native='1';setActiveNav(id)}
  function render(id,...args){if(rendering.has(id))return;const fn=raw[id];if(typeof fn!=='function'){post(id);return}rendering.add(id);let out;try{out=invoke(fn,args)}finally{if(!(out&&typeof out.then==='function'))rendering.delete(id)}if(out&&typeof out.then==='function')return out.finally(()=>{rendering.delete(id);requestAnimationFrame(()=>post(id))});requestAnimationFrame(()=>post(id));return out}
  function open(id){ensureScreens();const known=['today','tomorrow','week','events','homework','more','people'];if(!known.includes(id)&&originalOpen)return invoke(originalOpen,[id]);showOnly(id);if(id==='people'){if(raw.people)render('people');else if(originalOpen)invoke(originalOpen,['people'])}else render(id);try{window.scrollTo({top:0,behavior:'auto'})}catch(e){window.scrollTo(0,0)}}
  function installRenderWrappers(){if(raw.today){window.renderToday=(...a)=>render('today',...a);try{renderToday=window.renderToday}catch(e){}}if(raw.tomorrow){window.renderTomorrow=(...a)=>render('tomorrow',...a);try{renderTomorrow=window.renderTomorrow}catch(e){}}if(raw.week){window.renderWeek=(...a)=>render('week',...a);try{renderWeek=window.renderWeek}catch(e){}}if(raw.events){window.renderEvents=(...a)=>render('events',...a);try{renderEvents=window.renderEvents}catch(e){}}if(raw.homework){window.renderHomeworkScreen=(...a)=>render('homework',...a);try{renderHomeworkScreen=window.renderHomeworkScreen}catch(e){}}if(raw.more){window.renderMore=(...a)=>render('more',...a);try{renderMore=window.renderMore}catch(e){}}window.v6OpenHomework=()=>open('homework')}
  function install(){ensureScreens();ensureNav();installRenderWrappers();window.openScreen=open;try{openScreen=open}catch(e){};const active=document.querySelector('.screen.active')?.id||'today';render(active);document.documentElement.dataset.fcV8Native='1'}
  window.__fcV8Shell={version:'8.2-stable',open,ensureNav,post,install,render};
  install();
})();
(()=>{if(window.__fcChatCommandLoader)return;window.__fcChatCommandLoader=true;const s=document.createElement('script');s.src='./chat-command-sync.js?v=20260828-chat1';s.async=true;s.onerror=()=>console.error('fc_chat_command_loader');document.body.appendChild(s)})();
