/* Family Command V9 · idempotent data normalization */
(()=>{
'use strict';
if(window.__fcV9DataInstalled)return;window.__fcV9DataInstalled=true;
const FRUIT={id:'todo-landi-fruchtfliege-20260829',clientRef:'chat-2026-08-28-fruchtfliegenfalle-landi-bezahlt-v2',sourceCommandId:'af182519-2680-43ae-a6e0-b931b1483ee7',title:'Fruchtfliegenfalle für meine Frau in der LANDI kaufen – bereits bezahlt, kein Geld mehr verlangen',date:'2026-08-29',section:'day',priority:true,done:false,archived:false};
function persist(){try{if(typeof save==='function')save()}catch(e){console.error('fc9_data_save',e)}}
function ensureFruitfly(){try{if(typeof data==='undefined'||!data)return false;if(!Array.isArray(data.todos))data.todos=[];let changed=false;const old=['chat-2026-08-28-fruchtfliegenfalle-landi','9e88bd19-e984-4b47-9dc7-2b2f52d92dde'];const before=data.todos.length;data.todos=data.todos.filter(t=>!old.includes(String(t?.clientRef||''))&&!old.includes(String(t?.sourceCommandId||'')));if(data.todos.length!==before)changed=true;let t=data.todos.find(x=>String(x?.clientRef||'')===FRUIT.clientRef||String(x?.sourceCommandId||'')===FRUIT.sourceCommandId||String(x?.id||'')===FRUIT.id);if(!t){t={...FRUIT,createdAt:new Date().toISOString(),completedAt:'',order:Math.max(0,...data.todos.map(x=>Number(x?.order||0)))+10};data.todos.push(t);changed=true}for(const [k,v] of Object.entries(FRUIT))if(t[k]!==v){t[k]=v;changed=true}if(changed)persist();try{localStorage.setItem('fc-chat-todos-v2',JSON.stringify((()=>{let rows=[];try{rows=JSON.parse(localStorage.getItem('fc-chat-todos-v2')||'[]')}catch(e){}rows=Array.isArray(rows)?rows:[];const i=rows.findIndex(x=>String(x?.clientRef||'')===FRUIT.clientRef||String(x?.sourceCommandId||'')===FRUIT.sourceCommandId);const row={...t};if(i>=0)rows[i]={...rows[i],...row};else rows.push(row);return rows.slice(-100)})()))}catch(e){}return changed}catch(e){console.error('fc9_fruitfly',e);return false}}
const changed=ensureFruitfly();window.__fcV9Data={version:1,ensureFruitfly,fruitfly:FRUIT,changed};
})();
