import {W,H,clamp,dist,pointSegDist,circleRect,calcLaunch,starsFor,LEVELS} from './core.js';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d',{alpha:false});
const $=id=>document.getElementById(id);
const ui={job:$('jobName'),mission:$('missionText'),restart:$('restart'),intro:$('intro'),play:$('play'),result:$('result'),kicker:$('resultKicker'),title:$('resultTitle'),stars:$('stars'),time:$('timeStat'),shots:$('shotStat'),loot:$('lootStat'),next:$('next'),goal:$('goalBanner'),toast:$('toast'),rotate:$('rotate')};
let view={s:1,ox:0,oy:0,cssS:1,cssOx:0,cssOy:0},levelIndex=0,state=null,last=performance.now(),particles=[],rings=[],shake=0,audioCtx=null,toastTimer=0;
function sound(freq=440,d=.05,type='sine',vol=.035){try{audioCtx||=new(window.AudioContext||window.webkitAudioContext);const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+d);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}catch{}}
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);const s=Math.min(canvas.width/W,canvas.height/H),ox=(canvas.width-W*s)/2,oy=(canvas.height-H*s)/2,cssS=Math.min(r.width/W,r.height/H);view={s,ox,oy,cssS,cssOx:(r.width-W*cssS)/2,cssOy:(r.height-H*cssS)/2};ui.rotate.classList.toggle('hidden',innerWidth>=innerHeight)}
addEventListener('resize',resize);resize();
function pos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left-view.cssOx)/view.cssS,y:(e.clientY-r.top-view.cssOy)/view.cssS}}
function makeState(i){const L=LEVELS[i%LEVELS.length];return{L,t:0,shots:0,drag:false,launched:false,returning:false,ended:false,pointer:{x:L.start[0],y:L.start[1]},player:{x:L.start[0],y:L.start[1],vx:0,vy:0,r:25},loot:L.loot.map((p,n)=>({x:p[0],y:p[1],r:22,taken:false,n})),glass:L.glass.map(g=>({x:g[0],y:g[1],w:g[2],h:g[3],broken:false})),bumpers:L.bumpers.map(b=>({x:b[0],y:b[1],r:b[2]})),lasers:L.lasers.map(l=>({x1:l[0],y1:l[1],x2:l[2],y2:l[3],speed:l[4],cool:0})),got:0,flightT:0,aimHint:true,escape:false};}
function reset(i=levelIndex){levelIndex=(i+LEVELS.length)%LEVELS.length;state=makeState(levelIndex);particles=[];rings=[];shake=0;ui.result.classList.add('hidden');ui.goal.classList.add('hidden');updateHud();}
function updateHud(){ui.job.textContent=`JOB ${levelIndex+1} · ${state.L.name}`;ui.mission.textContent=state.escape?'🚐 ZURÜCK ZUM VAN!':`💎 BEUTE ${state.got} / ${state.L.required}`;ui.goal.classList.toggle('hidden',!state.escape)}
function toast(msg){ui.toast.textContent=msg;ui.toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>ui.toast.classList.remove('show'),650)}
function burst(x,y,color,count=22,power=250){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=30+Math.random()*power;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.25+Math.random()*.65,size:2+Math.random()*6,color})}}
function ring(x,y,color){rings.push({x,y,r:8,life:.45,color})}
function launch(){const v=calcLaunch(state.player,state.pointer);if(!v)return;state.player.vx=v.vx;state.player.vy=v.vy;state.launched=true;state.returning=false;state.drag=false;state.shots++;state.flightT=0;state.aimHint=false;sound(170,.09,'sawtooth',.05);burst(state.player.x,state.player.y,'#ffd33d',12,130)}
canvas.addEventListener('pointerdown',e=>{audioCtx?.resume?.();if(state.ended||ui.intro&&!ui.intro.classList.contains('hidden'))return;const p=pos(e);state.pointer=p;if(!state.launched&&dist(state.player,p)<92){state.drag=true;canvas.setPointerCapture?.(e.pointerId);sound(260,.025,'triangle',.018)}});
canvas.addEventListener('pointermove',e=>{if(state.drag)state.pointer=pos(e)});
canvas.addEventListener('pointerup',()=>{if(state.drag)launch()});
canvas.addEventListener('pointercancel',()=>state.drag=false);
function startReturn(){if(state.returning)return;state.returning=true;state.launched=true;ring(state.player.x,state.player.y,'#58d8ff')}
function complete(){if(state.ended)return;state.ended=true;const stars=starsFor(state.t,state.shots,state.L.par);ui.kicker.textContent='SAUBERER JOB';ui.title.textContent='GESCHAFFT!';ui.stars.textContent='★'.repeat(stars)+'☆'.repeat(3-stars);ui.time.textContent=`${state.t.toFixed(1)}s`;ui.shots.textContent=state.shots;ui.loot.textContent=`${state.got}/${state.loot.length}`;ui.next.textContent=levelIndex<LEVELS.length-1?'NÄCHSTER JOB':'NOCH EINE RUNDE';setTimeout(()=>ui.result.classList.remove('hidden'),350);sound(720,.25,'triangle',.08);burst(state.player.x,state.player.y,'#ffd33d',70,420)}
function update(dt){if(state.ended){stepFx(dt);return}const s=state,p=s.player,L=s.L;s.t+=dt;if(s.launched){s.flightT+=dt;p.vy+=640*dt;p.vx*=Math.pow(.996,dt*60);p.vy*=Math.pow(.997,dt*60);if(s.returning){const ax=L.start[0],ay=L.start[1],dx=ax-p.x,dy=ay-p.y,d=Math.hypot(dx,dy)||1;const pull=clamp(d*7.5,380,1600);p.vx+=dx/d*pull*dt;p.vy+=dy/d*pull*dt;p.vx*=.985;p.vy*=.985}p.x+=p.vx*dt;p.y+=p.vy*dt;const r=p.r;if(p.x<r){p.x=r;p.vx=Math.abs(p.vx)*.78;hit()}if(p.x>W-r){p.x=W-r;p.vx=-Math.abs(p.vx)*.78;hit()}if(p.y<82+r){p.y=82+r;p.vy=Math.abs(p.vy)*.75;hit()}if(p.y>H-r){p.y=H-r;p.vy=-Math.abs(p.vy)*.72;hit()}
  for(const b of s.bumpers){const dx=p.x-b.x,dy=p.y-b.y,d=Math.hypot(dx,dy),rr=p.r+b.r;if(d<rr){const nx=dx/(d||1),ny=dy/(d||1),pen=rr-d;p.x+=nx*pen;p.y+=ny*pen;const vn=p.vx*nx+p.vy*ny;if(vn<0){p.vx-=1.92*vn*nx;p.vy-=1.92*vn*ny;shake=7;sound(210,.04,'square',.025);burst(p.x,p.y,'#76e8ff',15,180)}}}
  const speed=Math.hypot(p.vx,p.vy);for(const g of s.glass){if(g.broken)continue;const c=circleRect(p,p.r,g);if(c){if(speed>320){g.broken=true;shake=11;sound(1040,.065,'square',.04);burst(p.x,p.y,'#b8f3ff',32,330)}else{p.x+=c.nx*c.pen;p.y+=c.ny*c.pen;const vn=p.vx*c.nx+p.vy*c.ny;if(vn<0){p.vx-=1.55*vn*c.nx;p.vy-=1.55*vn*c.ny;hit()}}}}
  for(const l of s.loot){if(!l.taken&&Math.hypot(p.x-l.x,p.y-l.y)<p.r+l.r+6){l.taken=true;s.got++;toast(`💎 BEUTE ${s.got}/${L.required}`);sound(470+s.got*60,.07,'triangle',.065);burst(l.x,l.y,'#ffd33d',30,260);ring(l.x,l.y,'#ffd33d');shake=5;if(s.got>=L.required){s.escape=true;updateHud();toast('🚐 JETZT ZURÜCK ZUM VAN!');startReturn()}}}
  for(const l of s.lasers){l.cool=Math.max(0,l.cool-dt);const on=Math.sin(s.t*l.speed*Math.PI*2)>-.18;if(on&&l.cool<=0&&pointSegDist(p.x,p.y,l.x1,l.y1,l.x2,l.y2)<p.r+5){l.cool=.9;shake=13;sound(92,.16,'sawtooth',.07);burst(p.x,p.y,'#ff586d',28,270);p.vx*=-.45;p.vy=-Math.abs(p.vy)-180}}
  if(!s.returning&&(s.flightT>3.1||speed<72&&s.flightT>.7)) startReturn();
  if(s.returning&&Math.hypot(p.x-L.start[0],p.y-L.start[1])<42){p.x=L.start[0];p.y=L.start[1];p.vx=p.vy=0;s.launched=false;s.returning=false;s.flightT=0;if(s.escape) complete();}
}
stepFx(dt)}
function hit(){shake=Math.max(shake,4);sound(155+Math.random()*60,.03,'square',.018)}
function stepFx(dt){for(const p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=390*dt;p.vx*=.985}particles=particles.filter(p=>p.life>0);for(const r of rings){r.life-=dt;r.r+=220*dt}rings=rings.filter(r=>r.life>0)}
function roundedRect(x,y,w,h,r){ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x,y,w,h,r);else ctx.rect(x,y,w,h)}
function draw(){ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#050811';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.setTransform(view.s,0,0,view.s,view.ox,view.oy);ctx.save();if(shake>0){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.86;if(shake<.2)shake=0}drawScene();ctx.restore()}
function drawScene(){const s=state,L=s.L,p=s.player;const [top,bottom,accent,gold]=L.palette;const bg=ctx.createLinearGradient(0,0,0,H);bg.addColorStop(0,top);bg.addColorStop(1,bottom);ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);
  ctx.fillStyle='rgba(255,255,255,.025)';for(let x=260;x<W;x+=150){ctx.fillRect(x,105,105,145);ctx.fillStyle='rgba(255,255,255,.07)';for(let yy=120;yy<230;yy+=32){ctx.fillRect(x+15,yy,18,12);ctx.fillRect(x+48,yy,18,12);ctx.fillRect(x+80,yy,12,12)}ctx.fillStyle='rgba(255,255,255,.025)'}
  ctx.fillStyle='rgba(8,12,19,.66)';ctx.fillRect(0,610,W,110);ctx.strokeStyle='rgba(255,255,255,.05)';ctx.lineWidth=2;for(let x=0;x<W;x+=80){ctx.beginPath();ctx.moveTo(x,610);ctx.lineTo(x+40,720);ctx.stroke()}
  const [vx,vy,vw,vh]=L.van;ctx.save();ctx.shadowColor='rgba(255,70,70,.35)';ctx.shadowBlur=25;ctx.fillStyle='#d83b45';roundedRect(vx,vy,vw,vh,24);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#9e2631';ctx.fillRect(vx+20,vy+40,vw-40,47);ctx.fillStyle='#172437';roundedRect(vx+25,vy+12,72,42,10);ctx.fill();ctx.fillStyle='#253b56';roundedRect(vx+107,vy+12,40,42,10);ctx.fill();ctx.fillStyle='#111722';ctx.beginPath();ctx.arc(vx+42,vy+vh,22,0,Math.PI*2);ctx.arc(vx+132,vy+vh,22,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='900 15px sans-serif';ctx.textAlign='center';ctx.fillText('FLUCHT',vx+vw/2,vy+83);ctx.strokeStyle=s.escape?'#42e88d':'rgba(66,232,141,.28)';ctx.lineWidth=s.escape?8:4;ctx.setLineDash([14,10]);ctx.beginPath();ctx.arc(L.start[0],L.start[1],72,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.restore();
  ctx.strokeStyle=s.escape?'#42e88d':accent;ctx.lineWidth=5;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(L.anchor[0],L.anchor[1]);ctx.quadraticCurveTo((L.anchor[0]+p.x)/2,(L.anchor[1]+p.y)/2+38,p.x,p.y);ctx.stroke();
  for(const g of s.glass){if(g.broken)continue;ctx.fillStyle='rgba(174,238,255,.10)';ctx.strokeStyle='rgba(184,239,255,.8)';ctx.lineWidth=2;ctx.fillRect(g.x,g.y,g.w,g.h);ctx.strokeRect(g.x,g.y,g.w,g.h);ctx.strokeStyle='rgba(255,255,255,.22)';ctx.beginPath();ctx.moveTo(g.x+4,g.y+12);ctx.lineTo(g.x+g.w-4,g.y+45);ctx.stroke()}
  for(const l of s.lasers){const on=Math.sin(s.t*l.speed*Math.PI*2)>-.18;ctx.strokeStyle=on?'rgba(255,78,103,.94)':'rgba(255,78,103,.14)';ctx.shadowColor=on?'#ff4e67':'transparent';ctx.shadowBlur=on?14:0;ctx.lineWidth=on?4:2;ctx.beginPath();ctx.moveTo(l.x1,l.y1);ctx.lineTo(l.x2,l.y2);ctx.stroke();ctx.shadowBlur=0}
  for(const b of s.bumpers){const rg=ctx.createRadialGradient(b.x-10,b.y-10,2,b.x,b.y,b.r);rg.addColorStop(0,'#fff6a8');rg.addColorStop(.25,gold);rg.addColorStop(1,'#b96a08');ctx.fillStyle=rg;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(41,25,4,.8)';ctx.lineWidth=7;ctx.stroke();ctx.fillStyle='#5f3503';ctx.font='900 20px sans-serif';ctx.textAlign='center';ctx.fillText('↗',b.x,b.y+7)}
  for(const l of s.loot){if(l.taken)continue;const pulse=1+Math.sin(s.t*4+l.n)*.08;ctx.save();ctx.translate(l.x,l.y);ctx.scale(pulse,pulse);ctx.shadowColor=gold;ctx.shadowBlur=25;ctx.fillStyle=gold;ctx.beginPath();ctx.moveTo(0,-25);ctx.lineTo(22,-5);ctx.lineTo(12,24);ctx.lineTo(-12,24);ctx.lineTo(-22,-5);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='rgba(255,255,255,.6)';ctx.beginPath();ctx.moveTo(-7,-16);ctx.lineTo(4,-10);ctx.lineTo(-2,2);ctx.closePath();ctx.fill();ctx.restore()}
  for(const r of rings){ctx.globalAlpha=clamp(r.life/.45,0,1);ctx.strokeStyle=r.color;ctx.lineWidth=4;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}ctx.save();for(const q of particles){ctx.globalAlpha=clamp(q.life/.6,0,1);ctx.fillStyle=q.color;ctx.fillRect(q.x,q.y,q.size,q.size)}ctx.restore();
  drawThief(p.x,p.y,s.t,Math.hypot(p.vx,p.vy));
  if(!s.launched){if(s.drag){const v=calcLaunch(p,s.pointer);if(v){ctx.strokeStyle='rgba(255,211,61,.95)';ctx.lineWidth=4;ctx.setLineDash([10,10]);ctx.beginPath();let x=p.x,y=p.y,vx=v.vx,vy=v.vy;ctx.moveTo(x,y);for(let i=0;i<18;i++){const dt=.075;vy+=640*dt;x+=vx*dt;y+=vy*dt;ctx.lineTo(x,y)}ctx.stroke();ctx.setLineDash([]);bubble(p.x+95,p.y-82,'LOSLASSEN!','Du wirst entlang der Punkte geschossen.','#ffd33d');}else bubble(p.x+110,p.y-85,'WEITER ZURÜCKZIEHEN','Mehr Abstand = mehr Kraft.','#58d8ff')}
    else if(s.aimHint){const t=(Math.sin(performance.now()/360)+1)/2;const hx=p.x+42+t*80,hy=p.y+45+t*35;ctx.strokeStyle='rgba(255,255,255,.65)';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(p.x+15,p.y+15);ctx.lineTo(hx,hy);ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(hx,hy,15,0,Math.PI*2);ctx.fill();bubble(p.x+120,p.y-90,'1. DIEB ANTIPPEN','2. zurückziehen  ·  3. loslassen','#58d8ff')}}
  if(s.escape){ctx.fillStyle='#43ee91';ctx.font='950 20px sans-serif';ctx.textAlign='left';ctx.fillText('⬅ ZUM ROTEN VAN',260,H-38)}else{ctx.fillStyle='rgba(230,239,250,.82)';ctx.font='900 17px sans-serif';ctx.textAlign='left';ctx.fillText(`SAMMLE ${Math.max(0,L.required-s.got)} EDELSTEIN${L.required-s.got===1?'':'E'}`,34,H-38)}
}
function drawThief(x,y,t,speed){ctx.save();ctx.translate(x,y);const rot=clamp(speed/1400,-1,1)*.35*Math.sin(t*9);ctx.rotate(rot);ctx.shadowColor='rgba(0,0,0,.4)';ctx.shadowBlur=18;ctx.shadowOffsetY=8;ctx.fillStyle='#172033';ctx.beginPath();ctx.arc(0,0,27,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#f0c8a3';ctx.beginPath();ctx.arc(0,-16,15,0,Math.PI*2);ctx.fill();ctx.fillStyle='#161b28';ctx.fillRect(-16,-24,32,10);ctx.fillStyle='#111622';roundedRect(-17,-21,34,12,5);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(-6,-16,3.5,0,Math.PI*2);ctx.arc(6,-16,3.5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#111';ctx.beginPath();ctx.arc(-5,-16,1.8,0,Math.PI*2);ctx.arc(7,-16,1.8,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#202b40';ctx.lineWidth=9;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-7,6);ctx.lineTo(-17,31);ctx.moveTo(7,6);ctx.lineTo(18,30);ctx.stroke();ctx.fillStyle='#bf8a21';ctx.beginPath();ctx.arc(24,4,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffd33d';ctx.font='900 13px sans-serif';ctx.textAlign='center';ctx.fillText('$',24,9);ctx.restore()}
function bubble(x,y,title,sub,color){ctx.save();ctx.font='900 16px sans-serif';const w=260,h=58;ctx.fillStyle='rgba(7,12,22,.9)';roundedRect(x,y,w,h,15);ctx.fill();ctx.strokeStyle=color;ctx.lineWidth=2;ctx.stroke();ctx.fillStyle=color;ctx.textAlign='left';ctx.fillText(title,x+14,y+22);ctx.font='700 12px sans-serif';ctx.fillStyle='#c7d4e6';ctx.fillText(sub,x+14,y+42);ctx.restore()}
function frame(now){const dt=Math.min(.03,(now-last)/1000||.016);last=now;update(dt);draw();requestAnimationFrame(frame)}
ui.play.onclick=()=>{audioCtx?.resume?.();ui.intro.classList.add('hidden');reset(0)};ui.restart.onclick=()=>reset(levelIndex);ui.next.onclick=()=>{ui.result.classList.add('hidden');reset(levelIndex<LEVELS.length-1?levelIndex+1:0)};
reset(0);requestAnimationFrame(frame);
window.__BANDIT_V2__={state:()=>structuredClone(state),reset,complete};