function drawFx(){for(const t of trails){ctx.globalAlpha=clamp(t.life/.5,0,1)*(overclockT>0?.48:(speedBoostT>0?.36:.22));ctx.fillStyle=t.heavy?'#ffd45c':'#8cf8ff';ctx.beginPath();ctx.ellipse(t.x,t.y,t.r*(overclockT>0?1.68:1.18),t.r*(t.heavy?.72:.86),0,0,Math.PI*2);ctx.fill();ctx.globalAlpha*=.55;ctx.beginPath();ctx.ellipse(t.x-t.r*.22,t.y,t.r*(overclockT>0?2.1:1.45),t.r*.38,0,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;for(const r of rings){ctx.globalAlpha=clamp(r.life/r.max,0,1);ctx.strokeStyle=r.color;ctx.lineWidth=4;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,Math.PI*2);ctx.stroke()}ctx.globalAlpha=1;for(const s of shockwaves){ctx.globalAlpha=clamp(s.life/s.max,0,1)*.76;ctx.strokeStyle=s.color;ctx.lineWidth=6;ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.stroke()}if(gatePulse>.02){ctx.save();ctx.globalAlpha=Math.min(.42,gatePulse*.44);ctx.strokeStyle=gateColor;ctx.lineWidth=5;ctx.beginPath();ctx.arc(player.x,player.y,player.r+24+gatePulse*22,0,Math.PI*2);ctx.stroke();ctx.restore()}ctx.globalAlpha=1;for(const p of particles){ctx.globalAlpha=clamp(p.life/.55,0,1);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,Math.max(1.2,p.size*.46),0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;for(const s of sparks){ctx.globalAlpha=clamp(s.life/.35,0,1);ctx.strokeStyle=s.color||'#ffd45c';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.x-s.vx*.026,s.y-s.vy*.026);ctx.stroke()}ctx.globalAlpha=1}
function drawBall(){
 ctx.save();const sy=Math.min(FLOOR-3,player.y+Math.max(38,(FLOOR-player.y)*.2));ctx.globalAlpha=.28;ctx.fillStyle='#000';ctx.beginPath();ctx.ellipse(player.x,sy,player.heavy?30:42,8,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.restore();
 ctx.save();ctx.translate(player.x,player.y);ctx.rotate(player.rot);const sp=clamp(Math.abs(player.vy)/1050,0,.18);if(!player.heavy)ctx.scale(1-sp*.34,1+sp*.88);
 if(player.heavy){const r=player.r;ctx.shadowColor='rgba(255,211,90,.42)';ctx.shadowBlur=26;const g=ctx.createRadialGradient(-8,-10,3,0,0,r+5);g.addColorStop(0,'#fff7da');g.addColorStop(.16,'#dfe3e6');g.addColorStop(.42,'#87909c');g.addColorStop(.74,'#39424f');g.addColorStop(1,'#131a23');ctx.fillStyle=g;ctx.beginPath();for(let i=0;i<14;i++){const aa=-Math.PI/2+i*Math.PI/7,rr=i%2?r:r*.92,xx=Math.cos(aa)*rr,yy=Math.sin(aa)*rr;i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)}ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='rgba(255,222,139,.95)';ctx.lineWidth=2.6;ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.12)';ctx.lineWidth=2;for(let i=0;i<7;i++){const aa=i*Math.PI/3.5;ctx.beginPath();ctx.moveTo(Math.cos(aa)*9,Math.sin(aa)*9);ctx.lineTo(Math.cos(aa)*(r-7),Math.sin(aa)*(r-7));ctx.stroke()}ctx.fillStyle='#ffd769';ctx.shadowColor='#ffd769';ctx.shadowBlur=14;ctx.beginPath();ctx.arc(0,0,6.8,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='rgba(255,255,255,.18)';ctx.lineWidth=1.6;ctx.beginPath();ctx.arc(0,0,r-4,0,Math.PI*2);ctx.stroke();}
 else{const r=player.r;ctx.shadowColor='#83fbff';ctx.shadowBlur=overclockT>0?58:42;const g=ctx.createRadialGradient(-10,-12,4,0,0,r+5);g.addColorStop(0,'#ffffff');g.addColorStop(.2,'#dffeff');g.addColorStop(.52,'#7af1ff');g.addColorStop(.82,'#7084ff');g.addColorStop(1,'#22308e');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='rgba(255,255,255,.78)';ctx.lineWidth=2;ctx.stroke();ctx.strokeStyle='rgba(131,251,255,.42)';ctx.lineWidth=2.5;ctx.beginPath();ctx.arc(0,0,r-6,0,Math.PI*2);ctx.stroke();ctx.save();ctx.rotate(-player.rot*1.8);for(let i=0;i<4;i++){ctx.rotate(Math.PI/2);const al=.26+.16*Math.sin(worldTime*9+i);ctx.strokeStyle='rgba(131,251,255,'+al+')';ctx.lineWidth=2.2;ctx.beginPath();ctx.moveTo(r+6,0);ctx.lineTo(r+16,0);ctx.stroke()}ctx.restore();ctx.fillStyle='rgba(255,255,255,.65)';ctx.beginPath();ctx.arc(-9,-11,5.4,0,Math.PI*2);ctx.fill();}
 if(!player.heavy){ctx.strokeStyle='rgba(131,251,255,'+(speedBoostT>0?.88:.32)+')';ctx.lineWidth=speedBoostT>0?4.2:2;ctx.beginPath();ctx.arc(0,0,player.r+8+Math.sin(worldTime*11)*2.5,0,Math.PI*2);ctx.stroke()}
 if(overclockT>0){ctx.strokeStyle='rgba(255,255,255,.66)';ctx.lineWidth=2.5;ctx.beginPath();ctx.arc(0,0,player.r+12+Math.sin(worldTime*16)*4,0,Math.PI*2);ctx.stroke()}
 ctx.restore();
 if(landingPulse>.02){ctx.save();ctx.globalAlpha=landingPulse*.52;ctx.strokeStyle=player.heavy?'#ffd769':'#83fbff';ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(player.x,FLOOR-2,44+landingPulse*54,10+landingPulse*9,0,0,Math.PI*2);ctx.stroke();ctx.restore()}
}
function drawToast(){if(toastT<=0)return;ctx.save();ctx.globalAlpha=clamp(toastT/.25,0,1);ctx.font='950 15px sans-serif';ctx.textAlign='center';const tx=player.x,ty=Math.max(125,player.y-84),w=Math.max(176,ctx.measureText(toastText).width+36);const g=ctx.createLinearGradient(tx-w/2,0,tx+w/2,0);g.addColorStop(0,'rgba(5,8,14,.86)');g.addColorStop(.5,'rgba(12,18,29,.92)');g.addColorStop(1,'rgba(5,8,14,.86)');ctx.fillStyle=g;round(tx-w/2,ty-21,w,38,19);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.09)';ctx.stroke();ctx.fillStyle=toastText.includes('PERFECT')||toastText.includes('OVERDRIVE')||toastText.includes('OVERCLOCK')?'#ffe68e':'#f7fbff';ctx.fillText(toastText,tx,ty+4);ctx.restore()}
function label(x,y,title,color,sub){ctx.save();ctx.textAlign='center';ctx.font='950 15px sans-serif';const sw=Math.max(170,ctx.measureText(sub).width+34),tw=Math.max(sw,ctx.measureText(title).width+52),w=tw;ctx.fillStyle='rgba(7,11,19,.78)';round(x-w/2,y-28,w,54,15);ctx.fill();ctx.strokeStyle=hexAlpha(color,.35);ctx.lineWidth=1.5;ctx.stroke();ctx.fillStyle=color;ctx.fillText(title,x,y-6);ctx.font='800 9px sans-serif';ctx.fillStyle='rgba(220,232,246,.70)';ctx.fillText(sub,x,y+11);ctx.restore()}
function hexAlpha(hex,a){const h=hex.replace('#','');const n=parseInt(h,16),r=(n>>16)&255,g=(n>>8)&255,b=n&255;return`rgba(${r},${g},${b},${a})`}
