(()=>{
'use strict';

const cv=document.getElementById('game'),c=cv.getContext('2d',{alpha:false});
const ui={
  hud:document.getElementById('hud'),menu:document.getElementById('menu'),pause:document.getElementById('pause'),result:document.getElementById('result'),
  attempt:document.getElementById('attempt'),state:document.getElementById('state'),score:document.getElementById('score'),combo:document.getElementById('combo'),percent:document.getElementById('percent'),bar:document.getElementById('progressBar'),
  start:document.getElementById('startBtn'),sound:document.getElementById('soundBtn'),pauseBtn:document.getElementById('pauseBtn'),resume:document.getElementById('resumeBtn'),menuBtn:document.getElementById('menuBtn'),
  retry:document.getElementById('retryBtn'),resultMenu:document.getElementById('resultMenuBtn'),rank:document.getElementById('rank'),finalScore:document.getElementById('finalScore'),finalTime:document.getElementById('finalTime'),toast:document.getElementById('toast')
};

const H=720,FLOOR=580,HALF=22,SPEED=430,GRAV=2450,HGRAV=4300,JUMP=-1030,SLAM=1280,END=11200,BEAT=60/158;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t;
const view={w:0,h:0,x:0,y:0,dpr:1,sc:1,vw:1280,locked:false};
let mode='menu',attempt=1,time=0,score=0,combo=1,cam=0,shake=0,flash=0,beatPulse=0,lastBeat=-1,holding=false,releaseBuffer=0,coyote=.08,dead=0;
let particles=[],trails=[],rings=[];
let p={x:190,y:FLOOR-HALF,vy:0,ground:true,heavy:false,angle:0,sx:1,sy:1};

const pits=[[1420,170],[2370,150],[3690,190],[4930,160],[6550,220],[7880,170],[9420,220],[10400,180]];
const obs=[
  {t:'spike',x:820,w:58},{t:'spike',x:1120,w:58},{t:'pad',x:1320,w:92},
  {t:'spike',x:1780,w:58},{t:'spike',x:1980,w:58},{t:'wall',x:2200,w:70,h:118},
  {t:'gate',x:2660,w:72,h:185},{t:'spike',x:3040,w:58},{t:'spike',x:3260,w:58},{t:'pad',x:3500,w:92},
  {t:'spike',x:4100,w:58},{t:'wall',x:4380,w:76,h:132},{t:'gate',x:4690,w:70,h:190},
  {t:'spike',x:5310,w:58},{t:'spike',x:5520,w:58},{t:'pad',x:5900,w:92},{t:'spike',x:6220,w:58},
  {t:'gate',x:6900,w:72,h:190},{t:'wall',x:7280,w:78,h:140},{t:'spike',x:7580,w:58},
  {t:'pad',x:8200,w:92},{t:'spike',x:8520,w:58},{t:'spike',x:8750,w:58},{t:'gate',x:9100,w:72,h:194},
  {t:'wall',x:9740,w:82,h:145},{t:'spike',x:10080,w:58},{t:'pad',x:10280,w:92},{t:'spike',x:10820,w:58}
];
const orbs=[1060,1880,2920,3380,4010,4770,5460,6140,6760,7480,8350,8980,9580,10160,10700].map((x,i)=>({x,y:390-(i%3)*58,r:22,hit:false}));
const portals=[2750,5650,8460,10900];
const decorPlatforms=[
  [460,260,240,1],[950,205,210,0],[1570,310,250,1],[2010,230,190,1],[2840,275,260,0],[3330,180,220,1],[3860,300,250,0],
  [4550,220,230,1],[5200,285,250,0],[6060,210,220,1],[6650,300,250,1],[7350,205,260,0],[8060,285,210,1],[8700,190,230,0],
  [9300,300,260,1],[9980,225,250,0],[10580,300,220,1]
];

function viewport(){const vv=window.visualViewport;return {w:Math.max(1,Math.round(vv?.width||innerWidth)),h:Math.max(1,Math.round(vv?.height||innerHeight)),x:Math.round(vv?.offsetLeft||0),y:Math.round(vv?.offsetTop||0)}}
function fit(force=false){if(view.locked&&!force)return;const v=viewport();view.w=v.w;view.h=v.h;view.x=v.x;view.y=v.y;view.dpr=Math.min(2,devicePixelRatio||1);view.sc=view.h/H;view.vw=view.w/view.sc;cv.style.left=view.x+'px';cv.style.top=view.y+'px';cv.style.width=view.w+'px';cv.style.height=view.h+'px';cv.width=Math.max(1,Math.floor(view.w*view.dpr));cv.height=Math.max(1,Math.floor(view.h*view.dpr))}
function freezeView(){fit(true);view.locked=true}function releaseView(){view.locked=false;fit(true)}
addEventListener('resize',()=>fit(false),{passive:true});visualViewport?.addEventListener('resize',()=>fit(false),{passive:true});visualViewport?.addEventListener('scroll',()=>fit(false),{passive:true});addEventListener('orientationchange',()=>{releaseView();setTimeout(()=>fit(true),160)},{passive:true});

class AudioEngine{
  constructor(){this.ctx=null;this.master=null;this.music=null;this.sfx=null;this.muted=localStorage.getItem('hl15-muted')==='1';this.timer=0;this.next=0;this.beat=0;this.noise=null}
  async unlock(){try{if(!this.ctx){const AC=window.AudioContext||window.webkitAudioContext;this.ctx=new AC();this.master=this.ctx.createGain();this.music=this.ctx.createGain();this.sfx=this.ctx.createGain();this.music.gain.value=.24;this.sfx.gain.value=.58;this.master.gain.value=this.muted?0:1;this.music.connect(this.master);this.sfx.connect(this.master);this.master.connect(this.ctx.destination);const b=this.ctx.createBuffer(1,this.ctx.sampleRate*.12,this.ctx.sampleRate);const d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length);this.noise=b;this.next=this.ctx.currentTime+.05;this.timer=setInterval(()=>this.schedule(),45)}if(this.ctx.state!=='running')await this.ctx.resume();return this.ctx.state==='running'}catch(e){return false}}
  toggle(){this.muted=!this.muted;localStorage.setItem('hl15-muted',this.muted?'1':'0');if(this.master&&this.ctx)this.master.gain.setTargetAtTime(this.muted?0:1,this.ctx.currentTime,.015);updateSoundIcon()}
  osc(f,d,type='sine',v=.04,delay=0,dest){if(!this.ctx||this.muted)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),at=this.ctx.currentTime+delay;o.type=type;o.frequency.setValueAtTime(f,at);g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(v,at+.004);g.gain.exponentialRampToValueAtTime(.0001,at+d);o.connect(g).connect(dest||this.sfx);o.start(at);o.stop(at+d+.03)}
  kick(at){if(!this.ctx||this.muted)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sine';o.frequency.setValueAtTime(150,at);o.frequency.exponentialRampToValueAtTime(43,at+.12);g.gain.setValueAtTime(.09,at);g.gain.exponentialRampToValueAtTime(.0001,at+.14);o.connect(g).connect(this.music);o.start(at);o.stop(at+.15)}
  hat(at){if(!this.ctx||this.muted||!this.noise)return;const s=this.ctx.createBufferSource(),g=this.ctx.createGain(),f=this.ctx.createBiquadFilter();s.buffer=this.noise;f.type='highpass';f.frequency.value=6000;g.gain.setValueAtTime(.018,at);g.gain.exponentialRampToValueAtTime(.0001,at+.045);s.connect(f).connect(g).connect(this.music);s.start(at);s.stop(at+.06)}
  schedule(){if(!this.ctx||this.ctx.state!=='running'||mode!=='run')return;while(this.next<this.ctx.currentTime+.18){this.kick(this.next);if(this.beat%2)this.hat(this.next);const roots=[55,65.4,73.4,49];const root=roots[Math.floor(this.beat/4)%roots.length];if(this.beat%2===0)this.osc(root,.18,'triangle',.012,this.next-this.ctx.currentTime,this.music);if(this.beat%8===4)this.osc(root*4,.12,'square',.008,this.next-this.ctx.currentTime,this.music);this.beat++;this.next+=BEAT}}
  event(name){if(!this.ctx)return;const m={jump:[760,.07,'triangle',.06],heavy:[118,.065,'square',.065],land:[92,.05,'sine',.05],hit:[72,.16,'sawtooth',.09],orb:[980,.06,'sine',.045],smash:[84,.11,'square',.08],gate:[620,.09,'triangle',.055],pad:[330,.08,'triangle',.065],start:[520,.06,'triangle',.045],finish:[660,.16,'triangle',.055]};const q=m[name];if(q)this.osc(q[0],q[1],q[2],q[3]);if(name==='finish'){this.osc(825,.16,'triangle',.05,.09);this.osc(990,.2,'triangle',.045,.18)}}
}
const audio=new AudioEngine();
function updateSoundIcon(){ui.sound.textContent=audio.muted?'×':'♪';ui.sound.classList.toggle('muted',audio.muted);ui.sound.setAttribute('aria-label',audio.muted?'Ton einschalten':'Ton ausschalten')}

function reset(keepAttempt=true){time=0;score=0;combo=1;cam=0;shake=flash=beatPulse=0;lastBeat=-1;holding=false;releaseBuffer=0;coyote=.08;dead=0;particles=[];trails=[];rings=[];p={x:190,y:FLOOR-HALF,vy:0,ground:true,heavy:false,angle:0,sx:1,sy:1};for(const o of obs){o.done=false;o.passed=false}for(const o of orbs)o.hit=false;if(!keepAttempt)attempt=1;hud()}
function startGame(){mode='run';freezeView();ui.menu.classList.add('hidden');ui.pause.classList.add('hidden');ui.result.classList.add('hidden');ui.hud.classList.remove('hidden');ui.hud.setAttribute('aria-hidden','false');reset(true);audio.event('start')}
function retry(){attempt++;mode='run';freezeView();ui.result.classList.add('hidden');ui.pause.classList.add('hidden');ui.hud.classList.remove('hidden');reset(true);audio.event('start')}
function backToMenu(){mode='menu';releaseView();ui.menu.classList.remove('hidden');ui.pause.classList.add('hidden');ui.result.classList.add('hidden');ui.hud.classList.add('hidden');reset(false)}
function pauseGame(){if(mode!=='run')return;mode='pause';ui.pause.classList.remove('hidden');ui.hud.classList.add('hidden')}
function resumeGame(){if(mode!=='pause')return;mode='run';ui.pause.classList.add('hidden');ui.hud.classList.remove('hidden');audio.unlock();audio.next=audio.ctx?audio.ctx.currentTime+.05:0}
function finish(){mode='result';ui.hud.classList.add('hidden');ui.result.classList.remove('hidden');const r=score>5400?'S':score>4000?'A':score>2800?'B':'C';ui.rank.textContent=r;ui.finalScore.textContent=String(Math.floor(score)).padStart(6,'0');ui.finalTime.textContent=time.toFixed(2)+'s';audio.event('finish');flash=.9}

function hud(){ui.attempt.textContent=attempt;ui.state.className='state '+(p.heavy?'heavy':'light');ui.state.innerHTML='<span class="stateIcon">'+(p.heavy?'●':'◇')+'</span><span>'+(p.heavy?'HEAVY':'LIGHT')+'</span>';ui.score.textContent=String(Math.floor(score)).padStart(6,'0');ui.combo.textContent=combo+'×';const k=clamp((p.x-190)/(END-190),0,1);ui.percent.textContent=Math.floor(k*100)+'%';ui.bar.style.width=(k*100).toFixed(1)+'%'}
function toast(t,col='#fff'){ui.toast.textContent=t;ui.toast.style.color=col;ui.toast.classList.add('on');clearTimeout(toast.t);toast.t=setTimeout(()=>ui.toast.classList.remove('on'),330)}
function emit(x,y,col,n=12,sp=220,g=200){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=sp*(.25+Math.random()*.85);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.35+Math.random()*.35,max:.7,size:1.5+Math.random()*3.5,col,g})}}
function ring(x,y,col){rings.push({x,y,r:12,life:.28,max:.28,col})}
function setHeavy(h){if(mode!=='run'||holding===h)return;holding=h;if(h){p.heavy=true;if(!p.ground){p.vy=Math.max(p.vy,SLAM);shake=Math.max(shake,3);audio.event('heavy');emit(p.x,p.y,'#ffb02e',8,150,160)}}else{p.heavy=false;releaseBuffer=.12;if(p.ground||coyote>0)jump()}hud()}
function jump(){p.vy=JUMP;p.ground=false;coyote=0;releaseBuffer=0;p.sx=.86;p.sy=1.16;ring(p.x,p.y+HALF,'#63ebff');emit(p.x,p.y+HALF,'#63ebff',14,230,140);audio.event('jump');shake=Math.max(shake,2.4)}
function crash(label){if(dead>0||mode!=='run')return;dead=.55;combo=1;shake=18;flash=.75;emit(p.x,p.y,'#ff4a63',34,340,330);ring(p.x,p.y,'#ff4a63');audio.event('hit');toast(label,'#ff8b9a');try{navigator.vibrate&&navigator.vibrate(18)}catch(e){}}
function reward(label,pts,col){score+=pts+combo*8;combo=Math.min(999,combo+1);toast(label,col);ring(p.x,p.y,col);emit(p.x,p.y,col,10,180,100);hud()}
function floorAt(x){for(const q of pits)if(x>q[0]&&x<q[0]+q[1])return null;return FLOOR}
function spikeHit(o){return p.x+HALF>o.x+5&&p.x-HALF<o.x+o.w-5&&p.y+HALF>FLOOR-55}
function rectHit(o){const y=FLOOR-o.h;return p.x+HALF>o.x&&p.x-HALF<o.x+o.w&&p.y+HALF>y&&p.y-HALF<FLOOR}

function step(dt){if(mode!=='run')return;if(dead>0){dead-=dt;fx(dt);if(dead<=0)retry();return}time+=dt;releaseBuffer=Math.max(0,releaseBuffer-dt);coyote=p.ground?.09:Math.max(0,coyote-dt);p.vy+=(p.heavy?HGRAV:GRAV)*dt;p.x+=SPEED*dt;p.y+=p.vy*dt;p.angle+=SPEED*dt/60;p.sx+=(1-p.sx)*Math.min(1,dt*18);p.sy+=(1-p.sy)*Math.min(1,dt*18);
  const fy=floorAt(p.x);p.ground=false;if(fy!==null&&p.y+HALF>=fy&&p.vy>=0){const imp=p.vy;p.y=fy-HALF;p.vy=0;p.ground=true;coyote=.09;p.angle=Math.round(p.angle/(Math.PI/2))*(Math.PI/2);if(imp>420){p.sx=1.14;p.sy=.86;ring(p.x,fy,p.heavy?'#ffb02e':'#fff');audio.event('land');if(p.heavy){emit(p.x,fy,'#ff9b1e',16,240,320);shake=Math.max(shake,6)}}if(releaseBuffer>0&&!p.heavy)jump()}
  if(p.y>H+90)crash('VOID');
  const bi=Math.floor(time/BEAT);if(bi!==lastBeat){lastBeat=bi;beatPulse=1;score+=3}
  for(const o of obs){if(o.done)continue;if(o.t==='spike'&&spikeHit(o)){crash('SPIKE');break}if(o.t==='wall'&&rectHit(o)){if(p.heavy){o.done=true;reward('SHATTER',190,'#ffb23d');audio.event('smash');shake=Math.max(shake,9);emit(o.x+o.w/2,FLOOR-o.h/2,'#ff7a1a',28,310,300)}else{crash('HOLD');break}}if(o.t==='gate'&&p.x+HALF>o.x&&p.x-HALF<o.x+o.w&&p.y+HALF>FLOOR-o.h){if(p.heavy){crash('RELEASE');break}else{o.done=true;reward('PHASE',175,'#66ebff');audio.event('gate')}}if(o.t==='pad'&&!o.done&&p.x+HALF>o.x&&p.x-HALF<o.x+o.w&&p.y+HALF>FLOOR-24&&p.vy>=0){o.done=true;p.y=FLOOR-HALF;p.vy=-1220;p.ground=false;reward('LAUNCH',150,'#ffd45a');audio.event('pad');emit(p.x,FLOOR,'#ffd45a',22,300,300)}if(!o.passed&&p.x>o.x+o.w+20){o.passed=true;if(o.t==='spike'){score+=90;combo=Math.min(999,combo+1)}}}
  for(const q of orbs){if(!q.hit&&Math.abs(p.x-q.x)<38&&Math.abs(p.y-q.y)<55){q.hit=true;reward('ENERGY',120,'#a6f8ff');audio.event('orb')}}
  if(p.x>=END){finish();return}
  trails.push({x:p.x,y:p.y,life:.23,max:.23,heavy:p.heavy});if(trails.length>40)trails.shift();hud();fx(dt)
}
function fx(dt){shake*=Math.pow(.003,dt);flash*=Math.pow(.001,dt);beatPulse*=Math.pow(.001,dt);for(const q of particles){q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=q.g*dt}particles=particles.filter(q=>q.life>0);for(const q of rings){q.life-=dt;q.r+=430*dt}rings=rings.filter(q=>q.life>0);for(const q of trails)q.life-=dt;trails=trails.filter(q=>q.life>0)}

function section(x){if(x<2800)return 0;if(x<5600)return 1;if(x<8400)return 2;return 3}
const pals=[
  {sky0:'#370018',sky1:'#8f003f',far:'#6a0d54',mid:'#bc126b',edge:'#ff7a1b',lava:'#ff5a00',accent:'#ffb72b',brick:'#281125',glow:'#ff3b69'},
  {sky0:'#10002d',sky1:'#4c087e',far:'#291063',mid:'#7412a6',edge:'#41dfff',lava:'#db28ff',accent:'#63eaff',brick:'#16102f',glow:'#ae4bff'},
  {sky0:'#070b3c',sky1:'#2d0a85',far:'#1f2e85',mid:'#4d20bb',edge:'#46e9ff',lava:'#0e96ff',accent:'#81f2ff',brick:'#101a48',glow:'#536dff'},
  {sky0:'#190008',sky1:'#5c0714',far:'#3a0b20',mid:'#8b122f',edge:'#ffb220',lava:'#ff6a00',accent:'#ffe35a',brick:'#241016',glow:'#ff3d26'}
];
function rr(x,y,w,h,r=8){c.beginPath();c.roundRect?c.roundRect(x,y,w,h,r):c.rect(x,y,w,h)}
function rgba(hex,a){const h=hex.replace('#',''),n=parseInt(h,16);return`rgba(${n>>16&255},${n>>8&255},${n&255},${a})`}
function brickRect(x,y,w,h,pal,edge=true){c.fillStyle=pal.brick;c.fillRect(x,y,w,h);const bh=22,bw=42;c.strokeStyle='rgba(255,255,255,.055)';c.lineWidth=2;for(let yy=y;yy<y+h;yy+=bh){const off=((Math.floor((yy-y)/bh)&1)*bw/2);for(let xx=x-off;xx<x+w;xx+=bw)c.strokeRect(xx,yy,bw,bh)}if(edge){c.fillStyle=pal.edge;c.fillRect(x,y, w,6);c.fillStyle=rgba(pal.edge,.18);c.fillRect(x,y+6,w,10)}}
function drawLava(camX,vw,pal){const y=642;c.fillStyle=pal.lava;c.fillRect(camX,y,vw,H-y);c.strokeStyle=pal.accent;c.lineWidth=4;c.shadowBlur=14;c.shadowColor=pal.lava;c.beginPath();for(let x=camX-30;x<=camX+vw+30;x+=20){const yy=y+Math.sin(x*.028+time*3.2)*6+Math.sin(x*.071-time*2.1)*3;x===camX-30?c.moveTo(x,yy):c.lineTo(x,yy)}c.stroke();c.shadowBlur=0;for(let x=Math.floor(camX/120)*120;x<camX+vw+120;x+=120){const bob=(Math.sin(time*2+x)*.5+.5)*10;c.fillStyle=rgba(pal.accent,.5);c.fillRect(x+40,y+18-bob,5,5);c.fillRect(x+52,y+29-bob,3,3)}}
function drawMountains(camX,vw,pal){c.save();c.translate(camX*.18,0);c.fillStyle=rgba(pal.far,.75);c.beginPath();c.moveTo(camX*.82,480);for(let x=camX*.82-200;x<camX*.82+vw+500;x+=180){const h=90+((Math.sin(x*.011)+1)*55);c.lineTo(x+90,480-h);c.lineTo(x+180,480)}c.lineTo(camX*.82+vw+500,520);c.lineTo(camX*.82-200,520);c.closePath();c.fill();c.restore();c.save();c.translate(camX*.35,0);c.fillStyle=rgba(pal.mid,.42);c.beginPath();c.moveTo(camX*.65-200,530);for(let x=camX*.65-200;x<camX*.65+vw+500;x+=140){const h=65+((Math.cos(x*.013)+1)*38);c.lineTo(x+70,530-h);c.lineTo(x+140,530)}c.lineTo(camX*.65+vw+500,560);c.lineTo(camX*.65-200,560);c.closePath();c.fill();c.restore()}
function drawTempleSilhouette(camX,vw,pal){c.save();c.globalAlpha=.28;c.fillStyle='#09000f';for(let x=Math.floor((camX*.52)/420)*420-500;x<camX*.52+vw+700;x+=420){const sx=x+camX*.48;c.fillRect(sx,250,70,300);c.fillRect(sx-35,240,140,24);c.fillRect(sx-12,205,94,36);c.beginPath();c.moveTo(sx-25,205);c.lineTo(sx+35,150);c.lineTo(sx+95,205);c.fill()}c.restore();
  c.save();c.strokeStyle=rgba(pal.accent,.13);c.lineWidth=8;for(let x=Math.floor(camX/340)*340-300;x<camX+vw+300;x+=340){c.beginPath();for(let y=0;y<360;y+=22){c.moveTo(x,y);c.lineTo(x+8,y+11);c.lineTo(x,y+22)}c.stroke()}c.restore()}
function drawStars(camX,vw,pal){for(let i=0;i<42;i++){const x=camX+((i*193+Math.floor(camX*.15))%(vw+140))-70,y=80+((i*71)%360);const a=.12+((i%5)*.035);c.fillStyle=rgba(i%4===0?pal.accent:'#fff',a);const s=i%7===0?3:2;c.fillRect(x,y,s,s)}}
function drawGround(camX,vw,pal){const start=Math.floor((camX-100)/48)*48,end=camX+vw+130;for(let x=start;x<end;x+=48){if(floorAt(x+24)===null)continue;c.fillStyle=pal.brick;c.fillRect(x,FLOOR,48,64);c.fillStyle=pal.edge;c.fillRect(x,FLOOR,48,6);c.fillStyle=rgba(pal.edge,.2);c.fillRect(x,FLOOR+6,48,8);c.strokeStyle='rgba(255,255,255,.045)';c.strokeRect(x,FLOOR+15,48,25);c.strokeRect(x+12,FLOOR+40,36,24)}drawLava(camX,vw,pal)}
function drawPlatform(x,y,w,spikes,pal){brickRect(x,y,w,48,pal);c.fillStyle='#080510';c.fillRect(x+24,y+48,w-48,20);if(spikes){for(let px=x+16;px<x+w-16;px+=30){c.fillStyle='#eaf8ff';c.beginPath();c.moveTo(px,y+48);c.lineTo(px+12,y+76);c.lineTo(px+24,y+48);c.fill()}}c.strokeStyle='rgba(8,3,16,.8)';c.lineWidth=8;c.beginPath();c.moveTo(x+w*.5,y-220);c.lineTo(x+w*.5,y);c.stroke();c.strokeStyle=rgba(pal.accent,.15);c.lineWidth=2;c.stroke()}
function drawTorch(x,y,pal){c.fillStyle='#251226';c.fillRect(x-8,y,16,34);c.fillStyle=pal.accent;c.fillRect(x-11,y-5,22,8);const flick=Math.sin(time*11+x)*6;c.shadowBlur=18;c.shadowColor=pal.edge;c.fillStyle=pal.edge;c.beginPath();c.moveTo(x,y-8);c.quadraticCurveTo(x-18,y-28,x+flick*.2,y-46-flick);c.quadraticCurveTo(x+18,y-28,x,y-8);c.fill();c.fillStyle='#fff06b';c.beginPath();c.moveTo(x,y-10);c.quadraticCurveTo(x-8,y-25,x,y-34);c.quadraticCurveTo(x+8,y-25,x,y-10);c.fill();c.shadowBlur=0}
function drawPortal(x,y,pal){const pulse=1+Math.sin(time*5+x)*.05;c.save();c.translate(x,y);c.scale(pulse,pulse);c.shadowBlur=24;c.shadowColor=pal.accent;c.strokeStyle=pal.accent;c.lineWidth=8;c.beginPath();c.ellipse(0,0,28,62,0,0,Math.PI*2);c.stroke();c.shadowBlur=0;c.strokeStyle=rgba('#ffffff',.35);c.lineWidth=3;c.beginPath();c.ellipse(0,0,18,50,0,0,Math.PI*2);c.stroke();c.fillStyle='rgba(3,0,12,.8)';c.beginPath();c.ellipse(0,0,14,45,0,0,Math.PI*2);c.fill();for(let i=0;i<8;i++){const a=time*1.8+i*Math.PI/4;c.fillStyle=i%2?pal.edge:pal.accent;c.fillRect(Math.cos(a)*42-3,Math.sin(a)*68-3,6,6)}c.restore()}
function drawOrb(q,pal){if(q.hit)return;const s=1+Math.sin(time*6+q.x)*.08;c.save();c.translate(q.x,q.y);c.scale(s,s);c.shadowBlur=26;c.shadowColor=pal.accent;c.fillStyle='#dfffff';c.beginPath();c.arc(0,0,10,0,Math.PI*2);c.fill();c.strokeStyle=pal.accent;c.lineWidth=6;c.beginPath();c.arc(0,0,24,0,Math.PI*2);c.stroke();c.strokeStyle=rgba(pal.accent,.38);c.lineWidth=3;for(let i=0;i<4;i++){const a=i*Math.PI/2+time*.7;c.beginPath();c.arc(0,0,36,a+.16,a+1.12);c.stroke()}c.shadowBlur=0;c.restore()}
function drawSpike(o,pal){for(let x=o.x;x<o.x+o.w;x+=29){c.shadowBlur=12;c.shadowColor=pal.edge;const g=c.createLinearGradient(0,FLOOR-58,0,FLOOR);g.addColorStop(0,'#f6fbff');g.addColorStop(.45,pal.accent);g.addColorStop(1,pal.edge);c.fillStyle=g;c.beginPath();c.moveTo(x,FLOOR);c.lineTo(x+14.5,FLOOR-58);c.lineTo(x+29,FLOOR);c.fill();c.shadowBlur=0;c.strokeStyle='rgba(0,0,0,.45)';c.lineWidth=3;c.stroke()}}
function drawWall(o,pal){if(o.done)return;brickRect(o.x,FLOOR-o.h,o.w,o.h,pal);c.fillStyle=pal.accent;c.fillRect(o.x+10,FLOOR-o.h+20,o.w-20,8);c.fillStyle='#05000a';c.font='900 25px monospace';c.fillText('✦',o.x+o.w/2-14,FLOOR-o.h/2+10)}
function drawGate(o,pal){if(o.done)return;const x=o.x+o.w/2,y=FLOOR-o.h/2;c.save();c.translate(x,y);c.shadowBlur=24;c.shadowColor='#59eaff';c.strokeStyle='#61eaff';c.lineWidth=7;c.beginPath();c.ellipse(0,0,25,o.h*.46,0,0,Math.PI*2);c.stroke();c.shadowBlur=0;c.strokeStyle='rgba(255,255,255,.36)';c.lineWidth=2;c.beginPath();c.ellipse(0,0,16,o.h*.4,0,0,Math.PI*2);c.stroke();for(let i=0;i<7;i++){const a=time*2+i*.9;c.fillStyle=i%2?'#7d63ff':'#70f3ff';c.fillRect(Math.cos(a)*38-3,Math.sin(a)*o.h*.47-3,6,6)}c.restore()}
function drawPad(o,pal){if(o.done)return;c.shadowBlur=18;c.shadowColor='#ffd45a';c.fillStyle='#ffe35d';c.fillRect(o.x,FLOOR-10,o.w,10);c.shadowBlur=0;c.fillStyle='#ff7a1b';for(let i=0;i<3;i++){const x=o.x+18+i*24;c.beginPath();c.moveTo(x,FLOOR-18);c.lineTo(x+10,FLOOR-30);c.lineTo(x+20,FLOOR-18);c.fill()}}
function drawDecor(camX,vw,pal){for(const d of decorPlatforms){if(d[0]+d[2]<camX-100||d[0]>camX+vw+100)continue;drawPlatform(d[0],d[1],d[2],d[3],pal);if((d[0]/10|0)%2===0)drawTorch(d[0]+35,d[1]-8,pal)}for(let x=Math.floor(camX/620)*620-620;x<camX+vw+620;x+=620){if((x/620|0)%2===0)drawTorch(x+120,520,pal)}}
function drawEffects(){for(const t of trails){const a=t.life/t.max;c.save();c.globalAlpha=a*.48;c.translate(t.x,t.y);c.rotate(p.angle*.5);c.fillStyle=t.heavy?'#ff9b1e':'#50e8ff';c.fillRect(-22-70*(1-a),-12,44+70*(1-a),24);c.restore()}for(const r of rings){c.globalAlpha=clamp(r.life/r.max,0,1);c.strokeStyle=r.col;c.lineWidth=4;c.beginPath();c.arc(r.x,r.y,r.r,0,Math.PI*2);c.stroke()}c.globalAlpha=1;for(const q of particles){c.globalAlpha=clamp(q.life/q.max,0,1);c.fillStyle=q.col;c.fillRect(q.x-q.size/2,q.y-q.size/2,q.size,q.size)}c.globalAlpha=1}
function drawPlayer(){c.save();c.translate(p.x,p.y);c.rotate(p.angle);c.scale(p.sx,p.sy);const col=p.heavy?'#ffae2f':'#54e8ff',col2=p.heavy?'#ff4f18':'#7a65ff';c.shadowBlur=p.heavy?24:26;c.shadowColor=col;const g=c.createLinearGradient(-HALF,-HALF,HALF,HALF);g.addColorStop(0,'#efffff');g.addColorStop(.18,col);g.addColorStop(1,col2);c.fillStyle=g;rr(-HALF,-HALF,HALF*2,HALF*2,7);c.fill();c.shadowBlur=0;c.lineWidth=4;c.strokeStyle='#07101a';c.stroke();c.lineWidth=2;c.strokeStyle='rgba(255,255,255,.72)';rr(-HALF+4,-HALF+4,HALF*2-8,HALF*2-8,5);c.stroke();c.fillStyle='#07101a';c.fillRect(-9,-5,6,7);c.fillRect(6,-5,6,7);c.fillRect(-6,9,15,4);c.fillStyle='#dfffff';c.fillRect(-7,-4,2,2);c.fillRect(8,-4,2,2);c.restore()}
function render(){const d=view.dpr,sc=view.sc;c.setTransform(1,0,0,1,0,0);c.fillStyle='#05000b';c.fillRect(0,0,cv.width,cv.height);c.setTransform(d*sc,0,0,d*sc,0,0);const desired=Math.max(0,p.x-Math.min(360,view.vw*.28));cam=lerp(cam,desired,.14);const pal=pals[section(p.x)];const sky=c.createLinearGradient(0,0,0,H);sky.addColorStop(0,pal.sky0);sky.addColorStop(.45,pal.sky1);sky.addColorStop(1,'#09000f');c.fillStyle=sky;c.fillRect(cam,0,view.vw,H);drawMountains(cam,view.vw,pal);drawTempleSilhouette(cam,view.vw,pal);drawStars(cam,view.vw,pal);c.save();if(shake>.1)c.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);drawDecor(cam,view.vw,pal);drawGround(cam,view.vw,pal);for(const q of orbs)if(q.x>cam-80&&q.x<cam+view.vw+80)drawOrb(q,pal);for(const x of portals)if(x>cam-120&&x<cam+view.vw+120)drawPortal(x,395,pal);for(const o of obs){if(o.x+o.w<cam-100||o.x>cam+view.vw+100)continue;if(o.t==='spike')drawSpike(o,pal);else if(o.t==='wall')drawWall(o,pal);else if(o.t==='gate')drawGate(o,pal);else if(o.t==='pad')drawPad(o,pal)}drawEffects();drawPlayer();c.restore();c.setTransform(1,0,0,1,0,0);if(beatPulse>.01){c.fillStyle=`rgba(255,255,255,${beatPulse*.025})`;c.fillRect(0,0,cv.width,cv.height)}if(flash>.01){c.fillStyle=`rgba(255,255,255,${Math.min(.32,flash*.36)})`;c.fillRect(0,0,cv.width,cv.height)}const vg=c.createRadialGradient(cv.width*.5,cv.height*.5,cv.height*.14,cv.width*.5,cv.height*.5,cv.width*.68);vg.addColorStop(0,'rgba(0,0,0,0)');vg.addColorStop(1,'rgba(0,0,0,.38)');c.fillStyle=vg;c.fillRect(0,0,cv.width,cv.height)}

let last=performance.now();function loop(now){const dt=Math.min(.032,(now-last)/1000);last=now;step(dt);render();requestAnimationFrame(loop)}

cv.addEventListener('pointerdown',e=>{if(mode!=='run')return;e.preventDefault();audio.unlock();setHeavy(true)},{passive:false});addEventListener('pointerup',e=>{if(mode!=='run')return;e.preventDefault();setHeavy(false)},{passive:false});addEventListener('pointercancel',()=>{if(mode==='run')setHeavy(false)},{passive:true});
addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat){e.preventDefault();if(mode==='menu'){audio.unlock();startGame()}else setHeavy(true)}if(e.code==='Escape'){if(mode==='run')pauseGame();else if(mode==='pause')resumeGame()}},{passive:false});addEventListener('keyup',e=>{if(e.code==='Space'){e.preventDefault();setHeavy(false)}},{passive:false});
ui.start.addEventListener('pointerdown',()=>audio.unlock(),{passive:true});ui.start.addEventListener('click',()=>{audio.unlock();startGame()});ui.sound.addEventListener('pointerdown',e=>{e.stopPropagation();audio.unlock()},{passive:true});ui.sound.addEventListener('click',e=>{e.stopPropagation();audio.toggle()});ui.pauseBtn.addEventListener('click',e=>{e.stopPropagation();pauseGame()});ui.resume.addEventListener('pointerdown',()=>audio.unlock(),{passive:true});ui.resume.addEventListener('click',resumeGame);ui.menuBtn.addEventListener('click',backToMenu);ui.retry.addEventListener('pointerdown',()=>audio.unlock(),{passive:true});ui.retry.addEventListener('click',retry);ui.resultMenu.addEventListener('click',backToMenu);
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&audio.ctx?.state==='suspended')audio.ctx.resume().catch(()=>{});if(document.hidden&&mode==='run')pauseGame()});

fit(true);updateSoundIcon();reset(true);requestAnimationFrame(loop);
window.__HL15__={state:()=>({mode,attempt,time,score,combo,x:p.x,y:p.y,vy:p.vy,heavy:p.heavy,cam,view:{...view},audio:audio.ctx?audio.ctx.state:'none'}),start:startGame,pause:pauseGame,resume:resumeGame};
})();
