const starter=[
{id:'s1',fr:'bonjour',de:'guten Tag',emoji:'👋',unit:'Unité 1 · Bonjour',score:0,seen:0},
{id:'s2',fr:'très bien',de:'sehr gut',emoji:'⭐',unit:'Unité 1 · Bonjour',score:0,seen:0},
{id:'s3',fr:'un',de:'eins',emoji:'1️⃣',unit:'Unité 1 · Bonjour',score:0,seen:0},
{id:'s4',fr:'merci',de:'danke',emoji:'🙏',unit:'Unité 1 · Bonjour',score:0,seen:0},
{id:'s5',fr:'Comment ça va ?',de:'Wie geht es?',emoji:'🙂',unit:'Unité 1 · Bonjour',score:0,seen:0},
{id:'s6',fr:'trois',de:'drei',emoji:'3️⃣',unit:'Unité 1 · Bonjour',score:0,seen:0},
{id:'s7',fr:'deux',de:'zwei',emoji:'2️⃣',unit:'Unité 1 · Bonjour',score:0,seen:0},
{id:'s8',fr:'quatre',de:'vier',emoji:'🍀',unit:'Unité 1 · Bonjour',score:0,seen:0}
];
let words=loadWords();let deck=[],deckIndex=0,quizMode='listen',quizDeck=[],quizIndex=0,quizLocked=false,currentQuiz=null;
function loadWords(){try{const x=JSON.parse(localStorage.getItem('salut_words')||'null');if(Array.isArray(x)&&x.length)return x}catch(e){}return starter.map(x=>({...x}))}
function saveWords(){localStorage.setItem('salut_words',JSON.stringify(words));updateStats();renderWordList()}
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.nav===id||(id==='add'&&n.dataset.nav==='manage')));window.scrollTo({top:0,behavior:'smooth'});if(id==='manage')renderWordList();if(id==='home')updateStats()}
function updateStats(){document.getElementById('statWords').textContent=words.length;const known=words.filter(w=>(w.score||0)>=4).length;document.getElementById('statKnown').textContent=known;const stars=words.reduce((a,w)=>a+Math.min(3,Math.floor((w.score||0)/2)),0);document.getElementById('statStars').textContent=stars+' ⭐'}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function startCards(){if(!words.length)return toast('Füge zuerst Wörter hinzu.');deck=shuffle(words).sort((a,b)=>(a.score||0)-(b.score||0));deckIndex=0;showScreen('learn');renderCard()}
function renderCard(){const w=deck[deckIndex];if(!w){showScreen('home');toast('Runde geschafft! 🎉');return}document.getElementById('cardUnit').textContent=w.unit||'Meine Wörter';document.getElementById('cardEmoji').textContent=w.emoji||'💬';document.getElementById('cardFr').textContent=w.fr;document.getElementById('cardDe').textContent=w.de;document.getElementById('cardDe').classList.remove('show');document.getElementById('revealWrap').style.display='block';document.getElementById('ratingWrap').style.display='none';document.getElementById('learnPrompt').textContent='Hör dir das Wort an und überlege die Bedeutung.';document.getElementById('learnCount').textContent=(deckIndex+1)+'/'+deck.length;document.getElementById('learnProgress').style.width=((deckIndex)/deck.length*100)+'%';setTimeout(()=>speak(w.fr,'fr-FR'),260)}
function revealCard(){document.getElementById('cardDe').classList.add('show');document.getElementById('revealWrap').style.display='none';document.getElementById('ratingWrap').style.display='grid';document.getElementById('learnPrompt').textContent='Wie sicher war die Antwort?'}
function rateCard(v){const d=deck[deckIndex];const w=words.find(x=>x.id===d.id);if(w){w.seen=(w.seen||0)+1;if(v===2)w.score=Math.min(8,(w.score||0)+2);else if(v===1)w.score=Math.min(8,(w.score||0)+1);else w.score=Math.max(0,(w.score||0)-1);saveWords()}deckIndex++;renderCard()}
function speakCurrent(){const w=deck[deckIndex];if(w)speak(w.fr,'fr-FR')}
function getVoice(lang){const voices=speechSynthesis.getVoices();return voices.find(v=>v.lang&&v.lang.toLowerCase().startsWith(lang.toLowerCase().slice(0,2)))||null}
function speak(text,lang='fr-FR'){if(!('speechSynthesis'in window))return toast('Sprachausgabe wird hier nicht unterstützt.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang;u.rate=.82;u.pitch=1;const v=getVoice(lang);if(v)u.voice=v;speechSynthesis.speak(u)}

function startQuiz(mode){if(words.length<2)return toast('Mindestens 2 Wörter nötig.');quizMode=mode;quizDeck=shuffle(words).slice(0,Math.min(10,words.length));quizIndex=0;quizLocked=false;showScreen('quiz');document.getElementById('quizTitle').textContent=mode==='listen'?'Hören & verstehen':'Mini-Quiz';renderQuiz()}
function renderQuiz(){if(quizIndex>=quizDeck.length){showScreen('home');toast('Quiz geschafft! ⭐');return}quizLocked=false;const w=quizDeck[quizIndex];currentQuiz=w;document.getElementById('quizCount').textContent=(quizIndex+1)+'/'+quizDeck.length;document.getElementById('quizProgress').style.width=(quizIndex/quizDeck.length*100)+'%';document.getElementById('quizFeedback').textContent='';const big=document.getElementById('quizBig'),sbtn=document.getElementById('quizSpeak'),inst=document.getElementById('quizInstruction');if(quizMode==='listen'){big.textContent='🔊 Hör genau hin';sbtn.style.display='inline-block';inst.textContent='Welche deutsche Bedeutung hast du gehört?';setTimeout(()=>speak(w.fr,'fr-FR'),250)}else{big.textContent=w.de;sbtn.style.display='none';inst.textContent='Welches französische Wort passt?'}
const correct=quizMode==='listen'?w.de:w.fr;const pool=shuffle(words.filter(x=>x.id!==w.id)).slice(0,3).map(x=>quizMode==='listen'?x.de:x.fr);const opts=shuffle([correct,...pool]);const wrap=document.getElementById('quizOptions');wrap.innerHTML='';opts.forEach(t=>{const b=document.createElement('button');b.className='option';b.textContent=t;b.onclick=()=>answerQuiz(b,t,correct);wrap.appendChild(b)})}
function speakQuiz(){if(currentQuiz)speak(currentQuiz.fr,'fr-FR')}
function answerQuiz(btn,answer,correct){if(quizLocked)return;quizLocked=true;document.querySelectorAll('#quizOptions .option').forEach(b=>{if(b.textContent===correct)b.classList.add('correct')});if(answer===correct){btn.classList.add('correct');document.getElementById('quizFeedback').textContent='Richtig! ⭐';const w=words.find(x=>x.id===currentQuiz.id);if(w){w.score=Math.min(8,(w.score||0)+1);w.seen=(w.seen||0)+1;saveWords()}}else{btn.classList.add('wrong');document.getElementById('quizFeedback').textContent='Fast – die richtige Antwort ist markiert.'}setTimeout(()=>{quizIndex++;renderQuiz()},1050)}

function addManual(){const fr=document.getElementById('manualFr').value.trim(),de=document.getElementById('manualDe').value.trim();if(!fr||!de)return toast('Bitte beide Felder ausfüllen.');words.push({id:'u'+Date.now(),fr,de,emoji:'💬',unit:'Meine Wörter',score:0,seen:0});saveWords();document.getElementById('manualFr').value='';document.getElementById('manualDe').value='';toast('Wort gespeichert. ✓')}
function renderWordList(){const box=document.getElementById('wordList');if(!box)return;if(!words.length){box.innerHTML='<div class="empty">Noch keine Wörter gespeichert.</div>';return}box.innerHTML='';words.forEach(w=>{const row=document.createElement('div');row.className='wordItem';row.innerHTML=`<div><b>${html(w.fr)} → ${html(w.de)}</b><small>${w.score>=4?'Sicher gelernt':'Noch üben'} · ${w.seen||0}× gesehen</small></div><div class="mini"><button title="Vorlesen">🔊</button><button title="Löschen">🗑️</button></div>`;const [sp,del]=row.querySelectorAll('button');sp.onclick=()=>speak(w.fr,'fr-FR');del.onclick=()=>{words=words.filter(x=>x.id!==w.id);saveWords()};box.appendChild(row)})}
function html(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function resetProgress(){words=words.map(w=>({...w,score:0,seen:0}));saveWords();toast('Lernfortschritt zurückgesetzt.')}
function restoreStarter(){if(!confirm('Alle selbst hinzugefügten Wörter löschen und nur die 8 Startwörter behalten?'))return;words=starter.map(x=>({...x}));saveWords();toast('Startwörter wiederhergestellt.')}
function toast(t){const el=document.getElementById('toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1900)}
window.speechSynthesis?.getVoices();window.speechSynthesis?.addEventListener?.('voiceschanged',()=>{});updateStats();renderWordList();
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
