function previewPhoto(input,imgId){const img=document.getElementById(imgId),label=document.querySelector('label[for="'+input.id+'"]');if(img.dataset.url)URL.revokeObjectURL(img.dataset.url);const f=input.files&&input.files[0];if(!f){img.removeAttribute('src');img.classList.remove('show');if(label)label.textContent='📷 Foto aufnehmen / auswählen';return}const u=URL.createObjectURL(f);img.dataset.url=u;img.src=u;img.classList.add('show');if(label)label.textContent='📷 Foto ändern';document.getElementById('scanMeta').classList.remove('show')}

function cleanOCRLine(s){s=String(s||'').replace(/[|_~`^\\&“”"«»]+/g,' ').replace(/\s+/g,' ').trim();s=s.replace(/^[-–—:;,.]+|[-–—:;,.]+$/g,'').trim();s=s.replace(/^(?:F[\s.,;:-]*H[\s.,;:-]*|FH[\s.,;:-]*)/i,'').trim();let t=s.split(/\s+/).filter(Boolean);while(t.length>1&&/^\d+[.,;:!?]*$/.test(t[0]))t.shift();while(t.length>1&&/^\d+[.,;:!?]*$/.test(t[t.length-1]))t.pop();const hasLower=()=>/[a-zà-ÿ]/.test(t.join(''));while(t.length>1&&hasLower()&&/^[A-ZÀ-Ý]{1,3}[.,;:!?]*$/.test(t[0]))t.shift();while(t.length>1&&hasLower()&&/^[A-ZÀ-Ý]{1,2}[.,;:!?]*$/.test(t[t.length-1]))t.pop();return t.join(' ').replace(/\s+([?!.,])/g,'$1').trim()}
function validOCRLine(s){if(!s||s.length<2||s.length>36)return false;if(!/[A-Za-zÀ-ÿ]/.test(s))return false;if(/^\d+$/.test(s))return false;if(/^[A-ZÀ-Ý]{1,3}$/.test(s))return false;if(/(unité|klett|balmer|bolmer|cartes|vocabulaire|©|2021|xero|https|www|qr)/i.test(s))return false;if(/([A-ZÀ-Ý])\1{3,}/.test(s))return false;const letters=(s.match(/[A-Za-zÀ-ÿ]/g)||[]).length;return letters/Math.max(1,s.length)>.48}
function textScore(s,lang){const letters=(s.match(/[A-Za-zÀ-ÿ]/g)||[]).length,lower=(s.match(/[a-zà-ÿ]/g)||[]).length,wordCount=s.split(/\s+/).filter(Boolean).length;let score=letters+lower*1.7;if(wordCount<=4)score+=4;if(/[?!]$/.test(s))score+=2;if(/[éèêëàâäçùûüîïôöœ]/i.test(s))score+=1.5;if(/^[A-ZÀ-Ý\s]{4,}$/.test(s))score-=16;if(/\b[A-ZÀ-Ý]{2,3}\b/.test(s))score-=11;if(/[A-ZÀ-Ý]{4,}/.test(s))score-=9;if(/[^A-Za-zÀ-ÿ0-9'’ ?!.,-]/.test(s))score-=6;if(lang==='de'&&/^[A-ZÄÖÜ][a-zäöüß]+(?:\s|$)/.test(s))score+=1;return score}
function extractMainText(text,lang){let lines=String(text||'').split(/\n+/).map(cleanOCRLine).filter(validOCRLine);lines=[...new Set(lines)];const combos=[];if(lang==='fr'){for(let i=0;i<lines.length-1;i++){const a=lines[i],b=lines[i+1];if(/^[A-ZÀ-Ý]/.test(a)&&!/\b[A-ZÀ-Ý]{2,3}\b/.test(a)&&textScore(a,lang)>12&&!/[.!?]$/.test(a)&&b.length<=8&&/^[A-Za-zÀ-ÿ'’ -]+[?!]?$/.test(b)){const c=(a+' '+b).replace(/\s+\?/g,'?');if(c.length<=32)combos.push(c)}}}const all=[...lines,...combos];if(!all.length)return'';all.sort((a,b)=>textScore(b,lang)-textScore(a,lang));return all[0].replace(/\s+([?!.,])/g,'$1').trim()}

function lowRuns(arr,threshold,minLen){const out=[];let start=-1;for(let i=0;i<arr.length;i++){if(arr[i]<threshold&&start<0)start=i;if((arr[i]>=threshold||i===arr.length-1)&&start>=0){const end=arr[i]>=threshold?i-1:i;if(end-start+1>=minLen)out.push([start,end]);start=-1}}return out}
function gapsToIntervals(gaps,total){const out=[];for(let i=0;i<gaps.length-1;i++){const a=gaps[i][1]+1,b=gaps[i+1][0]-1;if(b-a>total*.08)out.push([a,b])}return out}
async function loadBitmap(file){if(window.createImageBitmap)return await createImageBitmap(file);return await new Promise((resolve,reject)=>{const im=new Image(),u=URL.createObjectURL(file);im.onload=()=>{URL.revokeObjectURL(u);resolve(im)};im.onerror=e=>{URL.revokeObjectURL(u);reject(e)};im.src=u})}
async function analyzeSheet(file){const bitmap=await loadBitmap(file);const maxDim=900,scale=Math.min(1,maxDim/Math.max(bitmap.width,bitmap.height));const w=Math.max(1,Math.round(bitmap.width*scale)),h=Math.max(1,Math.round(bitmap.height*scale));const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(bitmap,0,0,w,h);const d=x.getImageData(0,0,w,h).data,row=new Uint32Array(h),col=new Uint32Array(w);for(let yy=0;yy<h;yy++){for(let xx=0;xx<w;xx++){const i=(yy*w+xx)*4;if(Math.max(d[i],d[i+1],d[i+2])>125){row[yy]++;col[xx]++}}}const rowFrac=Array.from(row,v=>v/w),colFrac=Array.from(col,v=>v/h);let rg=lowRuns(rowFrac,.10,Math.max(5,Math.round(h*.006))),cg=lowRuns(colFrac,.10,Math.max(5,Math.round(w*.006)));let rows=gapsToIntervals(rg,h),cols=gapsToIntervals(cg,w);if(rows.length<1||cols.length<1||rows.length*cols.length>20){rows=[[0,h-1]];cols=[[0,w-1]]}const boxes=[];for(let r=0;r<rows.length;r++){for(let cidx=0;cidx<cols.length;cidx++){const [y0,y1]=rows[r],[x0,x1]=cols[cidx];let bright=0;for(let yy=y0;yy<=y1;yy+=2){for(let xx=x0;xx<=x1;xx+=2){const i=(yy*w+xx)*4;if(Math.max(d[i],d[i+1],d[i+2])>125)bright++}}const sampled=Math.ceil((y1-y0+1)/2)*Math.ceil((x1-x0+1)/2),occ=bright/Math.max(1,sampled);if(occ>.24){boxes.push({row:r,col:cidx,key:r+'-'+cidx,x:x0/w,y:y0/h,w:(x1-x0+1)/w,h:(y1-y0+1)/h})}}}if(!boxes.length)boxes.push({row:0,col:0,key:'0-0',x:0,y:0,w:1,h:1});return{bitmap,boxes,rows:rows.length,cols:cols.length}}
function cropForOCR(sheet,box,lang,full=false){const b=sheet.bitmap,px=box.x*b.width,py=box.y*b.height,pw=box.w*b.width,ph=box.h*b.height;let rx=full?.03:.04,ry=full?.08:(lang==='fr'?.25:.26),rw=full?.94:(lang==='fr'?.48:.74),rh=full?.84:(lang==='fr'?.53:.55);const sx=px+pw*rx,sy=py+ph*ry,sw=pw*rw,sh=ph*rh,scale=Math.min(3,Math.max(1.7,850/Math.max(1,sw)));const c=document.createElement('canvas');c.width=Math.max(240,Math.round(sw*scale));c.height=Math.max(130,Math.round(sh*scale));const x=c.getContext('2d',{willReadFrequently:true});x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.drawImage(b,sx,sy,sw,sh,0,0,c.width,c.height);const id=x.getImageData(0,0,c.width,c.height),a=id.data;for(let i=0;i<a.length;i+=4){const g=.299*a[i]+.587*a[i+1]+.114*a[i+2],v=Math.max(0,Math.min(255,(g-128)*1.25+128));a[i]=a[i+1]=a[i+2]=v}x.putImageData(id,0,0);return c}
async function recognizeSheet(sheet,lang,label,statusEl){const worker=await Tesseract.createWorker(lang==='fr'?'fra':'deu',1,{logger:m=>{if(m.status==='recognizing text'&&recognizeSheet.current){statusEl.innerHTML='<span class="scanBusy"><span class="scanDot"></span>'+label+' '+recognizeSheet.current+' · '+Math.round((m.progress||0)*100)+' %</span>'}}});try{await worker.setParameters({tessedit_pageseg_mode:'6',preserve_interword_spaces:'1'});const out=[];for(let i=0;i<sheet.boxes.length;i++){recognizeSheet.current=(i+1)+'/'+sheet.boxes.length;const box=sheet.boxes[i];let res=await worker.recognize(cropForOCR(sheet,box,lang,false)),text=extractMainText(res.data.text,lang);if(!text){res=await worker.recognize(cropForOCR(sheet,box,lang,true));text=extractMainText(res.data.text,lang)}out.push({key:box.key,row:box.row,col:box.col,text})}return out}finally{recognizeSheet.current='';await worker.terminate()}}
function closeSheet(sheet){try{sheet&&sheet.bitmap&&sheet.bitmap.close&&sheet.bitmap.close()}catch(e){}}

async function runOCR(){const f=document.getElementById('frontPhoto').files[0],b=document.getElementById('backPhoto').files[0];if(!f||!b)return toast('Bitte beide Fotos auswählen.');if(!window.Tesseract)return toast('Texterkennung konnte nicht geladen werden.');const st=document.getElementById('ocrStatus'),btn=document.getElementById('ocrButton'),meta=document.getElementById('scanMeta');btn.disabled=true;btn.textContent='Erkennung läuft …';document.getElementById('candidatePairs').innerHTML='';document.getElementById('candidateTools').style.display='none';document.getElementById('saveCandidates').style.display='none';meta.classList.remove('show');let fs=null,bs=null;try{st.innerHTML='<span class="scanBusy"><span class="scanDot"></span>Kartenränder werden gesucht …</span>';[fs,bs]=await Promise.all([analyzeSheet(f),analyzeSheet(b)]);meta.innerHTML='<b>'+fs.boxes.length+' französische</b> und <b>'+bs.boxes.length+' deutsche</b> Karten gefunden.';meta.classList.add('show');const fr=await recognizeSheet(fs,'fr','Französisch',st),de=await recognizeSheet(bs,'de','Deutsch',st);const fm=new Map(fr.map(x=>[x.key,x.text])),dm=new Map(de.map(x=>[x.key,x.text]));let keys=[...new Set([...fm.keys(),...dm.keys()])];keys.sort((a,b)=>{const [ar,ac]=a.split('-').map(Number),[br,bc]=b.split('-').map(Number);return ar-br||ac-bc});const pairs=keys.map(k=>({fr:fm.get(k)||'',de:dm.get(k)||''}));renderCandidates(pairs);const filled=pairs.filter(x=>x.fr&&x.de).length;st.textContent='Fertig: '+filled+' Paare sind vollständig. Bitte kurz prüfen.'}catch(e){console.error(e);st.textContent='Die Erkennung hat nicht vollständig funktioniert. Du kannst die gefundenen Felder korrigieren oder Wörter manuell eintragen.';if(!document.querySelector('#candidatePairs .pairRow'))renderCandidates([{fr:'',de:''}])}finally{closeSheet(fs);closeSheet(bs);btn.disabled=false;btn.textContent='Karten automatisch erkennen'}}

function renderCandidates(pairs){const box=document.getElementById('candidatePairs');box.innerHTML='';if(pairs.length){const h=document.createElement('div');h.className='candidateHead';h.innerHTML='<span>Nr.</span><span>Französisch</span><span>Deutsch</span><span></span>';box.appendChild(h)}pairs.forEach((p,i)=>appendCandidateRow(p.fr,p.de,i+1));document.getElementById('candidateTools').style.display='flex';document.getElementById('saveCandidates').style.display='block'}
function appendCandidateRow(fr='',de='',n){const box=document.getElementById('candidatePairs');if(!box.querySelector('.candidateHead')){const h=document.createElement('div');h.className='candidateHead';h.innerHTML='<span>Nr.</span><span>Französisch</span><span>Deutsch</span><span></span>';box.appendChild(h)}const row=document.createElement('div');row.className='pairRow';row.innerHTML=`<span class="pairNo">${n||box.querySelectorAll('.pairRow').length+1}</span><input class="candFr" value="${esc(fr)}" placeholder="Französisch"><input class="candDe" value="${esc(de)}" placeholder="Deutsch"><button aria-label="Zeile löschen">×</button>`;row.querySelector('button').onclick=()=>{row.remove();renumberCandidates()};box.appendChild(row)}
function addCandidateRow(){appendCandidateRow('','');setTimeout(()=>{const rows=document.querySelectorAll('#candidatePairs .pairRow');rows[rows.length-1]?.querySelector('.candFr')?.focus()},20)}
function renumberCandidates(){document.querySelectorAll('#candidatePairs .pairRow .pairNo').forEach((n,i)=>n.textContent=i+1)}
function swapCandidateColumns(){document.querySelectorAll('#candidatePairs .pairRow').forEach(r=>{const a=r.querySelector('.candFr'),b=r.querySelector('.candDe'),v=a.value;a.value=b.value;b.value=v})}
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function saveCandidatePairs(){let added=0,skipped=0;document.querySelectorAll('#candidatePairs .pairRow').forEach(r=>{const fr=r.querySelector('.candFr').value.trim(),de=r.querySelector('.candDe').value.trim();if(!fr||!de){skipped++;return}if(!words.some(w=>w.fr.toLowerCase()===fr.toLowerCase()&&w.de.toLowerCase()===de.toLowerCase())){words.push({id:'u'+Date.now()+Math.random().toString(16).slice(2),fr,de,emoji:'💬',unit:'Meine Wörter',score:0,seen:0});added++}});saveWords();toast(added+' Wörter gespeichert'+(skipped?' · '+skipped+' unvollständig':'')+'.');document.getElementById('candidatePairs').innerHTML='';document.getElementById('candidateTools').style.display='none';document.getElementById('saveCandidates').style.display='none';document.getElementById('ocrStatus').textContent='';document.getElementById('scanMeta').classList.remove('show')}
