import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const js=await readFile(new URL('../compact-cockpit-v977.js',import.meta.url),'utf8');
const css=await readFile(new URL('../compact-cockpit-v977.css',import.meta.url),'utf8');
const docsCss=await readFile(new URL('../smart-documents-mobile-v973.css',import.meta.url),'utf8');
const sw=await readFile(new URL('../sw.js',import.meta.url),'utf8');
const loader=await readFile(new URL('../reference-mobile-v35.js',import.meta.url),'utf8');
const app=await readFile(new URL('../v9-app.js',import.meta.url),'utf8');
const dashboard=await readFile(new URL('../reference-dashboard-v36.js',import.meta.url),'utf8');
const daily=await readFile(new URL('../daily-check.js',import.meta.url),'utf8');
assert.match(js,/keine persönlichen to-dos für morgen/i,'empty tomorrow todo noise must be removed');
assert.match(js,/fc977-management-compact/,'secondary management tools must use compact visible layout');
assert.doesNotMatch(js,/grid\.hidden\s*=\s*true/,'management features must never be hidden by default');
assert.match(css,/#today[\s\S]*fc38-dashboard/,'today cockpit must be compacted');
assert.match(css,/\.fc-search-entry\{display:none!important\}/,'mobile search must move out of the content stream');
assert.match(app,/fc9-search-icon[\s\S]*data-open-search/,'search must remain available in the compact header');
assert.match(app,/fc982-calendar-controls/,'calendar mode and person filters must share one compact control row');
assert.doesNotMatch(app,/fc9-badge over/,'overdue homework must not repeat the same state in a second badge');
assert.match(dashboard,/function todayPanel\(\)\{const events=remainingEvents\(\);if\(!events\.length\)return''/,'empty today event panels must be omitted');
assert.match(dashboard,/return rows\.length\?[\s\S]*:''\}/,'empty child status panels must be omitted');
assert.match(daily,/function groupPackItems/,'daily check preparation must be grouped per person');
assert.match(css,/#tomorrow[\s\S]*fc674-tomorrow-children/,'tomorrow child preparation must be compacted');
assert.match(css,/#homework[\s\S]*fc9-tasktabs/,'tasks must be compacted');
assert.match(css,/#more[\s\S]*data-more-group="family"[\s\S]*min-height:68px/,'family tools must use scannable compact rows');
assert.match(css,/#more[\s\S]*data-more-group="manage"[\s\S]*min-height:60px/,'administration must use quieter compact rows');
assert.match(css,/#more[\s\S]*fc9-pend-row\{min-height:54px/,'pendency rows must stay visible but compact');
assert.doesNotMatch(css,/#more[\s\S]*(?:display\s*:\s*none|visibility\s*:\s*hidden)[\s\S]*data-more-group="manage"/,'management tools must not be hidden');
assert.match(docsCss,/fc-doc-search input\{height:44px!important;font-size:16px!important/,'document search must avoid iOS input zoom');
assert.match(docsCss,/fc-doc-review input\[type="text"\][\s\S]*font-size:16px!important/,'document title input must avoid iOS input zoom');
assert.match(docsCss,/fc-doc-person\{min-height:44px!important/,'document person selectors keep 44px touch targets');
assert.match(docsCss,/fc-doc-review button\{min-height:46px!important/,'document review actions keep accessible touch targets');
assert.match(docsCss,/fc-doc-proposal[\s\S]*padding:9px 10px!important/,'document proposals must be compact without clipping content');
assert.doesNotMatch(docsCss,/\.fc-doc-proposal[^\n]*max-height\s*:/,'document proposals must never be height-clipped');
assert.match(loader,/compact-cockpit-v977\.css/);
assert.match(loader,/compact-cockpit-v977\.js/);
assert.match(sw,/family-command-v119/);
assert.match(sw,/compact-cockpit-v977\.css/);
assert.match(sw,/compact-cockpit-v977\.js/);
console.log('V9.82 one-glance information architecture regression: ok');
