import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';
import { webcrypto } from 'node:crypto';
const source=await readFile(new URL('../smart-documents.js',import.meta.url),'utf8');
const state={people:[{id:'child-a',name:'Kind A'},{id:'child-b',name:'Kind B'}],events:[],homework:[],todos:[]};
let saves=0;
const sandbox={data:state,document:{addEventListener(){}},console,crypto:webcrypto,save(){saves++;}};
sandbox.window=sandbox;vm.createContext(sandbox);
// Test private pure helpers without adding a mutable production/debug API.
const marker='  window.__fcSmartDocumentsHealth=';
assert.ok(source.includes(marker));
vm.runInContext(source.replace(marker,'  window.reviewTest={issues,groupItems,applyItems,validDate};\n'+marker),sandbox);
const {issues,groupItems,applyItems,validDate}=sandbox.reviewTest;
const proposal={type:'event',title:'Ausflug',date:'2027-05-07',time:'08:20',end:'13:30',personId:'child-a',confidence:.99,note:'Mitnehmen: Jacke und Picknick.'};
const clean=v=>JSON.parse(JSON.stringify(v));
assert.equal(validDate('2028-02-29'),true);
for(const value of ['2027-02-29','2027-02-30','07.05.2027','2027-13-01','',null])assert.equal(validDate(value),false);
assert.deepEqual(clean(issues(proposal,[])),[]);
for(const patch of [{personId:'unknown'},{personId:''},{date:'2027-02-30'},{time:'24:00'},{time:'08:70'},{end:'07:00'},{endDate:'2027-05-06'},{title:''},{type:'invented'}])assert.ok(issues({...proposal,...patch},[]).length,JSON.stringify(patch));
assert.deepEqual(clean(issues({...proposal,personId:'unknown'},['child-b'])),[],'explicit manual assignment overrides the proposal');
assert.deepEqual(clean(issues({...proposal,endDate:'2027-05-08',end:'07:00'},[])),[],'overnight end is valid with a later end date');
const before=JSON.stringify(state),grouped=groupItems([proposal,{...proposal,personId:'child-b'}, {...proposal,title:'Unsicher',confidence:.1}]);
assert.equal(grouped.length,2);assert.deepEqual(clean(grouped[0].personIds),['child-a','child-b']);
assert.equal(grouped[1].confidence,.1,'low-confidence proposals are visible for review, not silently accepted or dropped');
assert.equal(JSON.stringify(state),before);assert.equal(saves,0,'building proposals cannot write data');
assert.deepEqual(clean(applyItems([], 'doc-empty')),[]);assert.equal(saves,0);
assert.throws(()=>applyItems([proposal,{...proposal,date:'2027-02-30'}],'doc-invalid'));
assert.equal(JSON.stringify(state),before,'invalid selection must fail before any partial mutation');
const first=applyItems([proposal],'doc-1');assert.equal(state.events.length,1);
assert.equal(state.events[0].note,proposal.note);assert.deepEqual(clean(state.events[0].personIds),['child-a']);
assert.equal(first[0].sourceKind,'event');assert.equal(first[0].sourceId,state.events[0].id);
applyItems([proposal],'doc-1');assert.equal(state.events.length,1,'retries cannot create duplicate events');
state.events[0].time='08:10';state.events[0].note='Manuell geprüfte Notiz';const existing=JSON.stringify(state.events[0]);
const relink=applyItems([proposal],'doc-2');assert.equal(state.events.length,1);assert.equal(JSON.stringify(state.events[0]),existing,'a corrected time and note are preserved');assert.equal(relink[0].sourceId,first[0].sourceId);
applyItems([{...proposal,personId:'child-b'}],'doc-3');assert.equal(state.events.length,2,'same title/date for another child is a different event');
assert.notEqual(state.events[0].id,state.events[1].id);
applyItems([{type:'homework',personId:'child-a',date:'2027-05-08',title:'Seite 12',note:'Buch mitnehmen'}],'doc-homework',['child-b']);
assert.equal(state.homework[0].personId,'child-b');assert.equal(state.homework[0].note,'Buch mitnehmen');
applyItems([{type:'reminder',personId:'child-a',date:'2027-05-08',title:'Rückmeldung',note:'Formular mitbringen'}],'doc-task');
assert.equal(state.todos[0].personId,'child-a');assert.equal(state.todos[0].note,'Formular mitbringen');
const id=state.todos[0].id;applyItems([{type:'reminder',personId:'child-a',date:'2027-05-08',title:'Rückmeldung'}],'doc-task');assert.equal(state.todos.length,1);assert.equal(state.todos[0].id,id);
assert.equal(sandbox.__fcSmartDocumentsHealth.reviewRequired,true);assert.equal(sandbox.__fcSmartDocumentsHealth.automaticImport,false);
console.log('document review unit regression: ok');
