import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';
const context = { localStorage: { getItem: () => null, setItem: () => {} }, console };
context.window = context;
vm.createContext(context);
vm.runInContext(await readFile(new URL('../core-runtime.js', import.meta.url), 'utf8'), context);
const event = { id: 'trip-example', title: 'Ausflug', date: '2027-05-07', time: '08:20', end: '13:30', personIds: ['child-example'], note: 'Besammlung: 08:20 Uhr. Mitnehmen: wetterfeste Kleidung, gute Schuhe, ein kleines Znüni und ein Mittagessen (Picknick). Rückkehr: 13:30 Uhr.' };
context.data.events = [event];
const before = JSON.stringify(context.data);
assert.equal(context.eventPackText(event), 'wetterfeste Kleidung, gute Schuhe, ein kleines Znüni und ein Mittagessen (Picknick)');
assert.equal(context.eventPreparationFor('child-example', '2027-05-07').length, 1);
assert.equal(context.eventPreparationFor('other-child', '2027-05-07').length, 0);
assert.equal(context.eventPreparationFor('child-example', '2027-05-06').length, 0);
assert.equal(context.eventPreparationFor('child-example', '2027-05-08').length, 0);
assert.equal(context.eventPackText({note:'Bei Regen findet ein Spaziergang statt.'}), '', 'never invent a packing list');
assert.equal(context.eventPackText({note:'Mitnehmen: z. B. ein Sandwich, Wasser und Schuhe.'}), 'z. B. ein Sandwich, Wasser und Schuhe', 'preserve abbreviations');
assert.equal(context.eventPackText({note:'Mitnehmen:\n- Jacke\n- Znüni\nRückkehr: 12:00 Uhr'}), '- Jacke - Znüni', 'preserve multiline lists, exclude the next labelled section');
assert.equal(context.eventPackText({note:'Mitnehmen: Regenjacke. Gute Schuhe. Bei Regen: Picknick drinnen.'}), 'Regenjacke. Gute Schuhe', 'do not drop multiple packing sentences');
assert.equal(context.eventPackText({note:'Niemand muss etwas mitnehmen.'}), '');
assert.equal(JSON.stringify(context.data), before, 'the read model must not change canonical data');
assert.equal(context.schoolDayFor('child-example', '2027-05-07').items.length, 0, 'an event must not invent school reminders or slots');
console.log('event preparation unit regression: ok');
