import { webkit } from 'playwright';
import { spawn } from 'node:child_process';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const PORT=4197,BASE=`http://127.0.0.1:${PORT}`;
const seed=readFileSync('family-command/e2e/mock-private-core.js','utf8');
const server=spawn('python3',['-m','http.server',String(PORT),'--directory','family-command'],{stdio:['ignore','pipe','pipe']});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function ready(){for(let i=0;i<60;i++){try{if((await fetch(BASE+'/index.html')).ok)return}catch{}await sleep(100)}throw new Error('server not ready')}
async function boot(browser,viewport,mobile=false){const ctx=await browser.newContext({viewport,isMobile:mobile,hasTouch:mobile,serviceWorkers:'block'});await ctx.addInitScript({content:seed});const page=await ctx.newPage();await page.goto(BASE+'/?access=test',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.documentElement.dataset.fcReady==='1'&&window.__fcV9&&window.__fcFamilyBudget?.version==='9.56.0',{timeout:20000});return{ctx,page}}
try{
 await ready();const browser=await webkit.launch({headless:true});const {ctx,page}=await boot(browser,{width:390,height:844},true);
 await page.locator('.fc9-nav button[data-screen="more"]').click();await page.waitForSelector('#more [data-fc-budget]');assert.match(await page.locator('#more [data-fc-budget]').innerText(),/Budget & Ausgaben/);await page.locator('#more [data-fc-budget]').click();await page.waitForSelector('#fcBudgetModal .fc-budget-shell');
 let initial=await page.evaluate(()=>{const shell=document.querySelector('.fc-budget-shell'),buttons=[...document.querySelectorAll('#fcBudgetModal button,#fcBudgetModal select')].filter(b=>{const r=b.getBoundingClientRect();return r.width&&r.height});return{overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth+1,w:shell.getBoundingClientRect().width,minControl:Math.min(...buttons.map(b=>b.getBoundingClientRect().height)),health:window.__fcFamilyBudget.health()}});console.log('budget-v956-mobile-initial',JSON.stringify(initial));assert.equal(initial.overflow,false);assert.ok(initial.w<=390);assert.ok(initial.minControl>=40);assert.equal(initial.health.transactions,0);assert.equal(initial.health.currency,'CHF');
 await page.locator('[data-edit-budget]').click();await page.locator('#fcBudgetAmount').fill('1500');await page.locator('#fcBudgetEdit [data-save]').click();await page.waitForFunction(()=>window.__fcFamilyBudget.health().budget===1500);
 await page.locator('[data-add-expense]').click();await page.locator('#fcBudgetTitle').fill('Wocheneinkauf');await page.locator('#fcBudgetValue').fill('123.45');await page.locator('#fcBudgetCat').selectOption('Lebensmittel');await page.locator('#fcBudgetEdit [data-save]').click();await page.waitForFunction(()=>window.__fcFamilyBudget.health().transactions===1);assert.match(await page.locator('.fc-budget-row').innerText(),/Wocheneinkauf/);
 await page.locator('[data-add-income]').click();await page.locator('#fcBudgetTitle').fill('Rückerstattung');await page.locator('#fcBudgetValue').fill('50');await page.locator('#fcBudgetCat').selectOption('Lohn');await page.locator('#fcBudgetEdit [data-save]').click();await page.waitForFunction(()=>window.__fcFamilyBudget.health().transactions===2);
 const totals=await page.evaluate(()=>{const vals=[...document.querySelectorAll('.fc-budget-summary b')].map(x=>x.textContent);return{vals,budget:window.__fcFamilyBudget.health().budget,count:window.__fcFamilyBudget.health().transactions}});console.log('budget-v956-totals',JSON.stringify(totals));assert.equal(totals.count,2);assert.equal(totals.budget,1500);assert.ok(totals.vals.some(x=>x.includes('123.45')||x.includes('123,45')));assert.ok(totals.vals.some(x=>x.includes('50.00')||x.includes('50,00')));
 await page.locator('[data-filter-type]').selectOption('expense');assert.equal(await page.locator('.fc-budget-row').count(),1);assert.match(await page.locator('.fc-budget-row').innerText(),/Wocheneinkauf/);await page.locator('[data-filter-type]').selectOption('all');
 await page.locator('.fc-budget-row').filter({hasText:'Wocheneinkauf'}).click();await page.locator('#fcBudgetValue').fill('100');await page.locator('#fcBudgetEdit [data-save]').click();await page.waitForFunction(()=>Object.values(data.finance.transactions).some(x=>x.title==='Wocheneinkauf'&&x.amount===100));
 page.on('dialog',d=>d.accept());await page.locator('.fc-budget-row').filter({hasText:'Wocheneinkauf'}).click();await page.locator('#fcBudgetEdit [data-remove]').click();await page.waitForFunction(()=>window.__fcFamilyBudget.health().transactions===1);assert.equal(await page.locator('.fc-budget-row').count(),1);
 await ctx.close();const desktop=await boot(browser,{width:1440,height:1000});await desktop.page.locator('.fc9-nav button[data-screen="more"]').click();await desktop.page.waitForSelector('#more [data-fc-budget]');await desktop.page.locator('#more [data-fc-budget]').click();await desktop.page.waitForSelector('.fc-budget-shell');const d=await desktop.page.evaluate(()=>{const r=document.querySelector('.fc-budget-shell').getBoundingClientRect();return{w:r.width,left:r.left,right:r.right,overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth+1,cols:getComputedStyle(document.querySelector('.fc-budget-summary')).gridTemplateColumns}});console.log('budget-v956-desktop',JSON.stringify(d));assert.equal(d.overflow,false);assert.ok(d.w>=800&&d.w<=1000);assert.ok(d.left>0&&d.right<1440);assert.match(d.cols,/px.*px.*px/);await desktop.ctx.close();await browser.close();console.log('V9.56 family budget regression: ok');
} finally {server.kill('SIGTERM')}
