import fs from 'node:fs';
const loader=fs.readFileSync(new URL('../reference-mobile-v35.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../header-crisp-v9654.css',import.meta.url),'utf8');
const structure=fs.readFileSync(new URL('../header-structure-v9654.js',import.meta.url),'utf8');
if(!loader.includes("finalCss('header-crisp-v9654.css','fc9654crisp')"))throw new Error('V9.66.9 crisp header stylesheet is not loaded last');
for(const token of ['filter:none!important','backdrop-filter:none!important','transform:none!important','will-change:auto!important','contain:none!important','background-color:#fff!important','position:static!important','background-image:none!important','color:#0b203b!important','-webkit-text-fill-color:#0b203b!important','font-size:18px!important','font-weight:750!important'])if(!css.includes(token))throw new Error(`missing V9.66.9 visible title guard: ${token}`);
for(const forbidden of ['header-binary-text-v9664.js','font-size:0!important','color:transparent!important','-webkit-text-fill-color:transparent!important','-webkit-font-smoothing:none!important','font-smooth:never!important','fc-wordmark-2x.png','fc-wordmark-3x.png'])if(css.includes(forbidden))throw new Error(`hidden/runtime-raster title must not return: ${forbidden}`);
if(!loader.includes("HEADER_V='20260906-v9669'"))throw new Error('V9.66.9 header cache version missing');
if(!loader.includes("fcHeaderRelease='v9669'"))throw new Error('V9.66.9 release marker missing');
if(!structure.includes("title.textContent='Familienzentrale'"))throw new Error('Familienzentrale title must be explicitly restored');
if(!structure.includes("subtitle.textContent='Alles im Blick. Alles im Griff.'"))throw new Error('subtitle must remain deterministic');
console.log('V9.66.9 visible Familienzentrale header regression ok');
