import fs from 'node:fs';
const loader=fs.readFileSync(new URL('../reference-mobile-v35.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../header-crisp-v9654.css',import.meta.url),'utf8');
if(!loader.includes("finalCss('header-crisp-v9654.css','fc9654crisp')"))throw new Error('V9.66.5 crisp header stylesheet is not loaded last');
for(const token of ['filter:none!important','backdrop-filter:none!important','transform:none!important','will-change:auto!important','contain:none!important','background-color:#fff!important','position:static!important','width:157px!important','height:20px!important','font-size:0!important','color:transparent!important','-webkit-text-fill-color:transparent!important','fc-wordmark-2x.png?v=20260906-v9665','fc-wordmark-3x.png?v=20260906-v9665','background-size:157px 20px!important','overflow:visible!important'])if(!css.includes(token))throw new Error(`missing V9.66.5 static wordmark guard: ${token}`);
for(const forbidden of ['header-binary-text-v9664.js','setInterval(refresh','MutationObserver','-webkit-font-smoothing:none!important','font-smooth:never!important','text-rendering:optimizeSpeed!important'])if(css.includes(forbidden))throw new Error(`runtime text rasterization must not return: ${forbidden}`);
if(!loader.includes("HEADER_V='20260906-v9665'"))throw new Error('V9.66.5 header cache version missing');
if(!loader.includes("fcHeaderRelease='v9665'"))throw new Error('V9.66.5 release marker missing');
if(loader.includes('header-binary-text-v9664.js'))throw new Error('binary canvas header renderer must stay removed');
console.log('V9.66.5 static Retina wordmark regression ok');
