import { webkit } from 'playwright';
import { spawn } from 'node:child_process';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const PORT=4194,BASE=`http://127.0.0.1:${PORT}`,seed=readFileSync('family-command/e2e/mock-private-core.js','utf8');
const server=spawn('python3',['-m','http.server',String(PORT),'--directory','family-command'],{stdio:['ignore','pipe','pipe']});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));async function ready(){for(let i=0;i<50;i++){try{if((await fetch(BASE+'/index.html')).ok)return}catch{}await sleep(100)}throw Error('server not ready')}
try{await ready();const browser=await webkit.launch({headless:true});
const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,serviceWorkers:'block'});await mobile.addInitScript({content:seed});const p=await mobile.newPage();await p.goto(BASE+'/?access=test',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>document.documentElement.dataset.fcReady==='1');await p.waitForFunction(()=>document.documentElement.dataset.fcMobileSchoolDay==='v47');
const m=await p.evaluate(()=>({grid:getComputedStyle(document.querySelector('.fc38-schoolgrid')).display,mobile:getComputedStyle(document.querySelector('.fc47-school-mobile')).display,tabs:document.querySelectorAll('.fc47-day').length,rows:document.querySelectorAll('.fc47-child').length,selected:document.querySelectorAll('.fc47-day.is-selected').length,overflow:document.documentElement.scrollWidth<=document.documentElement.clientWidth+1,bottomPadding:parseFloat(getComputedStyle(document.querySelector('.fc9-main')).paddingBottom)}));
assert.equal(m.grid,'none');assert.notEqual(m.mobile,'none');assert.equal(m.tabs,5);assert.equal(m.rows,3);assert.equal(m.selected,1);assert.equal(m.overflow,true);assert.ok(m.bottomPadding>=140);
const before=await p.locator('.fc47-day.is-selected').innerText();await p.locator('.fc47-day').nth(4).click();const after=await p.locator('.fc47-day.is-selected').innerText();assert.notEqual(before,after);await mobile.close();
const desktop=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});await desktop.addInitScript({content:seed});const d=await desktop.newPage();await d.goto(BASE+'/?access=test',{waitUntil:'domcontentloaded'});await d.waitForFunction(()=>document.documentElement.dataset.fcReady==='1');await d.waitForSelector('.fc38-schoolgrid');const x=await d.evaluate(()=>({grid:getComputedStyle(document.querySelector('.fc38-schoolgrid')).display,mobile:document.querySelector('.fc47-school-mobile')?getComputedStyle(document.querySelector('.fc47-school-mobile')).display:'missing'}));assert.notEqual(x.grid,'none');assert.ok(x.mobile==='missing'||x.mobile==='none');await desktop.close();await browser.close();console.log('V9.47 mobile school day regression: ok')}finally{server.kill('SIGTERM')}
