import { webkit } from 'playwright';
import { spawn } from 'node:child_process';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const PORT=4196,BASE=`http://127.0.0.1:${PORT}`;
const seed=readFileSync('family-command/e2e/mock-private-core.js','utf8');
const server=spawn('python3',['-m','http.server',String(PORT),'--directory','family-command'],{stdio:['ignore','pipe','pipe']});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function ready(){for(let i=0;i<60;i++){try{if((await fetch(BASE+'/index.html')).ok)return}catch{}await sleep(100)}throw new Error('server not ready')}
async function boot(browser,viewport,mobile=false){const ctx=await browser.newContext({viewport,isMobile:mobile,hasTouch:mobile,serviceWorkers:'block'});await ctx.addInitScript({content:seed});const page=await ctx.newPage();await page.goto(BASE+'/?access=test',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.documentElement.dataset.fcReady==='1'&&window.__fcV9&&window.__fcRecipes?.version==='9.55.0'&&window.__fcMealPlanner?.health?.().recipePlanning===true,{timeout:20000});return{ctx,page}}
try{
 await ready();const browser=await webkit.launch({headless:true});const {ctx,page}=await boot(browser,{width:390,height:844},true);
 await page.locator('.fc9-nav button[data-screen="more"]').click();await page.waitForSelector('#more [data-fc-recipes]');assert.match(await page.locator('#more [data-fc-recipes]').innerText(),/Rezepte & Favoriten/);await page.locator('#more [data-fc-recipes]').click();await page.waitForSelector('#fcRecipesModal .fc-recipes-shell');
 let initial=await page.evaluate(()=>{const shell=document.querySelector('.fc-recipes-shell'),buttons=[...document.querySelectorAll('#fcRecipesModal button')].filter(b=>{const r=b.getBoundingClientRect();return r.width&&r.height});return{overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth+1,w:shell.getBoundingClientRect().width,minButton:Math.min(...buttons.map(b=>b.getBoundingClientRect().height)),health:window.__fcRecipes.health()}});console.log('recipes-v955-mobile-initial',JSON.stringify(initial));assert.equal(initial.overflow,false);assert.ok(initial.w<=390);assert.ok(initial.minButton>=40);assert.equal(initial.health.recipes,0);assert.equal(initial.health.cloudCompatible,true);
 await page.locator('.fc-recipes-new').click();await page.locator('#fcRecipeTitle').fill('Spaghetti Carbonara');await page.locator('#fcRecipeMinutes').fill('20');await page.locator('#fcRecipeServings').fill('4');
 for(const [name,qty] of [['Spaghetti','500 g'],['Eier','4']]){await page.locator('[data-add-ing]').click();const row=page.locator('[data-ing-row]').last();await row.locator('[data-ing-name]').fill(name);await row.locator('[data-ing-qty]').fill(qty)}
 await page.locator('#fcRecipeInstructions').fill('Kochen, mischen, servieren.');await page.locator('#fcRecipeEdit [data-save]').click();await page.waitForFunction(()=>window.__fcRecipes.health().recipes===1);assert.match(await page.locator('.fc-recipe-card').innerText(),/Spaghetti Carbonara/);
 await page.locator('.fc-recipe-fav').click();await page.waitForFunction(()=>window.__fcRecipes.health().favorites===1);assert.match(await page.locator('#more [data-fc-recipes] span').innerText(),/1 ★/);
 await page.locator('.fc-recipes-search input').fill('Carbonara');assert.equal(await page.locator('.fc-recipe-card').count(),1);await page.locator('.fc-recipes-search input').fill('Pizza');assert.equal(await page.locator('.fc-recipe-card').count(),0);await page.locator('.fc-recipes-search input').fill('');
 await page.locator('.fc-recipe-open').click();await page.waitForSelector('#fcRecipeEdit [data-shopping]');await page.locator('#fcRecipeEdit [data-shopping]').click();await page.waitForFunction(()=>window.__fcShoppingLists.health().openItems===2);let shopping=await page.evaluate(()=>{const s=data.shopping,l=s.lists[s.activeListId];return Object.values(l.items||{}).filter(x=>x&&!x.archived&&!x.done).map(x=>x.title).sort()});assert.deepEqual(shopping,['Eier','Spaghetti']);
 await page.locator('.fc-recipe-open').click();await page.locator('#fcRecipeEdit [data-plan]').click();await page.waitForSelector('#fcRecipePlan');const today=await page.locator('#fcRecipePlanDate').inputValue();await page.locator('#fcRecipePlanType').selectOption('dinner');await page.locator('#fcRecipePlan [data-confirm]').click();await page.waitForFunction(({today})=>{const m=data.meals?.weeks||{};return Object.values(m).some(w=>w.days?.[today]?.dinner?.recipeId)},{today});let planned=await page.evaluate(today=>{for(const w of Object.values(data.meals.weeks||{})){const x=w.days?.[today]?.dinner;if(x)return{title:x.title,recipeId:x.recipeId,ingredients:x.ingredients?.length,source:x.source}}return null},today);console.log('recipes-v955-planned',JSON.stringify(planned));assert.equal(planned.title,'Spaghetti Carbonara');assert.ok(planned.recipeId);assert.equal(planned.ingredients,2);assert.equal(planned.source,'recipe');
 await page.locator('.fc-recipe-open').click();page.on('dialog',d=>d.accept());await page.locator('#fcRecipeEdit [data-delete]').click();await page.waitForFunction(()=>window.__fcRecipes.health().recipes===0);assert.equal(await page.locator('.fc-recipe-card').count(),0);
 await ctx.close();const desktop=await boot(browser,{width:1440,height:1000});await desktop.page.locator('.fc9-nav button[data-screen="more"]').click();await desktop.page.waitForSelector('#more [data-fc-recipes]');await desktop.page.locator('#more [data-fc-recipes]').click();await desktop.page.waitForSelector('.fc-recipes-shell');const d=await desktop.page.evaluate(()=>{const r=document.querySelector('.fc-recipes-shell').getBoundingClientRect();return{w:r.width,left:r.left,right:r.right,overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth+1,cols:getComputedStyle(document.querySelector('.fc-recipes-grid')).gridTemplateColumns}});console.log('recipes-v955-desktop',JSON.stringify(d));assert.equal(d.overflow,false);assert.ok(d.w>=800&&d.w<=1000);assert.ok(d.left>0&&d.right<1440);assert.match(d.cols,/px.*px/);await desktop.ctx.close();await browser.close();console.log('V9.55 recipes & favorites regression: ok');
} finally {server.kill('SIGTERM')}
