import { webkit } from 'playwright';
import { spawn } from 'node:child_process';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const PORT=4189,BASE=`http://127.0.0.1:${PORT}`;
const seed=readFileSync('family-command/e2e/mock-private-core.js','utf8');
const server=spawn('python3',['-m','http.server',String(PORT),'--directory','family-command'],{stdio:['ignore','pipe','pipe']});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function ready(){for(let i=0;i<60;i++){try{const r=await fetch(BASE+'/index.html');if(r.ok)return}catch{}await sleep(100)}throw new Error('server not ready')}
try{
 await ready();const browser=await webkit.launch({headless:true});const ctx=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,serviceWorkers:'block'});await ctx.addInitScript({content:seed});const page=await ctx.newPage();await page.goto(BASE+'/?access=test',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.documentElement.dataset.fcReady==='1'&&window.__fcV9);
 await page.evaluate(()=>{const iso=typeof todayISO==='function'?todayISO():(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`})();const d=new Date(`${iso}T12:00:00`),day=d.getDay();d.setDate(d.getDate()+1);const tomorrow=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;data.todos=[{id:'gift',date:iso,title:'Pokémon-Karten als Geschenk kaufen',priority:true,done:false,section:'day'},{id:'shop',date:iso,title:'Maggi kaufen',priority:true,done:false,section:'day'},{id:'normal',date:iso,title:'Normale offene Aufgabe',priority:false,done:false,section:'day'}];data.events=[{id:'visit',personIds:['child-a'],title:'Schulbesuch',date:iso,time:'13:40',note:'PET-Flaschen mitnehmen'},{id:'birthday',personIds:['child-a'],title:'Geburtstag Alessio',date:tomorrow,time:'13:30'}];for(const p of (data.people||[]).filter(p=>p.id!=='oli')){data.schedules[p.id]??={};for(const wd of [1,2,3,4,5])data.schedules[p.id][wd]=[{start:wd===3?'07:30':'08:20',end:'11:55',label:'Schule / Kindergarten',note:wd===3?'Turnzeug einpacken':''}]}save?.();window.renderToday?.()});
 await page.waitForFunction(()=>document.documentElement.dataset.fcReferenceDashboard==='v36');
 const r=await page.evaluate(()=>{const before=JSON.stringify({todos:data.todos,events:data.events,homework:data.homework,people:data.people,schedules:data.schedules});window.__fcReferenceDashboard36.rebuild(true);const after=JSON.stringify({todos:data.todos,events:data.events,homework:data.homework,people:data.people,schedules:data.schedules});const dash=document.querySelector('#today>.fc36-dashboard'),source=document.querySelector('#today>.fc9-page'),tasks=[...dash.querySelectorAll('.fc36-task')],timeline=[...dash.querySelectorAll('.fc36-line')],school=dash.querySelector('.fc36-school');return{same:before===after,version:window.__fcReferenceDashboard36.version,dashboard:!!dash,sourceDisplay:getComputedStyle(source).position,sourceWidth:source.getBoundingClientRect().width,overflow:document.documentElement.scrollWidth<=document.documentElement.clientWidth+1,daybar:dash.querySelector('.fc36-daybar')?.getBoundingClientRect().height||0,panels:dash.querySelectorAll('.fc36-panel').length,tasks:tasks.length,taskHeights:tasks.map(x=>x.getBoundingClientRect().height),timeline:timeline.length,schoolCells:school?.children.length||0,order:[...dash.children].map(x=>x.className),nav:document.querySelector('.fc9-nav')?.getBoundingClientRect().height||0,headings:[...dash.querySelectorAll('.fc36-panelhead h2')].map(x=>x.textContent.trim())}});
 console.log('reference-dashboard-v36',JSON.stringify(r));
 assert.equal(r.version,'9.36.0');assert.equal(r.dashboard,true);assert.equal(r.same,true,'visual dashboard must not mutate family state');assert.equal(r.overflow,true);assert.ok(r.sourceWidth<=1.5,'legacy today page must be visually removed from mobile layout');assert.ok(r.daybar>25&&r.daybar<55);assert.ok(r.panels>=4,'reference dashboard must expose task, today, tomorrow and school panels');assert.equal(r.tasks,3,'all open tasks must remain visible');for(const h of r.taskHeights)assert.ok(h>=38&&h<=56,`task rows must be compact and tappable: ${h}`);assert.ok(r.timeline>=2,'today overview must include events/routine rows');assert.ok(r.schoolCells>=18,'school week grid must remain available');assert.ok(r.headings.some(x=>x.includes('Das Wichtigste zuerst')));assert.ok(r.headings.some(x=>x.includes('im Überblick')));assert.ok(r.headings.some(x=>x.includes('Vorschau')));assert.ok(r.headings.some(x=>x.includes('Schulzeiten')));assert.ok(r.nav>45,'bottom navigation must remain available');
 await browser.close();console.log('V9.36 reference dashboard regression: ok');
}finally{server.kill('SIGTERM')}
