import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../reference-mobile-v35.js',import.meta.url),'utf8');
const base='https://example.test/HomepageProjekt/family-command/';
const links=[{rel:'stylesheet',href:base+'v9-global-polish.css?v=20260904-v9617',dataset:{}},{rel:'stylesheet',href:base+'v9-unified-design-v958.css?v=20260904-v9617',dataset:{}},{rel:'stylesheet',href:base+'v9-final-unity-v9618.css?v=20260904-v9617',dataset:{}},{rel:'stylesheet',href:base+'v9-design-system-v9619.css?v=20260904-v9617',dataset:{}},{rel:'stylesheet',href:base+'v9-layout-final-v9622.css?v=20260904-v9617',dataset:{}},{rel:'stylesheet',href:base+'sharp-header-v9643.css?v=20260904-v9617',dataset:{}},{rel:'stylesheet',href:base+'header-native-v9652.css?v=20260904-v9617',dataset:{}}];
const scripts=[];const documentElement={dataset:{}};
const document={readyState:'complete',documentElement,querySelector(selector){const m=selector.match(/^script\[data-([^\]]+)\]$/);return m?scripts.find(s=>s.dataset?.[m[1]])||null:null},querySelectorAll(selector){return selector==='link[rel="stylesheet"]'?links:[]},createElement(tag){return {tagName:String(tag).toUpperCase(),dataset:{},rel:'',href:'',src:'',async:true}},head:{appendChild(node){const i=links.indexOf(node);if(i>=0)links.splice(i,1);links.push(node);return node}},body:{appendChild(node){scripts.push(node);return node}},addEventListener(){throw new Error('DOMContentLoaded listener must not be needed when readyState=complete')}};
const window={};const location={href:base,hostname:'example.test'};vm.runInNewContext(source,{window,document,location,URL,console});
const byFile=file=>links.filter(l=>new URL(l.href,base).pathname.endsWith('/'+file));
for(const file of ['v9-global-polish.css','v9-unified-design-v958.css','v9-final-unity-v9618.css','v9-design-system-v9619.css','v9-layout-final-v9622.css','sharp-header-v9643.css','header-native-v9652.css','header-structure-v9654.css','header-crisp-v9654.css'])assert.equal(byFile(file).length,1,file);
assert.deepEqual(links.slice(-8).map(l=>new URL(l.href,base).pathname.split('/').pop()),['v9-unified-design-v958.css','v9-final-unity-v9618.css','v9-design-system-v9619.css','v9-layout-final-v9622.css','sharp-header-v9643.css','header-native-v9652.css','header-structure-v9654.css','header-crisp-v9654.css']);
assert.match(source,/20260903-v9520/);assert.equal(scripts.filter(s=>String(s.src).includes('header-structure-v9654.js')).length,1);
for(const file of ['sharp-header-v9643.css','header-native-v9652.css','header-structure-v9654.css','header-crisp-v9654.css'])assert.equal(new URL(byFile(file)[0].href,base).searchParams.get('v'),'20260906-v9660',file);
assert.equal(new URL(scripts.find(s=>s.src.includes('header-structure-v9654.js')).src,base).searchParams.get('v'),'20260906-v9660');
assert.equal(documentElement.dataset.fcHeaderRelease,'v9660');
console.log('ok reference loader dedupe V9.66.0');
