import { webkit } from 'playwright';
import { spawn } from 'node:child_process';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const PORT=4197,BASE=`http://127.0.0.1:${PORT}`,seed=readFileSync('family-command/e2e/mock-private-core.js','utf8');
const server=spawn('python3',['-m','http.server',String(PORT),'--directory','family-command'],{stdio:['ignore','pipe','pipe']});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));async function ready(){for(let i=0;i<60;i++){try{if((await fetch(BASE+'/index.html')).ok)return}catch{}await sleep(100)}throw Error('server not ready')}
try{await ready();const browser=await webkit.launch({headless:true});const ctx=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,serviceWorkers:'block'});await ctx.addInitScript({content:seed});const p=await ctx.newPage();await p.goto(BASE+'/?access=test',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>document.documentElement.dataset.fcReady==='1'&&window.__fcV9&&window.__fcTomorrowCalendarV9673,{timeout:30000});
await p.evaluate(()=>{const t=todayISO(),d=new Date(`${t}T12:00:00`);d.setDate(d.getDate()+1);const tomorrow=d.toISOString().slice(0,10),wd=new Date(`${tomorrow}T12:00:00`).getDay();for(const person of(data.people||[]).filter(x=>x.id!=='oli')){data.schedules[person.id]??={};data.schedules[person.id][wd]=[{start:'08:20',end:'11:55',label:/elia|eliya/i.test(`${person.id} ${person.name}`)?'Kindergarten':'Schule',note:'Turnschuhe in den Rucksack mitnehmen'}]}window.renderTomorrow?.()});
await p.locator('[data-screen="tomorrow"]').click();await p.waitForFunction(()=>document.querySelector('#tomorrow .fc673-tomorrow-pack'));const pack=await p.evaluate(()=>({rows:document.querySelectorAll('#tomorrow .fc673-packchild').length,text:document.querySelector('#tomorrow .fc673-tomorrow-pack')?.textContent||'',version:document.documentElement.dataset.fcTomorrowPack||''}));assert.equal(pack.rows,(await p.evaluate(()=>(data.people||[]).filter(x=>x.id!=='oli').length)));assert.match(pack.text,/MITNEHMEN/);assert.match(pack.text,/Schultasche/);assert.match(pack.text,/Trinkflasche/);assert.match(pack.text,/Turnzeug/);assert.equal(pack.version,'v673');
await p.locator('[data-screen="events"]').click();await p.waitForFunction(()=>document.querySelector('#events .fc673-monthgrid'));const buttons=p.locator('#events [data-fc673-date]');assert.ok(await buttons.count()>=28);const target=await buttons.nth(Math.min(7,(await buttons.count())-1)).getAttribute('data-fc673-date');await buttons.nth(Math.min(7,(await buttons.count())-1)).click();await p.waitForFunction(date=>window.__fcV9?.state?.calendarMode==='week'&&window.__fcV9?.state?.weekDate===date,target);assert.equal(await p.evaluate(()=>window.__fcV9.state.calendarMode),'week');assert.equal(await p.evaluate(()=>window.__fcV9.state.weekDate),target);assert.ok(await p.locator('#events [data-week-date]').count()>=5);await browser.close();console.log('V9.67.3 tomorrow/calendar regression: ok')}finally{server.kill('SIGTERM')}
