import { webkit } from 'playwright';
import { spawn } from 'node:child_process';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const PORT=4197,BASE=`http://127.0.0.1:${PORT}`,seed=readFileSync('family-command/e2e/mock-private-core.js','utf8');
const server=spawn('python3',['-m','http.server',String(PORT),'--directory','family-command'],{stdio:['ignore','pipe','pipe']});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));async function ready(){for(let i=0;i<60;i++){try{if((await fetch(BASE+'/index.html')).ok)return}catch{}await sleep(100)}throw Error('server not ready')}
try{await ready();const browser=await webkit.launch({headless:true});const ctx=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,serviceWorkers:'block'});await ctx.addInitScript({content:seed});const p=await ctx.newPage();await p.goto(BASE+'/?access=test',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>document.documentElement.dataset.fcReady==='1'&&window.__fcV9&&window.__fcTomorrowCalendarV9674,{timeout:30000});
const surface=await p.evaluate(()=>({html:getComputedStyle(document.documentElement).backgroundColor,body:getComputedStyle(document.body).backgroundColor,app:getComputedStyle(document.getElementById('fcApp')).backgroundColor}));for(const value of Object.values(surface))assert.notEqual(value,'rgba(0, 0, 0, 0)');
await p.evaluate(()=>{const t=todayISO(),d=new Date(`${t}T12:00:00`);d.setDate(d.getDate()+1);const tomorrow=d.toISOString().slice(0,10),wd=new Date(`${tomorrow}T12:00:00`).getDay();for(const person of(data.people||[]).filter(x=>x.id!=='oli')){data.schedules[person.id]??={};data.schedules[person.id][wd]=[{start:'08:20',end:'11:55',label:/elia|eliya/i.test(`${person.id} ${person.name}`)?'Kindergarten':'Turnen',note:'Turnschuhe in den Rucksack mitnehmen'}]}window.renderTomorrow?.()});
await p.locator('[data-screen="tomorrow"]').click();await p.waitForFunction(()=>document.querySelector('#tomorrow .fc674-tomorrow-children .fc674-inline-pack'));const tomorrowView=await p.evaluate(()=>({separate:!!document.querySelector('#tomorrow .fc673-tomorrow-pack'),rows:document.querySelectorAll('#tomorrow .fc674-tomorrow-children .fc9-person').length,inline:document.querySelectorAll('#tomorrow .fc674-inline-pack').length,text:document.querySelector('#tomorrow .fc674-tomorrow-children')?.textContent||'',version:document.documentElement.dataset.fcTomorrowCompact||''}));assert.equal(tomorrowView.separate,false);assert.equal(tomorrowView.inline,tomorrowView.rows);assert.match(tomorrowView.text,/08:20/);assert.match(tomorrowView.text,/Turnen/);assert.match(tomorrowView.text,/Turnzeug mitnehmen/);assert.equal(tomorrowView.version,'v674');
await p.locator('[data-screen="events"]').click();await p.evaluate(()=>{window.__fcV9.state.calendarMode='agenda';window.__fcV9.state.calendarMonth=new Date(2026,8,1,12);window.__fcV9.invalidate('events');window.__fcV9.render('events',true);window.__fcTomorrowCalendarV9674.render()});await p.waitForFunction(()=>document.querySelector('#events [data-fc673-date="2026-09-07"]'));await p.locator('#events [data-fc673-date="2026-09-07"]').click();await p.waitForFunction(()=>window.__fcV9?.state?.calendarMode==='week'&&window.__fcV9?.state?.weekDate==='2026-09-07');await p.locator('#events [data-week-date="2026-09-08"]').click();await p.waitForFunction(()=>window.__fcV9?.state?.weekDate==='2026-09-08');let stateAfter=await p.evaluate(()=>({mode:window.__fcV9?.state?.calendarMode,date:window.__fcV9?.state?.weekDate,activeText:document.querySelector('#events [data-week-date].active')?.textContent||'',selected:document.documentElement.dataset.fcCalendarSelectedDate||''}));assert.equal(stateAfter.mode,'week');assert.equal(stateAfter.date,'2026-09-08');assert.equal(stateAfter.selected,'2026-09-08');assert.match(stateAfter.activeText,/8\.9\./);await p.locator('#events [data-week-date="2026-09-07"]').click();await p.waitForFunction(()=>window.__fcV9?.state?.weekDate==='2026-09-07');stateAfter=await p.evaluate(()=>({date:window.__fcV9?.state?.weekDate,activeText:document.querySelector('#events [data-week-date].active')?.textContent||''}));assert.equal(stateAfter.date,'2026-09-07');assert.match(stateAfter.activeText,/7\.9\./);await browser.close();console.log('V9.67.4 tomorrow/calendar regression: ok')}finally{server.kill('SIGTERM')}
